package mcpsync

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/mvanhorn/cli-printing-press/v2/internal/generator"
	"github.com/mvanhorn/cli-printing-press/v2/internal/pipeline"
	"github.com/mvanhorn/cli-printing-press/v2/internal/spec"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestSyncBackfillsEndpointAnnotations(t *testing.T) {
	t.Parallel()

	apiSpec := &spec.APISpec{
		Name:    "synctest",
		Version: "0.1.0",
		BaseURL: "https://api.example.com",
		Auth: spec.AuthConfig{
			Type:    "api_key",
			Header:  "Authorization",
			Format:  "Bearer {token}",
			EnvVars: []string{"SYNCTEST_TOKEN"},
		},
		Config: spec.ConfigSpec{
			Format: "toml",
			Path:   "~/.config/synctest-pp-cli/config.toml",
		},
		Resources: map[string]spec.Resource{
			"projects": {
				Description: "Manage projects",
				Endpoints: map[string]spec.Endpoint{
					"list": {Method: "GET", Path: "/projects", Description: "List projects"},
					"get":  {Method: "GET", Path: "/projects/{id}", Description: "Get a project"},
				},
			},
		},
	}

	cliDir := filepath.Join(t.TempDir(), "synctest")
	gen := generator.New(apiSpec, cliDir)
	require.NoError(t, gen.Generate())

	specData, err := yaml.Marshal(apiSpec)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(cliDir, "spec.yaml"), specData, 0o644))

	endpointPath := filepath.Join(cliDir, "internal", "cli", "projects_list.go")
	endpointData, err := os.ReadFile(endpointPath)
	require.NoError(t, err)
	withoutAnnotation := endpointAnnotationLine.ReplaceAllString(string(endpointData), "")
	require.NotContains(t, withoutAnnotation, `"pp:endpoint"`)
	require.NoError(t, os.WriteFile(endpointPath, []byte(withoutAnnotation), 0o644))

	oldTools := `// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package mcp

func RegisterNovelFeatureTools() { shellOutToCLI("projects list") }
`
	require.NoError(t, os.WriteFile(filepath.Join(cliDir, "internal", "mcp", "tools.go"), []byte(oldTools), 0o644))

	result, err := Sync(cliDir, Options{})
	require.NoError(t, err)
	assert.True(t, result.Changed)

	updatedEndpoint, err := os.ReadFile(endpointPath)
	require.NoError(t, err)
	assert.Contains(t, string(updatedEndpoint), `Annotations: map[string]string{"pp:endpoint": "projects.list"}`)

	updatedTools, err := os.ReadFile(filepath.Join(cliDir, "internal", "mcp", "tools.go"))
	require.NoError(t, err)
	assert.Contains(t, string(updatedTools), "cobratree.RegisterAll")
}

func TestEnsureRootCmdExportPreservesRootFlagPointer(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(cliDir, "internal", "cli"), 0o755))
	rootPath := filepath.Join(cliDir, "internal", "cli", "root.go")
	require.NoError(t, os.WriteFile(rootPath, []byte(`// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

import "github.com/spf13/cobra"

type rootFlags struct{}

// Execute runs the CLI in non-interactive mode: never prompts, all values via flags or stdin.
func Execute() error {
	var flags rootFlags

	rootCmd := &cobra.Command{
		Use: "synctest-pp-cli",
	}
	rootCmd.AddCommand(newDoctorCmd(&flags))

	err := rootCmd.Execute()
	return err
}

func newDoctorCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{Use: "doctor"}
}

func ExitCode(err error) int { return 0 }
`), 0o644))

	require.NoError(t, ensureRootCmdExport(cliDir))

	updated, err := os.ReadFile(rootPath)
	require.NoError(t, err)
	src := string(updated)
	assert.Contains(t, src, "return newRootCmd(&flags)")
	assert.Contains(t, src, "rootCmd := newRootCmd(&flags)")
	assert.Contains(t, src, "rootCmd.AddCommand(newDoctorCmd(flags))")
	assert.NotContains(t, src, "newRootCmd(flags)")
}

// TestSyncRegeneratesStaleCliutil locks the contract that mcp-sync
// regenerates the cliutil package alongside MCP source. Older library
// CLIs ship cliutil packages that predate helpers the new MCP template
// uses (SanitizeErrorBody, LooksLikeAuthError); without regeneration
// the regenerated tools.go fails to build with "undefined:
// cliutil.SanitizeErrorBody". This test simulates that drift by
// stubbing cliutil/text.go with a minimal file lacking
// SanitizeErrorBody, runs Sync, and asserts the regenerated file
// carries the helper.
func TestSyncRegeneratesStaleCliutil(t *testing.T) {
	t.Parallel()

	apiSpec := &spec.APISpec{
		Name:    "cliutiltest",
		Version: "0.1.0",
		BaseURL: "https://api.example.com",
		Auth: spec.AuthConfig{
			Type:    "api_key",
			Header:  "Authorization",
			Format:  "Bearer {token}",
			EnvVars: []string{"CLIUTILTEST_TOKEN"},
		},
		Config: spec.ConfigSpec{
			Format: "toml",
			Path:   "~/.config/cliutiltest-pp-cli/config.toml",
		},
		Resources: map[string]spec.Resource{
			"items": {
				Description: "Manage items",
				Endpoints: map[string]spec.Endpoint{
					"list": {Method: "GET", Path: "/items", Description: "List items"},
				},
			},
		},
	}

	cliDir := filepath.Join(t.TempDir(), "cliutiltest")
	gen := generator.New(apiSpec, cliDir)
	require.NoError(t, gen.Generate())

	specData, err := yaml.Marshal(apiSpec)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(cliDir, "spec.yaml"), specData, 0o644))

	// Stub cliutil/text.go with the marker but without SanitizeErrorBody.
	// Mirrors the actual drift pattern in open-meteo: the file is generator-
	// emitted, just from an older template version that didn't ship the
	// helper yet.
	textPath := filepath.Join(cliDir, "internal", "cliutil", "text.go")
	staleText := `// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cliutil

// CleanText is the only helper this older template emitted.
func CleanText(s string) string { return s }
`
	require.NoError(t, os.WriteFile(textPath, []byte(staleText), 0o644))

	// Stub tools.go so Sync detects MCPSurfaceStaticList state and runs
	// the migration path (which calls GenerateMCPSurface).
	oldTools := `// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package mcp

func RegisterNovelFeatureTools() { shellOutToCLI("items list") }
`
	require.NoError(t, os.WriteFile(filepath.Join(cliDir, "internal", "mcp", "tools.go"), []byte(oldTools), 0o644))

	result, err := Sync(cliDir, Options{})
	require.NoError(t, err)
	assert.True(t, result.Changed)

	regenerated, err := os.ReadFile(textPath)
	require.NoError(t, err)
	src := string(regenerated)
	assert.Contains(t, src, "SanitizeErrorBody", "cliutil/text.go should be regenerated with SanitizeErrorBody")
	assert.NotContains(t, src, "// CleanText is the only helper this older template emitted.", "stale stub content should be replaced")
}

// TestSyncRefreshesProvenanceFromSpec locks the contract that mcp-sync
// updates .printing-press.json's spec-derived fields from the current
// spec.yaml. Pre-fix, mcp-sync wrote manifest.json from stale provenance,
// so spec.yaml updates to auth.key_url, auth.optional, auth.env_vars,
// etc. never reached the MCPB Configure modal until someone hand-injected
// them into .printing-press.json. Bit recipe-goat twice in one session.
func TestSyncRefreshesProvenanceFromSpec(t *testing.T) {
	t.Parallel()

	// Step 1: generate the CLI with an initial spec (no key_url, not optional).
	apiSpec := &spec.APISpec{
		Name:    "provrefresh",
		Version: "0.1.0",
		BaseURL: "https://api.example.com",
		Auth: spec.AuthConfig{
			Type:    "api_key",
			Header:  "Authorization",
			Format:  "Bearer {token}",
			EnvVars: []string{"PROVREFRESH_TOKEN"},
		},
		Config: spec.ConfigSpec{
			Format: "toml",
			Path:   "~/.config/provrefresh-pp-cli/config.toml",
		},
		Resources: map[string]spec.Resource{
			"items": {
				Description: "Manage items",
				Endpoints: map[string]spec.Endpoint{
					"list": {Method: "GET", Path: "/items", Description: "List items"},
				},
			},
		},
	}
	cliDir := filepath.Join(t.TempDir(), "provrefresh")
	gen := generator.New(apiSpec, cliDir)
	require.NoError(t, gen.Generate())

	// Step 2: simulate a generate-time provenance write. WriteManifestForGenerate
	// is what cli/generate.go calls; the test exercises the same path.
	require.NoError(t, pipeline.WriteManifestForGenerate(pipeline.GenerateManifestParams{
		APIName:   apiSpec.Name,
		OutputDir: cliDir,
		Spec:      apiSpec,
	}))

	// Step 3: edit spec.yaml with the new auth.key_url + auth.optional that
	// the original spec lacked. This is the field-update scenario that
	// breaks without provenance refresh.
	apiSpec.Auth.KeyURL = "https://example.com/get-a-token"
	apiSpec.Auth.Optional = true
	specData, err := yaml.Marshal(apiSpec)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(cliDir, "spec.yaml"), specData, 0o644))

	// Step 4: run mcp-sync. It should pick up the new spec values and
	// refresh .printing-press.json + manifest.json.
	result, err := Sync(cliDir, Options{})
	require.NoError(t, err)
	assert.True(t, result.Changed)

	// Step 5: verify .printing-press.json now reflects the new spec.
	provData, err := os.ReadFile(filepath.Join(cliDir, pipeline.CLIManifestFilename))
	require.NoError(t, err)
	var prov pipeline.CLIManifest
	require.NoError(t, json.Unmarshal(provData, &prov))
	assert.Equal(t, "https://example.com/get-a-token", prov.AuthKeyURL, "auth_key_url must refresh from spec.yaml on mcp-sync")
	assert.True(t, prov.AuthOptional, "auth_optional must refresh from spec.yaml on mcp-sync")

	// Step 6: verify the MCPB manifest also reflects the new spec — this
	// is the user-visible failure mode (Configure modal wording / Required
	// flag). Confirms the full chain spec.yaml → .printing-press.json →
	// manifest.json works end-to-end.
	manifestData, err := os.ReadFile(filepath.Join(cliDir, pipeline.MCPBManifestFilename))
	require.NoError(t, err)
	manifestStr := string(manifestData)
	assert.Contains(t, manifestStr, "https://example.com/get-a-token", "manifest description should surface key_url after refresh")
	assert.Contains(t, manifestStr, `"description": "Optional. Sets`, "manifest description should reflect auth_optional with the Optional. prefix")
}

// TestValidateSpecNameMatchesDirAccepts ensures matching name and dir
// pass the preflight without error. The dir basename is the source of
// truth for the package identity (it appears in go.mod, in directory
// listings, in the published library URL); spec.yaml.name should track it.
func TestValidateSpecNameMatchesDirAccepts(t *testing.T) {
	t.Parallel()
	cliDir := filepath.Join(t.TempDir(), "weather-goat")
	require.NoError(t, os.MkdirAll(cliDir, 0o755))
	parsed := &spec.APISpec{Name: "weather-goat"}
	if err := validateSpecNameMatchesDir(cliDir, parsed); err != nil {
		t.Errorf("matching name should accept; got %v", err)
	}
}

// TestValidateSpecNameMatchesDirRejectsDrift catches the weather-goat
// class of bug: spec.yaml.name = "weather" but directory is
// "weather-goat" because an old rename never updated the spec.
func TestValidateSpecNameMatchesDirRejectsDrift(t *testing.T) {
	t.Parallel()
	cliDir := filepath.Join(t.TempDir(), "weather-goat")
	require.NoError(t, os.MkdirAll(cliDir, 0o755))
	parsed := &spec.APISpec{Name: "weather"}
	err := validateSpecNameMatchesDir(cliDir, parsed)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "spec.yaml name \"weather\"")
	assert.Contains(t, err.Error(), "directory basename \"weather-goat\"")
	assert.Contains(t, err.Error(), "--force")
}

// TestValidateSpecNameMatchesDirNoOpOnEmptySpec — a nil spec or empty
// name skips validation. The downstream loadArchivedSpec already errors
// on missing spec; this layer doesn't need to redundantly check.
func TestValidateSpecNameMatchesDirNoOpOnEmptySpec(t *testing.T) {
	t.Parallel()
	cliDir := filepath.Join(t.TempDir(), "anything")
	require.NoError(t, os.MkdirAll(cliDir, 0o755))
	if err := validateSpecNameMatchesDir(cliDir, nil); err != nil {
		t.Errorf("nil spec should not error; got %v", err)
	}
	if err := validateSpecNameMatchesDir(cliDir, &spec.APISpec{}); err != nil {
		t.Errorf("empty name should not error; got %v", err)
	}
}

// TestRemoveStaleMCPHandlersFile locks behavior for the food52 case:
// older generator templates emitted MCP handlers in a separate
// internal/mcp/handlers.go; the current template emits everything in
// tools.go. mcp-sync needs to delete the stale handlers.go before
// regenerating to avoid "handleContext redeclared in this block"
// build errors.
func TestRemoveStaleMCPHandlersFile(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	mcpDir := filepath.Join(cliDir, "internal", "mcp")
	require.NoError(t, os.MkdirAll(mcpDir, 0o755))
	handlersPath := filepath.Join(mcpDir, "handlers.go")
	require.NoError(t, os.WriteFile(handlersPath, []byte(`// Copyright 2026 trevin-chow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package mcp
func handleContext() {}
`), 0o644))

	require.NoError(t, removeStaleMCPHandlersFile(cliDir, false))

	if _, err := os.Stat(handlersPath); !os.IsNotExist(err) {
		t.Errorf("expected handlers.go to be removed; stat err: %v", err)
	}
}

func TestRemoveStaleMCPHandlersFileNoOpWhenAbsent(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(cliDir, "internal", "mcp"), 0o755))

	if err := removeStaleMCPHandlersFile(cliDir, false); err != nil {
		t.Errorf("expected no error when handlers.go is absent, got: %v", err)
	}
}

func TestRemoveStaleMCPHandlersFileRefusesHandEdits(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	mcpDir := filepath.Join(cliDir, "internal", "mcp")
	require.NoError(t, os.MkdirAll(mcpDir, 0o755))
	handlersPath := filepath.Join(mcpDir, "handlers.go")
	// Hand-edited: marker absent. Removing this would destroy custom logic.
	require.NoError(t, os.WriteFile(handlersPath, []byte(`package mcp
// Hand-written by maintainer. Marker stripped on purpose.
func handleContext() {}
`), 0o644))

	err := removeStaleMCPHandlersFile(cliDir, false)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "appears hand-edited")
	if _, err := os.Stat(handlersPath); err != nil {
		t.Errorf("handlers.go should still exist after refusal; stat err: %v", err)
	}
}

func TestRemoveStaleMCPHandlersFileForceOverride(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	mcpDir := filepath.Join(cliDir, "internal", "mcp")
	require.NoError(t, os.MkdirAll(mcpDir, 0o755))
	handlersPath := filepath.Join(mcpDir, "handlers.go")
	require.NoError(t, os.WriteFile(handlersPath, []byte(`package mcp
// Hand-written. --force will delete this anyway.
func handleContext() {}
`), 0o644))

	require.NoError(t, removeStaleMCPHandlersFile(cliDir, true))

	if _, err := os.Stat(handlersPath); !os.IsNotExist(err) {
		t.Errorf("expected --force to remove hand-edited handlers.go; stat err: %v", err)
	}
}

// TestEnsureRootCmdExportRewritesMultiArgFlagsCallsites locks the
// regex behavior that distinguishes "&flags" (whole struct address —
// must become "flags" after refactor) from "&flags.someField" (field
// address — must stay). The earlier (&flags)→(flags) ReplaceAll
// missed callsites where &flags appeared in the middle of an arg
// list, breaking compilation on real library CLIs (hackernews has
// `autoRefreshIfStale(cmd.Context(), &flags, resources)`).
func TestEnsureRootCmdExportRewritesMultiArgFlagsCallsites(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(cliDir, "internal", "cli"), 0o755))
	rootPath := filepath.Join(cliDir, "internal", "cli", "root.go")
	require.NoError(t, os.WriteFile(rootPath, []byte(`// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

import "github.com/spf13/cobra"

type rootFlags struct{ asJSON bool }

func Execute() error {
	var flags rootFlags

	rootCmd := &cobra.Command{
		Use: "synctest-pp-cli",
	}
	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "")

	// Multi-arg call passing &flags — must become flags.
	autoRefreshIfStale(rootCmd.Context(), &flags, []string{"x"})
	// First-of-many call — must also become flags.
	doSomething(&flags, "x", "y")
	// Last-of-many call — must become flags.
	finalize("a", &flags)
	// Field-access — must NOT become flags.asJSON (would be a different bug).
	useFlag(&flags.asJSON)

	err := rootCmd.Execute()
	return err
}

func ExitCode(err error) int { return 0 }
`), 0o644))

	require.NoError(t, ensureRootCmdExport(cliDir))

	updated, err := os.ReadFile(rootPath)
	require.NoError(t, err)
	src := string(updated)

	// All three bare-&flags callsite shapes should rewrite cleanly.
	assert.Contains(t, src, "autoRefreshIfStale(rootCmd.Context(), flags, []string{")
	assert.Contains(t, src, "doSomething(flags, \"x\", \"y\")")
	assert.Contains(t, src, "finalize(\"a\", flags)")

	// Field-access must remain untouched — &flags.asJSON is still valid
	// when flags is *rootFlags (Go auto-dereferences for field access).
	assert.Contains(t, src, "BoolVar(&flags.asJSON,")
	assert.Contains(t, src, "useFlag(&flags.asJSON)")

	// And the prologue should still produce the canonical RootCmd export.
	assert.Contains(t, src, "func RootCmd() *cobra.Command")
	assert.Contains(t, src, "return newRootCmd(&flags)")
}

// TestEnsureRootCmdExportConditionalBlocks asserts the prolog includes
// suggestFlag and Deliver blocks only when their supporting definitions
// exist in the source. Without conditional inclusion, older library
// CLIs that predate both features fail to build with "undefined" errors.
func TestEnsureRootCmdExportConditionalBlocks(t *testing.T) {
	t.Parallel()

	const oldTemplate = `// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

import "github.com/spf13/cobra"

type rootFlags struct{ asJSON bool }

func Execute() error {
	var flags rootFlags

	rootCmd := &cobra.Command{
		Use: "oldtemplate-pp-cli",
	}
	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "")
	err := rootCmd.Execute()
	return err
}

func ExitCode(err error) int { return 0 }
`

	const modernTemplate = `// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

import (
	"bytes"
	"github.com/spf13/cobra"
)

type rootFlags struct {
	asJSON      bool
	compact     bool
	deliverBuf  *bytes.Buffer
	deliverSink DeliverSink
}

type DeliverSink struct{ Scheme, Target string }

func Deliver(s DeliverSink, b []byte, c bool) error { return nil }

func suggestFlag(name string, cmd *cobra.Command) string { return "" }

func Execute() error {
	var flags rootFlags

	rootCmd := &cobra.Command{
		Use: "modern-pp-cli",
	}
	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "")
	err := rootCmd.Execute()
	return err
}

func ExitCode(err error) int { return 0 }
`

	cases := []struct {
		name        string
		fixture     string
		wantSuggest bool
		wantDeliver bool
	}{
		{"old template lacks both features", oldTemplate, false, false},
		{"modern template has both features", modernTemplate, true, true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			cliDir := t.TempDir()
			require.NoError(t, os.MkdirAll(filepath.Join(cliDir, "internal", "cli"), 0o755))
			rootPath := filepath.Join(cliDir, "internal", "cli", "root.go")
			require.NoError(t, os.WriteFile(rootPath, []byte(tc.fixture), 0o644))

			require.NoError(t, ensureRootCmdExport(cliDir))

			updated, err := os.ReadFile(rootPath)
			require.NoError(t, err)
			src := string(updated)

			// Canonical RootCmd export always emitted.
			assert.Contains(t, src, "func RootCmd() *cobra.Command")
			assert.Contains(t, src, "return newRootCmd(&flags)")

			if tc.wantSuggest {
				assert.Contains(t, src, "suggestFlag(")
			} else {
				assert.NotContains(t, src, "suggestFlag(")
			}
			if tc.wantDeliver {
				assert.Contains(t, src, "Deliver(flags.deliverSink")
			} else {
				assert.NotContains(t, src, "Deliver(flags.deliverSink")
				assert.NotContains(t, src, "flags.deliverBuf")
			}
		})
	}
}

// TestEnsureRootCmdExportDetectsFeaturesAcrossPackage asserts that
// suggestFlag and Deliver are detected even when their definitions
// live in sibling files (helpers.go, deliver.go) rather than root.go.
func TestEnsureRootCmdExportDetectsFeaturesAcrossPackage(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	pkgDir := filepath.Join(cliDir, "internal", "cli")
	require.NoError(t, os.MkdirAll(pkgDir, 0o755))

	// root.go has the deliverBuf field (so the deliver block applies)
	// but neither Deliver nor suggestFlag are defined here.
	require.NoError(t, os.WriteFile(filepath.Join(pkgDir, "root.go"), []byte(`// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

import (
	"bytes"
	"github.com/spf13/cobra"
)

type rootFlags struct {
	asJSON      bool
	compact     bool
	deliverBuf  *bytes.Buffer
	deliverSink DeliverSink
}

func Execute() error {
	var flags rootFlags

	rootCmd := &cobra.Command{
		Use: "splittest-pp-cli",
	}
	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "")
	err := rootCmd.Execute()
	return err
}

func ExitCode(err error) int { return 0 }
`), 0o644))

	// deliver.go provides the Deliver function (real generator layout).
	require.NoError(t, os.WriteFile(filepath.Join(pkgDir, "deliver.go"), []byte(`package cli

type DeliverSink struct{ Scheme, Target string }

func Deliver(s DeliverSink, b []byte, c bool) error { return nil }
`), 0o644))

	// helpers.go provides suggestFlag (real generator layout).
	require.NoError(t, os.WriteFile(filepath.Join(pkgDir, "helpers.go"), []byte(`package cli

import "github.com/spf13/cobra"

func suggestFlag(name string, cmd *cobra.Command) string { return "" }
`), 0o644))

	require.NoError(t, ensureRootCmdExport(cliDir))

	updated, err := os.ReadFile(filepath.Join(pkgDir, "root.go"))
	require.NoError(t, err)
	src := string(updated)

	assert.Contains(t, src, "suggestFlag(", "suggestFlag detected in helpers.go must enable the suggestFlag block")
	assert.Contains(t, src, "Deliver(flags.deliverSink", "Deliver detected in deliver.go must enable the deliver block")
}

// TestEnsureRootCmdExportIsIdempotent locks the no-op behavior on a root.go
// that already has RootCmd. Future template changes that add or remove
// surrounding code must not reintroduce the export and double-define it.
func TestEnsureRootCmdExportIsIdempotent(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(cliDir, "internal", "cli"), 0o755))
	rootPath := filepath.Join(cliDir, "internal", "cli", "root.go")
	original := []byte(`// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

import "github.com/spf13/cobra"

type rootFlags struct{}

func RootCmd() *cobra.Command {
	var flags rootFlags
	return newRootCmd(&flags)
}

func Execute() error { return nil }

func newRootCmd(flags *rootFlags) *cobra.Command { return &cobra.Command{} }
`)
	require.NoError(t, os.WriteFile(rootPath, original, 0o644))

	require.NoError(t, ensureRootCmdExport(cliDir))

	updated, err := os.ReadFile(rootPath)
	require.NoError(t, err)
	assert.Equal(t, string(original), string(updated), "ensureRootCmdExport should not modify root.go that already exports RootCmd")
}

// TestEnsureRootCmdExportRefusesHandEdits guards the hand-edit safety net.
// If the generator's don't-edit marker is missing the migration must refuse
// rather than silently overwriting whatever shape the file has now.
func TestEnsureRootCmdExportRefusesHandEdits(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(cliDir, "internal", "cli"), 0o755))
	rootPath := filepath.Join(cliDir, "internal", "cli", "root.go")
	require.NoError(t, os.WriteFile(rootPath, []byte(`// Hand-edited by maintainer; marker stripped on purpose.
package cli

import "github.com/spf13/cobra"

type rootFlags struct{}

func Execute() error {
	var flags rootFlags
	rootCmd := &cobra.Command{Use: "synctest"}
	_ = flags
	return rootCmd.Execute()
}
`), 0o644))

	err := ensureRootCmdExport(cliDir)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "appears hand-edited")
}

// TestEnsureRootCmdExportFailsClosedOnUnknownShape locks the failure path
// when ensureRootCmdExport encounters a generator-marked file whose Execute
// shape no longer matches the regex. The right behavior is "error out so the
// human investigates," not "patch what you find anyway." This test pins that
// contract and will fail if anyone weakens it.
func TestEnsureRootCmdExportFailsClosedOnUnknownShape(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(cliDir, "internal", "cli"), 0o755))
	rootPath := filepath.Join(cliDir, "internal", "cli", "root.go")
	require.NoError(t, os.WriteFile(rootPath, []byte(`// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

// This shape doesn't match the prologue ensureRootCmdExport expects.
func Execute() error {
	cfg := loadConfig()
	root := buildRoot(cfg)
	return root.Execute()
}
`), 0o644))

	err := ensureRootCmdExport(cliDir)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "does not match the generated Execute shape")
}

func TestReadRegistryDisplayName(t *testing.T) {
	writeRegistry := func(t *testing.T, libDir string, entries any) {
		t.Helper()
		body := map[string]any{"schema_version": 1, "entries": entries}
		data, err := json.Marshal(body)
		require.NoError(t, err)
		require.NoError(t, os.WriteFile(filepath.Join(libDir, "registry.json"), data, 0o644))
	}

	t.Run("env unset returns empty", func(t *testing.T) {
		t.Setenv("PRINTING_PRESS_LIBRARY_PUBLIC", "")
		assert.Equal(t, "", readRegistryDisplayName("cal-com"))
	})

	t.Run("env set but file missing returns empty", func(t *testing.T) {
		t.Setenv("PRINTING_PRESS_LIBRARY_PUBLIC", t.TempDir())
		assert.Equal(t, "", readRegistryDisplayName("cal-com"))
	})

	t.Run("malformed JSON returns empty", func(t *testing.T) {
		libDir := t.TempDir()
		require.NoError(t, os.WriteFile(filepath.Join(libDir, "registry.json"), []byte("not json"), 0o644))
		t.Setenv("PRINTING_PRESS_LIBRARY_PUBLIC", libDir)
		assert.Equal(t, "", readRegistryDisplayName("cal-com"))
	})

	t.Run("slug not in registry returns empty", func(t *testing.T) {
		libDir := t.TempDir()
		writeRegistry(t, libDir, []map[string]string{
			{"name": "wikipedia", "api": "Wikipedia"},
		})
		t.Setenv("PRINTING_PRESS_LIBRARY_PUBLIC", libDir)
		assert.Equal(t, "", readRegistryDisplayName("cal-com"))
	})

	t.Run("api equal to slug returns empty", func(t *testing.T) {
		libDir := t.TempDir()
		writeRegistry(t, libDir, []map[string]string{
			{"name": "agent-capture", "api": "agent-capture"},
		})
		t.Setenv("PRINTING_PRESS_LIBRARY_PUBLIC", libDir)
		assert.Equal(t, "", readRegistryDisplayName("agent-capture"))
	})

	t.Run("api too long returns empty", func(t *testing.T) {
		libDir := t.TempDir()
		writeRegistry(t, libDir, []map[string]string{
			{"name": "recipe-goat", "api": "Cross-site recipe aggregator (37 trusted sites: King Arthur, Serious Eats, Smitten Kitchen, AllRecipes, Food52, BBC Food, EatingWell, Food Network, and 29 more) + USDA FoodData Central"},
		})
		t.Setenv("PRINTING_PRESS_LIBRARY_PUBLIC", libDir)
		assert.Equal(t, "", readRegistryDisplayName("recipe-goat"))
	})

	t.Run("usable api returns it", func(t *testing.T) {
		libDir := t.TempDir()
		writeRegistry(t, libDir, []map[string]string{
			{"name": "wikipedia", "api": "Wikipedia"},
			{"name": "cal-com", "api": "Cal.com"},
			{"name": "company-goat", "api": "Company GOAT"},
		})
		t.Setenv("PRINTING_PRESS_LIBRARY_PUBLIC", libDir)
		assert.Equal(t, "Cal.com", readRegistryDisplayName("cal-com"))
		assert.Equal(t, "Wikipedia", readRegistryDisplayName("wikipedia"))
		assert.Equal(t, "Company GOAT", readRegistryDisplayName("company-goat"))
	})

	t.Run("whitespace-only api returns empty", func(t *testing.T) {
		libDir := t.TempDir()
		writeRegistry(t, libDir, []map[string]string{
			{"name": "wikipedia", "api": "  \t\n"},
		})
		t.Setenv("PRINTING_PRESS_LIBRARY_PUBLIC", libDir)
		assert.Equal(t, "", readRegistryDisplayName("wikipedia"))
	})

	t.Run("api whitespace is trimmed", func(t *testing.T) {
		libDir := t.TempDir()
		writeRegistry(t, libDir, []map[string]string{
			{"name": "wikipedia", "api": "  Wikipedia  "},
		})
		t.Setenv("PRINTING_PRESS_LIBRARY_PUBLIC", libDir)
		assert.Equal(t, "Wikipedia", readRegistryDisplayName("wikipedia"))
	})

	t.Run("unknown schema_version returns empty", func(t *testing.T) {
		libDir := t.TempDir()
		body := map[string]any{
			"schema_version": 2, // future schema, this binary doesn't understand
			"entries": []map[string]string{
				{"name": "cal-com", "api": "Cal.com"},
			},
		}
		data, err := json.Marshal(body)
		require.NoError(t, err)
		require.NoError(t, os.WriteFile(filepath.Join(libDir, "registry.json"), data, 0o644))
		t.Setenv("PRINTING_PRESS_LIBRARY_PUBLIC", libDir)
		assert.Equal(t, "", readRegistryDisplayName("cal-com"))
	})

	t.Run("missing schema_version returns empty", func(t *testing.T) {
		libDir := t.TempDir()
		body := map[string]any{
			// schema_version omitted; defaults to 0, which doesn't match.
			"entries": []map[string]string{
				{"name": "cal-com", "api": "Cal.com"},
			},
		}
		data, err := json.Marshal(body)
		require.NoError(t, err)
		require.NoError(t, os.WriteFile(filepath.Join(libDir, "registry.json"), data, 0o644))
		t.Setenv("PRINTING_PRESS_LIBRARY_PUBLIC", libDir)
		assert.Equal(t, "", readRegistryDisplayName("cal-com"))
	})
}

// TestSyncFallsThroughToRegistryDisplayName exercises the new branch
// in Sync's preservation block end-to-end: spec.yaml without
// display_name, manifest.json with no usable value, registry.json
// with a brand name. Asserts the registry value lands in
// .printing-press.json so subsequent WriteMCPBManifest carries it
// into the published manifest.
func TestSyncFallsThroughToRegistryDisplayName(t *testing.T) {
	apiSpec := &spec.APISpec{
		Name:    "testbrand",
		Version: "0.1.0",
		BaseURL: "https://api.example.com",
		Auth: spec.AuthConfig{
			Type:    "api_key",
			Header:  "Authorization",
			Format:  "Bearer {token}",
			EnvVars: []string{"TESTBRAND_TOKEN"},
		},
		Config: spec.ConfigSpec{
			Format: "toml",
			Path:   "~/.config/testbrand-pp-cli/config.toml",
		},
		Resources: map[string]spec.Resource{
			"items": {
				Description: "Manage items",
				Endpoints: map[string]spec.Endpoint{
					"list": {Method: "GET", Path: "/items", Description: "List items"},
				},
			},
		},
	}
	cliDir := filepath.Join(t.TempDir(), "testbrand")
	gen := generator.New(apiSpec, cliDir)
	require.NoError(t, gen.Generate())
	require.NoError(t, pipeline.WriteManifestForGenerate(pipeline.GenerateManifestParams{
		APIName:   apiSpec.Name,
		OutputDir: cliDir,
		Spec:      apiSpec,
	}))
	specData, err := yaml.Marshal(apiSpec)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(cliDir, "spec.yaml"), specData, 0o644))

	// Force manifest.json's display_name to empty so the manifest-side
	// preservation step rejects it and falls through to the registry.
	// Without this, the generator's HumanName-derived "Testbrand" would
	// be preserved and the registry path never gets exercised.
	manifestPath := filepath.Join(cliDir, pipeline.MCPBManifestFilename)
	mcpbData, err := os.ReadFile(manifestPath)
	require.NoError(t, err)
	var mcpb pipeline.MCPBManifest
	require.NoError(t, json.Unmarshal(mcpbData, &mcpb))
	mcpb.DisplayName = ""
	modifiedData, err := json.Marshal(mcpb)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(manifestPath, modifiedData, 0o644))

	// Set up the public library with a registry.json the fallback can read.
	libDir := t.TempDir()
	registry := map[string]any{
		"schema_version": 1,
		"entries": []map[string]string{
			{"name": "testbrand", "api": "TestBrand!"},
		},
	}
	registryData, err := json.Marshal(registry)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(libDir, "registry.json"), registryData, 0o644))
	t.Setenv("PRINTING_PRESS_LIBRARY_PUBLIC", libDir)

	_, err = Sync(cliDir, Options{})
	require.NoError(t, err)

	// .printing-press.json must reflect the registry-derived value;
	// the broken alternative is silently regressing to "Testbrand".
	provData, err := os.ReadFile(filepath.Join(cliDir, pipeline.CLIManifestFilename))
	require.NoError(t, err)
	var prov pipeline.CLIManifest
	require.NoError(t, json.Unmarshal(provData, &prov))
	assert.Equal(t, "TestBrand!", prov.DisplayName)
}
