package mcpsync

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/mvanhorn/cli-printing-press/v2/internal/generator"
	"github.com/mvanhorn/cli-printing-press/v2/internal/spec"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestSyncBackfillsEndpointAnnotations(t *testing.T) {
	t.Parallel()

	apiSpec := &spec.APISpec{
		Name:    "synctest",
		Version: "0.1.0",
		BaseURL: "https://api.example.com",
		Auth: spec.AuthConfig{
			Type:    "api_key",
			Header:  "Authorization",
			Format:  "Bearer {token}",
			EnvVars: []string{"SYNCTEST_TOKEN"},
		},
		Config: spec.ConfigSpec{
			Format: "toml",
			Path:   "~/.config/synctest-pp-cli/config.toml",
		},
		Resources: map[string]spec.Resource{
			"projects": {
				Description: "Manage projects",
				Endpoints: map[string]spec.Endpoint{
					"list": {Method: "GET", Path: "/projects", Description: "List projects"},
					"get":  {Method: "GET", Path: "/projects/{id}", Description: "Get a project"},
				},
			},
		},
	}

	cliDir := filepath.Join(t.TempDir(), "synctest")
	gen := generator.New(apiSpec, cliDir)
	require.NoError(t, gen.Generate())

	specData, err := yaml.Marshal(apiSpec)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(filepath.Join(cliDir, "spec.yaml"), specData, 0o644))

	endpointPath := filepath.Join(cliDir, "internal", "cli", "projects_list.go")
	endpointData, err := os.ReadFile(endpointPath)
	require.NoError(t, err)
	withoutAnnotation := endpointAnnotationLine.ReplaceAllString(string(endpointData), "")
	require.NotContains(t, withoutAnnotation, `"pp:endpoint"`)
	require.NoError(t, os.WriteFile(endpointPath, []byte(withoutAnnotation), 0o644))

	oldTools := `// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package mcp

func RegisterNovelFeatureTools() { shellOutToCLI("projects list") }
`
	require.NoError(t, os.WriteFile(filepath.Join(cliDir, "internal", "mcp", "tools.go"), []byte(oldTools), 0o644))

	result, err := Sync(cliDir, Options{})
	require.NoError(t, err)
	assert.True(t, result.Changed)

	updatedEndpoint, err := os.ReadFile(endpointPath)
	require.NoError(t, err)
	assert.Contains(t, string(updatedEndpoint), `Annotations: map[string]string{"pp:endpoint": "projects.list"}`)

	updatedTools, err := os.ReadFile(filepath.Join(cliDir, "internal", "mcp", "tools.go"))
	require.NoError(t, err)
	assert.Contains(t, string(updatedTools), "cobratree.RegisterAll")
}

func TestEnsureRootCmdExportPreservesRootFlagPointer(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(cliDir, "internal", "cli"), 0o755))
	rootPath := filepath.Join(cliDir, "internal", "cli", "root.go")
	require.NoError(t, os.WriteFile(rootPath, []byte(`// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

import "github.com/spf13/cobra"

type rootFlags struct{}

// Execute runs the CLI in non-interactive mode: never prompts, all values via flags or stdin.
func Execute() error {
	var flags rootFlags

	rootCmd := &cobra.Command{
		Use: "synctest-pp-cli",
	}
	rootCmd.AddCommand(newDoctorCmd(&flags))

	err := rootCmd.Execute()
	return err
}

func newDoctorCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{Use: "doctor"}
}

func ExitCode(err error) int { return 0 }
`), 0o644))

	require.NoError(t, ensureRootCmdExport(cliDir))

	updated, err := os.ReadFile(rootPath)
	require.NoError(t, err)
	src := string(updated)
	assert.Contains(t, src, "return newRootCmd(&flags)")
	assert.Contains(t, src, "rootCmd := newRootCmd(&flags)")
	assert.Contains(t, src, "rootCmd.AddCommand(newDoctorCmd(flags))")
	assert.NotContains(t, src, "newRootCmd(flags)")
}

// TestRemoveStaleMCPHandlersFile locks behavior for the food52 case:
// older generator templates emitted MCP handlers in a separate
// internal/mcp/handlers.go; the current template emits everything in
// tools.go. mcp-sync needs to delete the stale handlers.go before
// regenerating to avoid "handleContext redeclared in this block"
// build errors.
func TestRemoveStaleMCPHandlersFile(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	mcpDir := filepath.Join(cliDir, "internal", "mcp")
	require.NoError(t, os.MkdirAll(mcpDir, 0o755))
	handlersPath := filepath.Join(mcpDir, "handlers.go")
	require.NoError(t, os.WriteFile(handlersPath, []byte(`// Copyright 2026 trevin-chow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package mcp
func handleContext() {}
`), 0o644))

	require.NoError(t, removeStaleMCPHandlersFile(cliDir, false))

	if _, err := os.Stat(handlersPath); !os.IsNotExist(err) {
		t.Errorf("expected handlers.go to be removed; stat err: %v", err)
	}
}

func TestRemoveStaleMCPHandlersFileNoOpWhenAbsent(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(cliDir, "internal", "mcp"), 0o755))

	if err := removeStaleMCPHandlersFile(cliDir, false); err != nil {
		t.Errorf("expected no error when handlers.go is absent, got: %v", err)
	}
}

func TestRemoveStaleMCPHandlersFileRefusesHandEdits(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	mcpDir := filepath.Join(cliDir, "internal", "mcp")
	require.NoError(t, os.MkdirAll(mcpDir, 0o755))
	handlersPath := filepath.Join(mcpDir, "handlers.go")
	// Hand-edited: marker absent. Removing this would destroy custom logic.
	require.NoError(t, os.WriteFile(handlersPath, []byte(`package mcp
// Hand-written by maintainer. Marker stripped on purpose.
func handleContext() {}
`), 0o644))

	err := removeStaleMCPHandlersFile(cliDir, false)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "appears hand-edited")
	if _, err := os.Stat(handlersPath); err != nil {
		t.Errorf("handlers.go should still exist after refusal; stat err: %v", err)
	}
}

func TestRemoveStaleMCPHandlersFileForceOverride(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	mcpDir := filepath.Join(cliDir, "internal", "mcp")
	require.NoError(t, os.MkdirAll(mcpDir, 0o755))
	handlersPath := filepath.Join(mcpDir, "handlers.go")
	require.NoError(t, os.WriteFile(handlersPath, []byte(`package mcp
// Hand-written. --force will delete this anyway.
func handleContext() {}
`), 0o644))

	require.NoError(t, removeStaleMCPHandlersFile(cliDir, true))

	if _, err := os.Stat(handlersPath); !os.IsNotExist(err) {
		t.Errorf("expected --force to remove hand-edited handlers.go; stat err: %v", err)
	}
}

// TestEnsureRootCmdExportRewritesMultiArgFlagsCallsites locks the
// regex behavior that distinguishes "&flags" (whole struct address —
// must become "flags" after refactor) from "&flags.someField" (field
// address — must stay). The earlier (&flags)→(flags) ReplaceAll
// missed callsites where &flags appeared in the middle of an arg
// list, breaking compilation on real library CLIs (hackernews has
// `autoRefreshIfStale(cmd.Context(), &flags, resources)`).
func TestEnsureRootCmdExportRewritesMultiArgFlagsCallsites(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(cliDir, "internal", "cli"), 0o755))
	rootPath := filepath.Join(cliDir, "internal", "cli", "root.go")
	require.NoError(t, os.WriteFile(rootPath, []byte(`// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

import "github.com/spf13/cobra"

type rootFlags struct{ asJSON bool }

func Execute() error {
	var flags rootFlags

	rootCmd := &cobra.Command{
		Use: "synctest-pp-cli",
	}
	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "")

	// Multi-arg call passing &flags — must become flags.
	autoRefreshIfStale(rootCmd.Context(), &flags, []string{"x"})
	// First-of-many call — must also become flags.
	doSomething(&flags, "x", "y")
	// Last-of-many call — must become flags.
	finalize("a", &flags)
	// Field-access — must NOT become flags.asJSON (would be a different bug).
	useFlag(&flags.asJSON)

	err := rootCmd.Execute()
	return err
}

func ExitCode(err error) int { return 0 }
`), 0o644))

	require.NoError(t, ensureRootCmdExport(cliDir))

	updated, err := os.ReadFile(rootPath)
	require.NoError(t, err)
	src := string(updated)

	// All three bare-&flags callsite shapes should rewrite cleanly.
	assert.Contains(t, src, "autoRefreshIfStale(rootCmd.Context(), flags, []string{")
	assert.Contains(t, src, "doSomething(flags, \"x\", \"y\")")
	assert.Contains(t, src, "finalize(\"a\", flags)")

	// Field-access must remain untouched — &flags.asJSON is still valid
	// when flags is *rootFlags (Go auto-dereferences for field access).
	assert.Contains(t, src, "BoolVar(&flags.asJSON,")
	assert.Contains(t, src, "useFlag(&flags.asJSON)")

	// And the prologue should still produce the canonical RootCmd export.
	assert.Contains(t, src, "func RootCmd() *cobra.Command")
	assert.Contains(t, src, "return newRootCmd(&flags)")
}

// TestEnsureRootCmdExportIsIdempotent locks the no-op behavior on a root.go
// that already has RootCmd. Future template changes that add or remove
// surrounding code must not reintroduce the export and double-define it.
func TestEnsureRootCmdExportIsIdempotent(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(cliDir, "internal", "cli"), 0o755))
	rootPath := filepath.Join(cliDir, "internal", "cli", "root.go")
	original := []byte(`// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

import "github.com/spf13/cobra"

type rootFlags struct{}

func RootCmd() *cobra.Command {
	var flags rootFlags
	return newRootCmd(&flags)
}

func Execute() error { return nil }

func newRootCmd(flags *rootFlags) *cobra.Command { return &cobra.Command{} }
`)
	require.NoError(t, os.WriteFile(rootPath, original, 0o644))

	require.NoError(t, ensureRootCmdExport(cliDir))

	updated, err := os.ReadFile(rootPath)
	require.NoError(t, err)
	assert.Equal(t, string(original), string(updated), "ensureRootCmdExport should not modify root.go that already exports RootCmd")
}

// TestEnsureRootCmdExportRefusesHandEdits guards the hand-edit safety net.
// If the generator's don't-edit marker is missing the migration must refuse
// rather than silently overwriting whatever shape the file has now.
func TestEnsureRootCmdExportRefusesHandEdits(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(cliDir, "internal", "cli"), 0o755))
	rootPath := filepath.Join(cliDir, "internal", "cli", "root.go")
	require.NoError(t, os.WriteFile(rootPath, []byte(`// Hand-edited by maintainer; marker stripped on purpose.
package cli

import "github.com/spf13/cobra"

type rootFlags struct{}

func Execute() error {
	var flags rootFlags
	rootCmd := &cobra.Command{Use: "synctest"}
	_ = flags
	return rootCmd.Execute()
}
`), 0o644))

	err := ensureRootCmdExport(cliDir)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "appears hand-edited")
}

// TestEnsureRootCmdExportFailsClosedOnUnknownShape locks the failure path
// when ensureRootCmdExport encounters a generator-marked file whose Execute
// shape no longer matches the regex. The right behavior is "error out so the
// human investigates," not "patch what you find anyway." This test pins that
// contract and will fail if anyone weakens it.
func TestEnsureRootCmdExportFailsClosedOnUnknownShape(t *testing.T) {
	t.Parallel()

	cliDir := t.TempDir()
	require.NoError(t, os.MkdirAll(filepath.Join(cliDir, "internal", "cli"), 0o755))
	rootPath := filepath.Join(cliDir, "internal", "cli", "root.go")
	require.NoError(t, os.WriteFile(rootPath, []byte(`// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

// This shape doesn't match the prologue ensureRootCmdExport expects.
func Execute() error {
	cfg := loadConfig()
	root := buildRoot(cfg)
	return root.Execute()
}
`), 0o644))

	err := ensureRootCmdExport(cliDir)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "does not match the generated Execute shape")
}
