// Copyright 2026 printing-press-golden. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types


type CreateProjectRequest struct {
	Name string `json:"name"`
	OwnerEmail string `json:"owner_email"`
	Visibility string `json:"visibility"`
}

type Currency struct {
	Code string `json:"code"`
	Decimals int `json:"decimals"`
	Symbol string `json:"symbol"`
}

type Project struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Status string `json:"status"`
	Visibility string `json:"visibility"`
}

type Task struct {
	DueAt string `json:"due_at"`
	Id string `json:"id"`
	Priority string `json:"priority"`
	ProjectId string `json:"project_id"`
	Title string `json:"title"`
}

type UpdateTaskRequest struct {
	Completed bool `json:"completed"`
	Priority string `json:"priority"`
	Title string `json:"title"`
}
