// Copyright 2026 trevin-chow. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCategoryCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "category",
		Short: "Manage category",
	}

	cmd.AddCommand(newCategoryGetCmd(flags))
	cmd.AddCommand(newCategoryListCategoriesCmd(flags))
	cmd.AddCommand(newCategoryLandscapeCmd(flags))
	return cmd
}

func newCategoryGetCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{Use: "get"}
}

func newCategoryListCategoriesCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{Use: "list-categories"}
}
