// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newBankTransferCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "bank-transfer",
		Short: "Manage bank transfer",
	}

	cmd.AddCommand(newBankTransferBalanceGetCmd(flags))
	cmd.AddCommand(newBankTransferCancelCmd(flags))
	cmd.AddCommand(newBankTransferCreateCmd(flags))
	cmd.AddCommand(newBankTransferEventListCmd(flags))
	cmd.AddCommand(newBankTransferEventSyncCmd(flags))
	cmd.AddCommand(newBankTransferGetCmd(flags))
	cmd.AddCommand(newBankTransferListCmd(flags))
	cmd.AddCommand(newBankTransferMigrateAccountCmd(flags))
	cmd.AddCommand(newBankTransferSweepGetCmd(flags))
	cmd.AddCommand(newBankTransferSweepListCmd(flags))
	return cmd
}

func newBankTransferBalanceGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyOriginationAccountId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "balance-get",
		Short: "Get balance of your Bank Transfer account",
		Example: "  plaid-cli bank-transfer balance-get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/bank_transfer/balance/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyOriginationAccountId != "" {
				body["origination_account_id"] = bodyOriginationAccountId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyOriginationAccountId, "origination-account-id", "", "If multiple origination accounts are available, `origination_account_id` must be used to specify the account for...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newBankTransferCancelCmd(flags *rootFlags) *cobra.Command {
	var bodyBankTransferId string
	var bodyClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "cancel",
		Short: "Cancel a bank transfer",
		Example: "  plaid-cli bank-transfer cancel --bank-transfer-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/bank_transfer/cancel"
			body := map[string]any{}
			if bodyBankTransferId != "" {
				body["bank_transfer_id"] = bodyBankTransferId
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyBankTransferId, "bank-transfer-id", "", "Plaid’s unique identifier for a bank transfer.")
	_ = cmd.MarkFlagRequired("bank-transfer-id")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newBankTransferCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyAccountId string
	var bodyAchClass string
	var bodyAmount string
	var bodyClientId string
	var bodyCustomTag string
	var bodyDescription string
	var bodyIdempotencyKey string
	var bodyIsoCurrencyCode string
	var bodyNetwork string
	var bodyOriginationAccountId string
	var bodySecret string
	var bodyType string

	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a bank transfer",
		Example: "  plaid-cli bank-transfer create --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/bank_transfer/create"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyAccountId != "" {
				body["account_id"] = bodyAccountId
			}
			if bodyAchClass != "" {
				body["ach_class"] = bodyAchClass
			}
			if bodyAmount != "" {
				body["amount"] = bodyAmount
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCustomTag != "" {
				body["custom_tag"] = bodyCustomTag
			}
			if bodyDescription != "" {
				body["description"] = bodyDescription
			}
			if bodyIdempotencyKey != "" {
				body["idempotency_key"] = bodyIdempotencyKey
			}
			if bodyIsoCurrencyCode != "" {
				body["iso_currency_code"] = bodyIsoCurrencyCode
			}
			if bodyNetwork != "" {
				body["network"] = bodyNetwork
			}
			if bodyOriginationAccountId != "" {
				body["origination_account_id"] = bodyOriginationAccountId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyType != "" {
				body["type"] = bodyType
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The Plaid `access_token` for the account that will be debited or credited.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyAccountId, "account-id", "", "The Plaid `account_id` for the account that will be debited or credited.")
	_ = cmd.MarkFlagRequired("account-id")
	cmd.Flags().StringVar(&bodyAchClass, "ach-class", "", "Specifies the use case of the transfer. Required for transfers on an ACH network. For more details, see [ACH SEC...")
	cmd.Flags().StringVar(&bodyAmount, "amount", "", "The amount of the bank transfer (decimal string with two digits of precision e.g. '10.00').")
	_ = cmd.MarkFlagRequired("amount")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyCustomTag, "custom-tag", "", "An arbitrary string provided by the client for storage with the bank transfer. May be up to 100 characters.")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "The transfer description. Maximum of 10 characters.")
	_ = cmd.MarkFlagRequired("description")
	cmd.Flags().StringVar(&bodyIdempotencyKey, "idempotency-key", "", "A random key provided by the client, per unique bank transfer. Maximum of 50 characters. The API supports...")
	_ = cmd.MarkFlagRequired("idempotency-key")
	cmd.Flags().StringVar(&bodyIsoCurrencyCode, "iso-currency-code", "", "The currency of the transfer amount – should be set to 'USD'.")
	_ = cmd.MarkFlagRequired("iso-currency-code")
	cmd.Flags().StringVar(&bodyNetwork, "network", "", "The network or rails used for the transfer. Valid options are `ach`, `same-day-ach`, or `wire`.")
	_ = cmd.MarkFlagRequired("network")
	cmd.Flags().StringVar(&bodyOriginationAccountId, "origination-account-id", "", "Plaid’s unique identifier for the origination account for this transfer. If you have more than one origination...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyType, "type", "", "The type of bank transfer. This will be either `debit` or `credit`. A `debit` indicates a transfer of money into the...")
	_ = cmd.MarkFlagRequired("type")

	return cmd
}

func newBankTransferEventListCmd(flags *rootFlags) *cobra.Command {
	var bodyAccountId string
	var bodyBankTransferId string
	var bodyBankTransferType string
	var bodyClientId string
	var bodyCount int
	var bodyDirection string
	var bodyEndDate string
	var bodyOffset int
	var bodyOriginationAccountId string
	var bodySecret string
	var bodyStartDate string

	cmd := &cobra.Command{
		Use:   "event-list",
		Short: "List bank transfer events",
		Example: "  plaid-cli bank-transfer event-list",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/bank_transfer/event/list"
			body := map[string]any{}
			if bodyAccountId != "" {
				body["account_id"] = bodyAccountId
			}
			if bodyBankTransferId != "" {
				body["bank_transfer_id"] = bodyBankTransferId
			}
			if bodyBankTransferType != "" {
				body["bank_transfer_type"] = bodyBankTransferType
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCount != 0 {
				body["count"] = bodyCount
			}
			if bodyDirection != "" {
				body["direction"] = bodyDirection
			}
			if bodyEndDate != "" {
				body["end_date"] = bodyEndDate
			}
			if bodyOffset != 0 {
				body["offset"] = bodyOffset
			}
			if bodyOriginationAccountId != "" {
				body["origination_account_id"] = bodyOriginationAccountId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStartDate != "" {
				body["start_date"] = bodyStartDate
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccountId, "account-id", "", "The account ID to get events for all transactions to/from an account.")
	cmd.Flags().StringVar(&bodyBankTransferId, "bank-transfer-id", "", "Plaid’s unique identifier for a bank transfer.")
	cmd.Flags().StringVar(&bodyBankTransferType, "bank-transfer-type", "", "The type of bank transfer. This will be either `debit` or `credit`. A `debit` indicates a transfer of money into...")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().IntVar(&bodyCount, "count", 25, "The maximum number of bank transfer events to return. If the number of events matching the above parameters is...")
	cmd.Flags().StringVar(&bodyDirection, "direction", "", "Indicates the direction of the transfer: `outbound`: for API-initiated transfers `inbound`: for payments received by...")
	cmd.Flags().StringVar(&bodyEndDate, "end-date", "", "The end datetime of bank transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)")
	cmd.Flags().IntVar(&bodyOffset, "offset", 0, "The offset into the list of bank transfer events. When `count`=25 and `offset`=0, the first 25 events will be...")
	cmd.Flags().StringVar(&bodyOriginationAccountId, "origination-account-id", "", "The origination account ID to get events for transfers from a specific origination account.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStartDate, "start-date", "", "The start datetime of bank transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)")

	return cmd
}

func newBankTransferEventSyncCmd(flags *rootFlags) *cobra.Command {
	var bodyAfterId int
	var bodyClientId string
	var bodyCount int
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "event-sync",
		Short: "Sync bank transfer events",
		Example: "  plaid-cli bank-transfer event-sync",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/bank_transfer/event/sync"
			body := map[string]any{}
			if bodyAfterId != 0 {
				body["after_id"] = bodyAfterId
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCount != 0 {
				body["count"] = bodyCount
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&bodyAfterId, "after-id", 0, "The latest (largest) `event_id` fetched via the sync endpoint, or 0 initially.")
	_ = cmd.MarkFlagRequired("after-id")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().IntVar(&bodyCount, "count", 25, "The maximum number of bank transfer events to return.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newBankTransferGetCmd(flags *rootFlags) *cobra.Command {
	var bodyBankTransferId string
	var bodyClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "get",
		Short: "Retrieve a bank transfer",
		Example: "  plaid-cli bank-transfer get --bank-transfer-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/bank_transfer/get"
			body := map[string]any{}
			if bodyBankTransferId != "" {
				body["bank_transfer_id"] = bodyBankTransferId
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyBankTransferId, "bank-transfer-id", "", "Plaid’s unique identifier for a bank transfer.")
	_ = cmd.MarkFlagRequired("bank-transfer-id")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newBankTransferListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCount int
	var bodyDirection string
	var bodyEndDate string
	var bodyOffset int
	var bodyOriginationAccountId string
	var bodySecret string
	var bodyStartDate string

	cmd := &cobra.Command{
		Use:   "list",
		Short: "List bank transfers",
		Example: "  plaid-cli bank-transfer list",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/bank_transfer/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCount != 0 {
				body["count"] = bodyCount
			}
			if bodyDirection != "" {
				body["direction"] = bodyDirection
			}
			if bodyEndDate != "" {
				body["end_date"] = bodyEndDate
			}
			if bodyOffset != 0 {
				body["offset"] = bodyOffset
			}
			if bodyOriginationAccountId != "" {
				body["origination_account_id"] = bodyOriginationAccountId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStartDate != "" {
				body["start_date"] = bodyStartDate
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().IntVar(&bodyCount, "count", 25, "The maximum number of bank transfers to return.")
	cmd.Flags().StringVar(&bodyDirection, "direction", "", "Indicates the direction of the transfer: `outbound` for API-initiated transfers, or `inbound` for payments received...")
	cmd.Flags().StringVar(&bodyEndDate, "end-date", "", "The end datetime of bank transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)")
	cmd.Flags().IntVar(&bodyOffset, "offset", 0, "The number of bank transfers to skip before returning results.")
	cmd.Flags().StringVar(&bodyOriginationAccountId, "origination-account-id", "", "Filter bank transfers to only those originated through the specified origination account.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStartDate, "start-date", "", "The start datetime of bank transfers to list. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)")

	return cmd
}

func newBankTransferMigrateAccountCmd(flags *rootFlags) *cobra.Command {
	var bodyAccountNumber string
	var bodyAccountType string
	var bodyClientId string
	var bodyRoutingNumber string
	var bodySecret string
	var bodyWireRoutingNumber string

	cmd := &cobra.Command{
		Use:   "migrate-account",
		Short: "Migrate account into Bank Transfers",
		Example: "  plaid-cli bank-transfer migrate-account --account-number value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/bank_transfer/migrate_account"
			body := map[string]any{}
			if bodyAccountNumber != "" {
				body["account_number"] = bodyAccountNumber
			}
			if bodyAccountType != "" {
				body["account_type"] = bodyAccountType
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyRoutingNumber != "" {
				body["routing_number"] = bodyRoutingNumber
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWireRoutingNumber != "" {
				body["wire_routing_number"] = bodyWireRoutingNumber
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccountNumber, "account-number", "", "The user's account number.")
	_ = cmd.MarkFlagRequired("account-number")
	cmd.Flags().StringVar(&bodyAccountType, "account-type", "", "The type of the bank account (`checking` or `savings`).")
	_ = cmd.MarkFlagRequired("account-type")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyRoutingNumber, "routing-number", "", "The user's routing number.")
	_ = cmd.MarkFlagRequired("routing-number")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWireRoutingNumber, "wire-routing-number", "", "The user's wire transfer routing number. This is the ABA number; for some institutions, this may differ from the ACH...")

	return cmd
}

func newBankTransferSweepGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string
	var bodySweepId string

	cmd := &cobra.Command{
		Use:   "sweep-get",
		Short: "Retrieve a sweep",
		Example: "  plaid-cli bank-transfer sweep-get --sweep-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/bank_transfer/sweep/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodySweepId != "" {
				body["sweep_id"] = bodySweepId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodySweepId, "sweep-id", "", "Identifier of the sweep.")
	_ = cmd.MarkFlagRequired("sweep-id")

	return cmd
}

func newBankTransferSweepListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCount int
	var bodyEndTime string
	var bodyOriginationAccountId string
	var bodySecret string
	var bodyStartTime string

	cmd := &cobra.Command{
		Use:   "sweep-list",
		Short: "List sweeps",
		Example: "  plaid-cli bank-transfer sweep-list",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/bank_transfer/sweep/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCount != 0 {
				body["count"] = bodyCount
			}
			if bodyEndTime != "" {
				body["end_time"] = bodyEndTime
			}
			if bodyOriginationAccountId != "" {
				body["origination_account_id"] = bodyOriginationAccountId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStartTime != "" {
				body["start_time"] = bodyStartTime
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().IntVar(&bodyCount, "count", 25, "The maximum number of sweeps to return.")
	cmd.Flags().StringVar(&bodyEndTime, "end-time", "", "The end `created` datetime of sweeps to return (RFC 3339 format).")
	cmd.Flags().StringVar(&bodyOriginationAccountId, "origination-account-id", "", "If multiple origination accounts are available, `origination_account_id` must be used to specify the account that...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStartTime, "start-time", "", "The start `created` datetime of sweeps to return (RFC 3339 format).")

	return cmd
}

