// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newBetaCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "beta",
		Short: "Manage beta",
	}

	cmd.AddCommand(newBetaCreditBankEmploymentGetCmd(flags))
	cmd.AddCommand(newBetaEwaReportV1GetCmd(flags))
	cmd.AddCommand(newBetaPartnerCustomerV1CreateCmd(flags))
	cmd.AddCommand(newBetaPartnerCustomerV1EnableCmd(flags))
	cmd.AddCommand(newBetaPartnerCustomerV1GetCmd(flags))
	cmd.AddCommand(newBetaPartnerCustomerV1UpdateCmd(flags))
	cmd.AddCommand(newBetaTransactionsEnhanceCmd(flags))
	cmd.AddCommand(newBetaTransactionsRulesCreateCmd(flags))
	cmd.AddCommand(newBetaTransactionsRulesListCmd(flags))
	cmd.AddCommand(newBetaTransactionsRulesRemoveCmd(flags))
	cmd.AddCommand(newBetaTransactionsUserInsightsGetCmd(flags))
	return cmd
}

func newBetaCreditBankEmploymentGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string
	var bodyUserToken string

	cmd := &cobra.Command{
		Use:   "credit-bank-employment-get",
		Aliases: []string{"create"},
		Short: "Retrieve information from the bank accounts used for employment verification",
		Example: "  plaid-cli beta credit-bank-employment-get --user-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/beta/credit/v1/bank_employment/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyUserToken != "" {
				body["user_token"] = bodyUserToken
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyUserToken, "user-token", "", "The user token associated with the User data is being requested for. This field is used only by customers with...")
	_ = cmd.MarkFlagRequired("user-token")

	return cmd
}

func newBetaEwaReportV1GetCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "ewa-report-v1-get",
		Short: "Get EWA Score Report",
		Example: "  plaid-cli beta ewa-report-v1-get --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/beta/ewa_report/v1/get"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newBetaPartnerCustomerV1CreateCmd(flags *rootFlags) *cobra.Command {
	var bodyApplicationName string
	var bodyClientId string
	var bodyCompanyName string
	var bodyCreateLinkCustomization bool
	var bodyIsDiligenceAttested bool
	var bodyLegalEntityName string
	var bodyLogo string
	var bodySecret string
	var bodyWebsite string

	cmd := &cobra.Command{
		Use:   "partner-customer-v1-create",
		Short: "Creates a new end customer for a Plaid reseller.",
		Example: "  plaid-cli beta partner-customer-v1-create --application-name value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/beta/partner/customer/v1/create"
			body := map[string]any{}
			if bodyApplicationName != "" {
				body["application_name"] = bodyApplicationName
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCompanyName != "" {
				body["company_name"] = bodyCompanyName
			}
			if bodyCreateLinkCustomization != false {
				body["create_link_customization"] = bodyCreateLinkCustomization
			}
			if bodyIsDiligenceAttested != false {
				body["is_diligence_attested"] = bodyIsDiligenceAttested
			}
			if bodyLegalEntityName != "" {
				body["legal_entity_name"] = bodyLegalEntityName
			}
			if bodyLogo != "" {
				body["logo"] = bodyLogo
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWebsite != "" {
				body["website"] = bodyWebsite
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyApplicationName, "application-name", "", "The name of the end customer's application. This will be shown to end users when they go through the Plaid Link...")
	_ = cmd.MarkFlagRequired("application-name")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyCompanyName, "company-name", "", "The company name of the end customer being created. This will be used to display the end customer in the Plaid...")
	_ = cmd.MarkFlagRequired("company-name")
	cmd.Flags().BoolVar(&bodyCreateLinkCustomization, "create-link-customization", false, "If `true`, the end customer's default Link customization will be set to match the partner's. You can always change...")
	cmd.Flags().BoolVar(&bodyIsDiligenceAttested, "is-diligence-attested", false, "Denotes whether or not the partner has completed attestation of diligence for the end customer to be created.")
	cmd.Flags().StringVar(&bodyLegalEntityName, "legal-entity-name", "", "The end customer's legal name. This will be shared with financial institutions as part of the OAuth registration...")
	cmd.Flags().StringVar(&bodyLogo, "logo", "", "Base64-encoded representation of the end customer's logo. Must be a PNG of size 1024x1024 under 4MB. The logo will...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWebsite, "website", "", "The end customer's website.")
	_ = cmd.MarkFlagRequired("website")

	return cmd
}

func newBetaPartnerCustomerV1EnableCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyEndCustomerClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "partner-customer-v1-enable",
		Short: "Enables a Plaid reseller's end customer in the Production environment.",
		Example: "  plaid-cli beta partner-customer-v1-enable --end-customer-client-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/beta/partner/customer/v1/enable"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEndCustomerClientId != "" {
				body["end_customer_client_id"] = bodyEndCustomerClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEndCustomerClientId, "end-customer-client-id", "", "End customer client id")
	_ = cmd.MarkFlagRequired("end-customer-client-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newBetaPartnerCustomerV1GetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyEndCustomerClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "partner-customer-v1-get",
		Short: "Retrieves the details of a Plaid reseller's end customer.",
		Example: "  plaid-cli beta partner-customer-v1-get --end-customer-client-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/beta/partner/customer/v1/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEndCustomerClientId != "" {
				body["end_customer_client_id"] = bodyEndCustomerClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEndCustomerClientId, "end-customer-client-id", "", "End customer client id")
	_ = cmd.MarkFlagRequired("end-customer-client-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newBetaPartnerCustomerV1UpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyEndCustomerClientId string
	var bodyLegalEntityName string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "partner-customer-v1-update",
		Short: "Updates an existing end customer.",
		Example: "  plaid-cli beta partner-customer-v1-update --end-customer-client-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/beta/partner/customer/v1/update"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEndCustomerClientId != "" {
				body["end_customer_client_id"] = bodyEndCustomerClientId
			}
			if bodyLegalEntityName != "" {
				body["legal_entity_name"] = bodyLegalEntityName
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEndCustomerClientId, "end-customer-client-id", "", "End customer client id")
	_ = cmd.MarkFlagRequired("end-customer-client-id")
	cmd.Flags().StringVar(&bodyLegalEntityName, "legal-entity-name", "", "Legal entity name")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newBetaTransactionsEnhanceCmd(flags *rootFlags) *cobra.Command {
	var bodyAccountType string
	var bodyClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "transactions-enhance",
		Short: "enhance locally-held transaction data",
		Example: "  plaid-cli beta transactions-enhance --account-type value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/beta/transactions/v1/enhance"
			body := map[string]any{}
			if bodyAccountType != "" {
				body["account_type"] = bodyAccountType
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccountType, "account-type", "", "The type of account for the requested transactions (`depository` or `credit`).")
	_ = cmd.MarkFlagRequired("account-type")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newBetaTransactionsRulesCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyClientUserId string
	var bodyPfcDetailedCategory string
	var bodyPfcPrimaryCategory string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "transactions-rules-create",
		Short: "Create transaction category rule",
		Example: "  plaid-cli beta transactions-rules-create --client-user-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/beta/transactions/rules/v1/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodyPfcDetailedCategory != "" {
				body["pfc_detailed_category"] = bodyPfcDetailedCategory
			}
			if bodyPfcPrimaryCategory != "" {
				body["pfc_primary_category"] = bodyPfcPrimaryCategory
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID representing the end user. This ID is used to associate rules with a specific user.")
	_ = cmd.MarkFlagRequired("client-user-id")
	cmd.Flags().StringVar(&bodyPfcDetailedCategory, "pfc-detailed-category", "", "A personal finance detailed category. See the [taxonomy csv file](https://plaid.com/documents/pfc-taxonomy-all.csv)...")
	_ = cmd.MarkFlagRequired("pfc-detailed-category")
	cmd.Flags().StringVar(&bodyPfcPrimaryCategory, "pfc-primary-category", "", "A personal finance primary category. See the [taxonomy csv file](https://plaid.com/documents/pfc-taxonomy-all.csv)...")
	_ = cmd.MarkFlagRequired("pfc-primary-category")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newBetaTransactionsRulesListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyClientUserId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "transactions-rules-list",
		Short: "Return a list of rules created for the Item associated with the access token.",
		Example: "  plaid-cli beta transactions-rules-list --client-user-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/beta/transactions/rules/v1/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID representing the end user whose rules should be listed.")
	_ = cmd.MarkFlagRequired("client-user-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newBetaTransactionsRulesRemoveCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyClientUserId string
	var bodyRuleId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "transactions-rules-remove",
		Short: "Remove transaction rule",
		Example: "  plaid-cli beta transactions-rules-remove --client-user-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/beta/transactions/rules/v1/remove"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodyRuleId != "" {
				body["rule_id"] = bodyRuleId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID representing the end user the rule belongs to.")
	_ = cmd.MarkFlagRequired("client-user-id")
	cmd.Flags().StringVar(&bodyRuleId, "rule-id", "", "A rule's unique identifier")
	_ = cmd.MarkFlagRequired("rule-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newBetaTransactionsUserInsightsGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyClientUserId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "transactions-user-insights-get",
		Short: "Obtain user insights based on transactions sent through /transactions/enrich",
		Example: "  plaid-cli beta transactions-user-insights-get --client-user-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/beta/transactions/user_insights/v1/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique client-provided `client_user_id` to retrieve insights for.")
	_ = cmd.MarkFlagRequired("client-user-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

