// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newConsentCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "consent",
		Short: "Manage consent",
	}

	cmd.AddCommand(newConsentEventsGetCmd(flags))
	return cmd
}

func newConsentEventsGetCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "events-get",
		Aliases: []string{"create"},
		Short: "List a historical log of item consent events",
		Example: "  plaid-cli consent events-get --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/consent/events/get"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

