// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newEmployersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "employers",
		Short: "Manage employers",
	}

	cmd.AddCommand(newEmployersSearchCmd(flags))
	return cmd
}

func newEmployersSearchCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyQuery string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "search",
		Aliases: []string{"create"},
		Short: "Search employer database",
		Example: "  plaid-cli employers search --query value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/employers/search"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyQuery != "" {
				body["query"] = bodyQuery
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyQuery, "query", "", "The employer name to be searched for.")
	_ = cmd.MarkFlagRequired("query")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

