// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newIdentityVerificationCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "identity-verification",
		Short: "Manage identity verification",
	}

	cmd.AddCommand(newIdentityVerificationAutofillCreateCmd(flags))
	cmd.AddCommand(newIdentityVerificationCreateCmd(flags))
	cmd.AddCommand(newIdentityVerificationGetCmd(flags))
	cmd.AddCommand(newIdentityVerificationListCmd(flags))
	cmd.AddCommand(newIdentityVerificationRetryCmd(flags))
	return cmd
}

func newIdentityVerificationAutofillCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyIdentityVerificationId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "autofill-create",
		Short: "Create autofill for an Identity Verification",
		Example: "  plaid-cli identity-verification autofill-create --identity-verification-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/identity_verification/autofill/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyIdentityVerificationId != "" {
				body["identity_verification_id"] = bodyIdentityVerificationId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyIdentityVerificationId, "identity-verification-id", "", "ID of the associated Identity Verification attempt.")
	_ = cmd.MarkFlagRequired("identity-verification-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newIdentityVerificationCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyClientUserId string
	var bodyGaveConsent bool
	var bodyIsIdempotent bool
	var bodyIsShareable bool
	var bodySecret string
	var bodyTemplateId string
	var bodyUserId string

	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a new Identity Verification",
		Example: "  plaid-cli identity-verification create --template-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/identity_verification/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodyGaveConsent != false {
				body["gave_consent"] = bodyGaveConsent
			}
			if bodyIsIdempotent != false {
				body["is_idempotent"] = bodyIsIdempotent
			}
			if bodyIsShareable != false {
				body["is_shareable"] = bodyIsShareable
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyTemplateId != "" {
				body["template_id"] = bodyTemplateId
			}
			if bodyUserId != "" {
				body["user_id"] = bodyUserId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID that identifies the end user in your system. Either a `user_id` or the `client_user_id` must be...")
	cmd.Flags().BoolVar(&bodyGaveConsent, "gave-consent", false, "A flag specifying whether the end user has already agreed to a privacy policy specifying that their data will be...")
	_ = cmd.MarkFlagRequired("gave-consent")
	cmd.Flags().BoolVar(&bodyIsIdempotent, "is-idempotent", false, "An optional flag specifying how you would like Plaid to handle attempts to create an Identity Verification when an...")
	cmd.Flags().BoolVar(&bodyIsShareable, "is-shareable", false, "A flag specifying whether you would like Plaid to expose a shareable URL for the verification being created.")
	_ = cmd.MarkFlagRequired("is-shareable")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyTemplateId, "template-id", "", "ID of the associated Identity Verification template. Like all Plaid identifiers, this is case-sensitive.")
	_ = cmd.MarkFlagRequired("template-id")
	cmd.Flags().StringVar(&bodyUserId, "user-id", "", "Unique user identifier, created by calling `/user/create`. Either a `user_id` or the `client_user_id` must be...")

	return cmd
}

func newIdentityVerificationGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyIdentityVerificationId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "get",
		Short: "Retrieve Identity Verification",
		Example: "  plaid-cli identity-verification get --identity-verification-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/identity_verification/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyIdentityVerificationId != "" {
				body["identity_verification_id"] = bodyIdentityVerificationId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyIdentityVerificationId, "identity-verification-id", "", "ID of the associated Identity Verification attempt.")
	_ = cmd.MarkFlagRequired("identity-verification-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newIdentityVerificationListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyClientUserId string
	var bodyCursor string
	var bodySecret string
	var bodyTemplateId string

	cmd := &cobra.Command{
		Use:   "list",
		Short: "List Identity Verifications",
		Example: "  plaid-cli identity-verification list --template-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/identity_verification/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyTemplateId != "" {
				body["template_id"] = bodyTemplateId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID that identifies the end user in your system. Either a `user_id` or the `client_user_id` must be...")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "An identifier that determines which page of results you receive.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyTemplateId, "template-id", "", "ID of the associated Identity Verification template. Like all Plaid identifiers, this is case-sensitive.")
	_ = cmd.MarkFlagRequired("template-id")

	return cmd
}

func newIdentityVerificationRetryCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyClientUserId string
	var bodyIsShareable bool
	var bodySecret string
	var bodyStrategy string
	var bodyTemplateId string

	cmd := &cobra.Command{
		Use:   "retry",
		Short: "Retry an Identity Verification",
		Example: "  plaid-cli identity-verification retry --client-user-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/identity_verification/retry"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodyIsShareable != false {
				body["is_shareable"] = bodyIsShareable
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStrategy != "" {
				body["strategy"] = bodyStrategy
			}
			if bodyTemplateId != "" {
				body["template_id"] = bodyTemplateId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID that identifies the end user in your system. Either a `user_id` or the `client_user_id` must be...")
	_ = cmd.MarkFlagRequired("client-user-id")
	cmd.Flags().BoolVar(&bodyIsShareable, "is-shareable", false, "A flag specifying whether you would like Plaid to expose a shareable URL for the verification being retried. If a...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStrategy, "strategy", "", "An instruction specifying what steps the new Identity Verification attempt should require the user to complete:...")
	_ = cmd.MarkFlagRequired("strategy")
	cmd.Flags().StringVar(&bodyTemplateId, "template-id", "", "ID of the associated Identity Verification template. Like all Plaid identifiers, this is case-sensitive.")
	_ = cmd.MarkFlagRequired("template-id")

	return cmd
}

