// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newIncomeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "income",
		Short: "Manage income",
	}

	cmd.AddCommand(newIncomeVerificationCreateCmd(flags))
	cmd.AddCommand(newIncomeVerificationDocumentsDownloadCmd(flags))
	cmd.AddCommand(newIncomeVerificationPaystubsGetCmd(flags))
	cmd.AddCommand(newIncomeVerificationPrecheckCmd(flags))
	cmd.AddCommand(newIncomeVerificationTaxformsGetCmd(flags))
	return cmd
}

func newIncomeVerificationCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyPrecheckId string
	var bodySecret string
	var bodyWebhook string

	cmd := &cobra.Command{
		Use:   "verification-create",
		Aliases: []string{"create"},
		Short: "(Deprecated) Create an income verification instance",
		Example: "  plaid-cli income verification-create --webhook value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/income/verification/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyPrecheckId != "" {
				body["precheck_id"] = bodyPrecheckId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWebhook != "" {
				body["webhook"] = bodyWebhook
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyPrecheckId, "precheck-id", "", "The ID of a precheck created with `/income/verification/precheck`. Will be used to improve conversion of the income...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWebhook, "webhook", "", "The URL endpoint to which Plaid should send webhooks related to the progress of the income verification process.")
	_ = cmd.MarkFlagRequired("webhook")

	return cmd
}

func newIncomeVerificationDocumentsDownloadCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyClientId string
	var bodyDocumentId string
	var bodyIncomeVerificationId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "verification-documents-download",
		Short: "(Deprecated) Download the original documents used for income verification",
		Example: "  plaid-cli income verification-documents-download",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/income/verification/documents/download"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyDocumentId != "" {
				body["document_id"] = bodyDocumentId
			}
			if bodyIncomeVerificationId != "" {
				body["income_verification_id"] = bodyIncomeVerificationId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyDocumentId, "document-id", "", "The document ID to download. If passed, a single document will be returned in the resulting zip file, rather than...")
	cmd.Flags().StringVar(&bodyIncomeVerificationId, "income-verification-id", "", "The ID of the verification.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newIncomeVerificationPaystubsGetCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyClientId string
	var bodyIncomeVerificationId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "verification-paystubs-get",
		Short: "(Deprecated) Retrieve information from the paystubs used for income verification",
		Example: "  plaid-cli income verification-paystubs-get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/income/verification/paystubs/get"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyIncomeVerificationId != "" {
				body["income_verification_id"] = bodyIncomeVerificationId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyIncomeVerificationId, "income-verification-id", "", "The ID of the verification for which to get paystub information.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newIncomeVerificationPrecheckCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "verification-precheck",
		Short: "(Deprecated) Check digital income verification eligibility and optimize conversion",
		Example: "  plaid-cli income verification-precheck",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/income/verification/precheck"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newIncomeVerificationTaxformsGetCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyClientId string
	var bodyIncomeVerificationId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "verification-taxforms-get",
		Short: "(Deprecated) Retrieve information from the tax documents used for income verification",
		Example: "  plaid-cli income verification-taxforms-get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/income/verification/taxforms/get"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyIncomeVerificationId != "" {
				body["income_verification_id"] = bodyIncomeVerificationId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyIncomeVerificationId, "income-verification-id", "", "The ID of the verification.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

