// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newIssuesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "issues",
		Short: "Manage issues",
	}

	cmd.AddCommand(newIssuesGetCmd(flags))
	cmd.AddCommand(newIssuesSearchCmd(flags))
	cmd.AddCommand(newIssuesSubscribeCmd(flags))
	return cmd
}

func newIssuesGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyIssueId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "get",
		Aliases: []string{"create"},
		Short: "Get an Issue",
		Example: "  plaid-cli issues get --issue-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/issues/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyIssueId != "" {
				body["issue_id"] = bodyIssueId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyIssueId, "issue-id", "", "The unique identifier of the issue to retrieve.")
	_ = cmd.MarkFlagRequired("issue-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newIssuesSearchCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyItemId string
	var bodyLinkSessionId string
	var bodyLinkSessionRequestId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "search",
		Short: "Search for an Issue",
		Example: "  plaid-cli issues search",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/issues/search"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyItemId != "" {
				body["item_id"] = bodyItemId
			}
			if bodyLinkSessionId != "" {
				body["link_session_id"] = bodyLinkSessionId
			}
			if bodyLinkSessionRequestId != "" {
				body["link_session_request_id"] = bodyLinkSessionRequestId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyItemId, "item-id", "", "A unique identifier for the Plaid Item.")
	cmd.Flags().StringVar(&bodyLinkSessionId, "link-session-id", "", "A unique identifier for the Link session.")
	cmd.Flags().StringVar(&bodyLinkSessionRequestId, "link-session-request-id", "", "The `request_id` for the Link session that might have had an institution connection issue.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newIssuesSubscribeCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyIssueId string
	var bodySecret string
	var bodyWebhook string

	cmd := &cobra.Command{
		Use:   "subscribe",
		Short: "Subscribe to an Issue",
		Example: "  plaid-cli issues subscribe --issue-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/issues/subscribe"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyIssueId != "" {
				body["issue_id"] = bodyIssueId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWebhook != "" {
				body["webhook"] = bodyWebhook
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyIssueId, "issue-id", "", "The unique identifier of the issue to subscribe to.")
	_ = cmd.MarkFlagRequired("issue-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWebhook, "webhook", "", "The webhook URL where notifications should be sent when the issue status changes.")
	_ = cmd.MarkFlagRequired("webhook")

	return cmd
}

