// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newPaymentInitiationCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "payment-initiation",
		Short: "Manage payment initiation",
	}

	cmd.AddCommand(newPaymentInitiationConsentCreateCmd(flags))
	cmd.AddCommand(newPaymentInitiationConsentGetCmd(flags))
	cmd.AddCommand(newPaymentInitiationConsentPaymentExecuteCmd(flags))
	cmd.AddCommand(newPaymentInitiationConsentRevokeCmd(flags))
	cmd.AddCommand(newPaymentInitiationCreatePaymentTokenCmd(flags))
	cmd.AddCommand(newPaymentInitiationPaymentCreateCmd(flags))
	cmd.AddCommand(newPaymentInitiationPaymentGetCmd(flags))
	cmd.AddCommand(newPaymentInitiationPaymentListCmd(flags))
	cmd.AddCommand(newPaymentInitiationPaymentReverseCmd(flags))
	cmd.AddCommand(newPaymentInitiationRecipientCreateCmd(flags))
	cmd.AddCommand(newPaymentInitiationRecipientGetCmd(flags))
	cmd.AddCommand(newPaymentInitiationRecipientListCmd(flags))
	return cmd
}

func newPaymentInitiationConsentCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyRecipientId string
	var bodyReference string
	var bodySecret string
	var bodyType string

	cmd := &cobra.Command{
		Use:   "consent-create",
		Aliases: []string{"create"},
		Short: "Create payment consent",
		Example: "  plaid-cli payment-initiation consent-create --recipient-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/payment_initiation/consent/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyRecipientId != "" {
				body["recipient_id"] = bodyRecipientId
			}
			if bodyReference != "" {
				body["reference"] = bodyReference
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyType != "" {
				body["type"] = bodyType
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyRecipientId, "recipient-id", "", "The ID of the recipient the payment consent is for. The created consent can be used to transfer funds to this...")
	_ = cmd.MarkFlagRequired("recipient-id")
	cmd.Flags().StringVar(&bodyReference, "reference", "", "A reference for the payment consent. This must be an alphanumeric string with at most 18 characters and must not...")
	_ = cmd.MarkFlagRequired("reference")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyType, "type", "", "Payment consent type. Defines possible use case for payments made with the given consent. `SWEEPING`: Allows moving...")

	return cmd
}

func newPaymentInitiationConsentGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyConsentId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "consent-get",
		Short: "Get payment consent",
		Example: "  plaid-cli payment-initiation consent-get --consent-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/payment_initiation/consent/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyConsentId != "" {
				body["consent_id"] = bodyConsentId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyConsentId, "consent-id", "", "The `consent_id` returned from `/payment_initiation/consent/create`.")
	_ = cmd.MarkFlagRequired("consent-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newPaymentInitiationConsentPaymentExecuteCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyConsentId string
	var bodyIdempotencyKey string
	var bodyProcessingMode string
	var bodyReference string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "consent-payment-execute",
		Short: "Execute a single payment using consent",
		Example: "  plaid-cli payment-initiation consent-payment-execute --consent-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/payment_initiation/consent/payment/execute"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyConsentId != "" {
				body["consent_id"] = bodyConsentId
			}
			if bodyIdempotencyKey != "" {
				body["idempotency_key"] = bodyIdempotencyKey
			}
			if bodyProcessingMode != "" {
				body["processing_mode"] = bodyProcessingMode
			}
			if bodyReference != "" {
				body["reference"] = bodyReference
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyConsentId, "consent-id", "", "The consent ID.")
	_ = cmd.MarkFlagRequired("consent-id")
	cmd.Flags().StringVar(&bodyIdempotencyKey, "idempotency-key", "", "A random key provided by the client, per unique consent payment. Maximum of 128 characters. The API supports...")
	_ = cmd.MarkFlagRequired("idempotency-key")
	cmd.Flags().StringVar(&bodyProcessingMode, "processing-mode", "", "Decides the mode under which the payment processing should be performed, using `IMMEDIATE` as default. `IMMEDIATE`:...")
	cmd.Flags().StringVar(&bodyReference, "reference", "", "A reference for the payment. This must be an alphanumeric string with at most 18 characters and must not contain any...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newPaymentInitiationConsentRevokeCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyConsentId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "consent-revoke",
		Short: "Revoke payment consent",
		Example: "  plaid-cli payment-initiation consent-revoke --consent-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/payment_initiation/consent/revoke"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyConsentId != "" {
				body["consent_id"] = bodyConsentId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyConsentId, "consent-id", "", "The consent ID.")
	_ = cmd.MarkFlagRequired("consent-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newPaymentInitiationCreatePaymentTokenCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyPaymentId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "create-payment-token",
		Short: "Create payment token",
		Example: "  plaid-cli payment-initiation create-payment-token --payment-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/payment_initiation/payment/token/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyPaymentId != "" {
				body["payment_id"] = bodyPaymentId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyPaymentId, "payment-id", "", "The `payment_id` returned from `/payment_initiation/payment/create`.")
	_ = cmd.MarkFlagRequired("payment-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newPaymentInitiationPaymentCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyRecipientId string
	var bodyReference string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "payment-create",
		Short: "Create a payment",
		Example: "  plaid-cli payment-initiation payment-create --recipient-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/payment_initiation/payment/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyRecipientId != "" {
				body["recipient_id"] = bodyRecipientId
			}
			if bodyReference != "" {
				body["reference"] = bodyReference
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyRecipientId, "recipient-id", "", "The ID of the recipient the payment is for.")
	_ = cmd.MarkFlagRequired("recipient-id")
	cmd.Flags().StringVar(&bodyReference, "reference", "", "A reference for the payment. This must be an alphanumeric string with at most 18 characters and must not contain any...")
	_ = cmd.MarkFlagRequired("reference")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newPaymentInitiationPaymentGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyPaymentId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "payment-get",
		Short: "Get payment details",
		Example: "  plaid-cli payment-initiation payment-get --payment-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/payment_initiation/payment/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyPaymentId != "" {
				body["payment_id"] = bodyPaymentId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyPaymentId, "payment-id", "", "The `payment_id` returned from `/payment_initiation/payment/create`.")
	_ = cmd.MarkFlagRequired("payment-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newPaymentInitiationPaymentListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyConsentId string
	var bodyCount int
	var bodyCursor string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "payment-list",
		Short: "List payments",
		Example: "  plaid-cli payment-initiation payment-list",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/payment_initiation/payment/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyConsentId != "" {
				body["consent_id"] = bodyConsentId
			}
			if bodyCount != 0 {
				body["count"] = bodyCount
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyConsentId, "consent-id", "", "The consent ID. If specified, only payments, executed using this consent, will be returned.")
	cmd.Flags().IntVar(&bodyCount, "count", 10, "The maximum number of payments to return. If `count` is not specified, a maximum of 10 payments will be returned,...")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "A string in RFC 3339 format (i.e. '2019-12-06T22:35:49Z'). Only payments created before the cursor will be returned.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newPaymentInitiationPaymentReverseCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCounterpartyDateOfBirth string
	var bodyIdempotencyKey string
	var bodyPaymentId string
	var bodyReference string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "payment-reverse",
		Short: "Reverse an existing payment",
		Example: "  plaid-cli payment-initiation payment-reverse --idempotency-key value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/payment_initiation/payment/reverse"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCounterpartyDateOfBirth != "" {
				body["counterparty_date_of_birth"] = bodyCounterpartyDateOfBirth
			}
			if bodyIdempotencyKey != "" {
				body["idempotency_key"] = bodyIdempotencyKey
			}
			if bodyPaymentId != "" {
				body["payment_id"] = bodyPaymentId
			}
			if bodyReference != "" {
				body["reference"] = bodyReference
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyCounterpartyDateOfBirth, "counterparty-date-of-birth", "", "The counterparty's birthdate, in [ISO 8601](https://wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD) format.")
	cmd.Flags().StringVar(&bodyIdempotencyKey, "idempotency-key", "", "A random key provided by the client, per unique wallet transaction. Maximum of 128 characters. The API supports...")
	_ = cmd.MarkFlagRequired("idempotency-key")
	cmd.Flags().StringVar(&bodyPaymentId, "payment-id", "", "The ID of the payment to reverse")
	_ = cmd.MarkFlagRequired("payment-id")
	cmd.Flags().StringVar(&bodyReference, "reference", "", "A reference for the refund. This must be an alphanumeric string with 6 to 18 characters and must not contain any...")
	_ = cmd.MarkFlagRequired("reference")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newPaymentInitiationRecipientCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyIban string
	var bodyName string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "recipient-create",
		Short: "Create payment recipient",
		Example: "  plaid-cli payment-initiation recipient-create --name value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/payment_initiation/recipient/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyIban != "" {
				body["iban"] = bodyIban
			}
			if bodyName != "" {
				body["name"] = bodyName
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyIban, "iban", "", "The International Bank Account Number (IBAN) for the recipient. If BACS data is not provided, an IBAN is required.")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the recipient. We recommend using strings of length 18 or less and avoid special characters to ensure...")
	_ = cmd.MarkFlagRequired("name")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newPaymentInitiationRecipientGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyRecipientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "recipient-get",
		Short: "Get payment recipient",
		Example: "  plaid-cli payment-initiation recipient-get --recipient-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/payment_initiation/recipient/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyRecipientId != "" {
				body["recipient_id"] = bodyRecipientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyRecipientId, "recipient-id", "", "The ID of the recipient")
	_ = cmd.MarkFlagRequired("recipient-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newPaymentInitiationRecipientListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCount int
	var bodyCursor string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "recipient-list",
		Short: "List payment recipients",
		Example: "  plaid-cli payment-initiation recipient-list",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/payment_initiation/recipient/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCount != 0 {
				body["count"] = bodyCount
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().IntVar(&bodyCount, "count", 100, "The maximum number of recipients to return. If `count` is not specified, a maximum of 100 recipients will be...")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "A value representing the latest recipient to be included in the response. Set this from `next_cursor` received from...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

