// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newProcessorCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "processor",
		Short: "Manage processor",
	}

	cmd.AddCommand(newProcessorAccountGetCmd(flags))
	cmd.AddCommand(newProcessorApexTokenCreateCmd(flags))
	cmd.AddCommand(newProcessorAuthGetCmd(flags))
	cmd.AddCommand(newProcessorBalanceGetCmd(flags))
	cmd.AddCommand(newProcessorBankTransferCreateCmd(flags))
	cmd.AddCommand(newProcessorIdentityGetCmd(flags))
	cmd.AddCommand(newProcessorIdentityMatchCmd(flags))
	cmd.AddCommand(newProcessorInvestmentsHoldingsGetCmd(flags))
	cmd.AddCommand(newProcessorInvestmentsTransactionsGetCmd(flags))
	cmd.AddCommand(newProcessorLiabilitiesGetCmd(flags))
	cmd.AddCommand(newProcessorSignalDecisionReportCmd(flags))
	cmd.AddCommand(newProcessorSignalEvaluateCmd(flags))
	cmd.AddCommand(newProcessorSignalPrepareCmd(flags))
	cmd.AddCommand(newProcessorSignalReturnReportCmd(flags))
	cmd.AddCommand(newProcessorStripeBankAccountTokenCreateCmd(flags))
	cmd.AddCommand(newProcessorTokenCreateCmd(flags))
	cmd.AddCommand(newProcessorTokenPermissionsGetCmd(flags))
	cmd.AddCommand(newProcessorTokenPermissionsSetCmd(flags))
	cmd.AddCommand(newProcessorTokenWebhookUpdateCmd(flags))
	cmd.AddCommand(newProcessorTransactionsGetCmd(flags))
	cmd.AddCommand(newProcessorTransactionsRecurringGetCmd(flags))
	cmd.AddCommand(newProcessorTransactionsRefreshCmd(flags))
	cmd.AddCommand(newProcessorTransactionsSyncCmd(flags))
	return cmd
}

func newProcessorAccountGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "account-get",
		Aliases: []string{"create"},
		Short: "Retrieve the account associated with a processor token",
		Example: "  plaid-cli processor account-get --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/account/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorApexTokenCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyAccountId string
	var bodyClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "apex-token-create",
		Short: "Create Apex bank account token",
		Example: "  plaid-cli processor apex-token-create --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/apex/processor_token/create"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyAccountId != "" {
				body["account_id"] = bodyAccountId
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyAccountId, "account-id", "", "The `account_id` value obtained from the `onSuccess` callback in Link")
	_ = cmd.MarkFlagRequired("account-id")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorAuthGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "auth-get",
		Short: "Retrieve Auth data",
		Example: "  plaid-cli processor auth-get --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/auth/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorBalanceGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "balance-get",
		Short: "Retrieve Balance data",
		Example: "  plaid-cli processor balance-get --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/balance/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorBankTransferCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAchClass string
	var bodyAmount string
	var bodyClientId string
	var bodyCustomTag string
	var bodyDescription string
	var bodyIdempotencyKey string
	var bodyIsoCurrencyCode string
	var bodyNetwork string
	var bodyOriginationAccountId string
	var bodyProcessorToken string
	var bodySecret string
	var bodyType string

	cmd := &cobra.Command{
		Use:   "bank-transfer-create",
		Short: "Create a bank transfer as a processor",
		Example: "  plaid-cli processor bank-transfer-create --amount value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/bank_transfer/create"
			body := map[string]any{}
			if bodyAchClass != "" {
				body["ach_class"] = bodyAchClass
			}
			if bodyAmount != "" {
				body["amount"] = bodyAmount
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCustomTag != "" {
				body["custom_tag"] = bodyCustomTag
			}
			if bodyDescription != "" {
				body["description"] = bodyDescription
			}
			if bodyIdempotencyKey != "" {
				body["idempotency_key"] = bodyIdempotencyKey
			}
			if bodyIsoCurrencyCode != "" {
				body["iso_currency_code"] = bodyIsoCurrencyCode
			}
			if bodyNetwork != "" {
				body["network"] = bodyNetwork
			}
			if bodyOriginationAccountId != "" {
				body["origination_account_id"] = bodyOriginationAccountId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyType != "" {
				body["type"] = bodyType
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAchClass, "ach-class", "", "Specifies the use case of the transfer. Required for transfers on an ACH network. For more details, see [ACH SEC...")
	cmd.Flags().StringVar(&bodyAmount, "amount", "", "The amount of the bank transfer (decimal string with two digits of precision e.g. '10.00').")
	_ = cmd.MarkFlagRequired("amount")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyCustomTag, "custom-tag", "", "An arbitrary string provided by the client for storage with the bank transfer. May be up to 100 characters.")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "The transfer description. Maximum of 10 characters.")
	_ = cmd.MarkFlagRequired("description")
	cmd.Flags().StringVar(&bodyIdempotencyKey, "idempotency-key", "", "A random key provided by the client, per unique bank transfer. Maximum of 50 characters. The API supports...")
	_ = cmd.MarkFlagRequired("idempotency-key")
	cmd.Flags().StringVar(&bodyIsoCurrencyCode, "iso-currency-code", "", "The currency of the transfer amount – should be set to 'USD'.")
	_ = cmd.MarkFlagRequired("iso-currency-code")
	cmd.Flags().StringVar(&bodyNetwork, "network", "", "The network or rails used for the transfer. Valid options are `ach`, `same-day-ach`, or `wire`.")
	_ = cmd.MarkFlagRequired("network")
	cmd.Flags().StringVar(&bodyOriginationAccountId, "origination-account-id", "", "Plaid’s unique identifier for the origination account for this transfer. If you have more than one origination...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyType, "type", "", "The type of bank transfer. This will be either `debit` or `credit`. A `debit` indicates a transfer of money into the...")
	_ = cmd.MarkFlagRequired("type")

	return cmd
}

func newProcessorIdentityGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "identity-get",
		Short: "Retrieve Identity data",
		Example: "  plaid-cli processor identity-get --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/identity/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorIdentityMatchCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "identity-match",
		Short: "Retrieve identity match score",
		Example: "  plaid-cli processor identity-match --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/identity/match"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorInvestmentsHoldingsGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "investments-holdings-get",
		Short: "Retrieve Investment Holdings",
		Example: "  plaid-cli processor investments-holdings-get --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/investments/holdings/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorInvestmentsTransactionsGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyEndDate string
	var bodyProcessorToken string
	var bodySecret string
	var bodyStartDate string

	cmd := &cobra.Command{
		Use:   "investments-transactions-get",
		Short: "Get investment transactions data",
		Example: "  plaid-cli processor investments-transactions-get --end-date value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/investments/transactions/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEndDate != "" {
				body["end_date"] = bodyEndDate
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStartDate != "" {
				body["start_date"] = bodyStartDate
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEndDate, "end-date", "", "The latest date for which data should be returned. Dates should be formatted as YYYY-MM-DD.")
	_ = cmd.MarkFlagRequired("end-date")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStartDate, "start-date", "", "The earliest date for which data should be returned. Dates should be formatted as YYYY-MM-DD.")
	_ = cmd.MarkFlagRequired("start-date")

	return cmd
}

func newProcessorLiabilitiesGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "liabilities-get",
		Short: "Retrieve Liabilities data",
		Example: "  plaid-cli processor liabilities-get --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/liabilities/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorSignalDecisionReportCmd(flags *rootFlags) *cobra.Command {
	var bodyAmountInstantlyAvailable float64
	var bodyClientId string
	var bodyClientTransactionId string
	var bodyDaysFundsOnHold int
	var bodyDecisionOutcome string
	var bodyInitiated bool
	var bodyPaymentMethod string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "signal-decision-report",
		Short: "Report whether you initiated an ACH transaction",
		Example: "  plaid-cli processor signal-decision-report --client-transaction-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/signal/decision/report"
			body := map[string]any{}
			if bodyAmountInstantlyAvailable != 0.0 {
				body["amount_instantly_available"] = bodyAmountInstantlyAvailable
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientTransactionId != "" {
				body["client_transaction_id"] = bodyClientTransactionId
			}
			if bodyDaysFundsOnHold != 0 {
				body["days_funds_on_hold"] = bodyDaysFundsOnHold
			}
			if bodyDecisionOutcome != "" {
				body["decision_outcome"] = bodyDecisionOutcome
			}
			if bodyInitiated != false {
				body["initiated"] = bodyInitiated
			}
			if bodyPaymentMethod != "" {
				body["payment_method"] = bodyPaymentMethod
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().Float64Var(&bodyAmountInstantlyAvailable, "amount-instantly-available", 0.0, "The amount (in USD) made available to your customers instantly following the debit transaction. It could be a...")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientTransactionId, "client-transaction-id", "", "Must be the same as the `client_transaction_id` supplied when calling `/signal/evaluate`")
	_ = cmd.MarkFlagRequired("client-transaction-id")
	cmd.Flags().IntVar(&bodyDaysFundsOnHold, "days-funds-on-hold", 0, "The actual number of days (hold time) since the ACH debit transaction that you wait before making funds available to...")
	cmd.Flags().StringVar(&bodyDecisionOutcome, "decision-outcome", "", "The payment decision from the risk assessment. `APPROVE`: approve the transaction without requiring further actions...")
	cmd.Flags().BoolVar(&bodyInitiated, "initiated", false, "`true` if the ACH transaction was initiated, `false` otherwise. This field must be returned as a boolean. If...")
	_ = cmd.MarkFlagRequired("initiated")
	cmd.Flags().StringVar(&bodyPaymentMethod, "payment-method", "", "The payment method to complete the transaction after the risk assessment. It may be different from the default...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorSignalEvaluateCmd(flags *rootFlags) *cobra.Command {
	var bodyAmount float64
	var bodyClientId string
	var bodyClientTransactionId string
	var bodyClientUserId string
	var bodyDefaultPaymentMethod string
	var bodyIsRecurring bool
	var bodyProcessorToken string
	var bodyRulesetKey string
	var bodySecret string
	var bodyUserPresent bool

	cmd := &cobra.Command{
		Use:   "signal-evaluate",
		Short: "Evaluate a planned ACH transaction",
		Example: "  plaid-cli processor signal-evaluate --client-transaction-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/signal/evaluate"
			body := map[string]any{}
			if bodyAmount != 0.0 {
				body["amount"] = bodyAmount
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientTransactionId != "" {
				body["client_transaction_id"] = bodyClientTransactionId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodyDefaultPaymentMethod != "" {
				body["default_payment_method"] = bodyDefaultPaymentMethod
			}
			if bodyIsRecurring != false {
				body["is_recurring"] = bodyIsRecurring
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodyRulesetKey != "" {
				body["ruleset_key"] = bodyRulesetKey
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyUserPresent != false {
				body["user_present"] = bodyUserPresent
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().Float64Var(&bodyAmount, "amount", 0.0, "The transaction amount, in USD (e.g. `102.05`)")
	_ = cmd.MarkFlagRequired("amount")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientTransactionId, "client-transaction-id", "", "The unique ID that you would like to use to refer to this transaction. For your convenience mapping your internal...")
	_ = cmd.MarkFlagRequired("client-transaction-id")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID that identifies the end user in your system. This ID is used to correlate requests by a user with...")
	cmd.Flags().StringVar(&bodyDefaultPaymentMethod, "default-payment-method", "", "The default ACH or non-ACH payment method to complete the transaction. `SAME_DAY_ACH`: Same Day ACH by Nacha. The...")
	cmd.Flags().BoolVar(&bodyIsRecurring, "is-recurring", false, "**true** if the ACH transaction is a recurring transaction; **false** otherwise")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodyRulesetKey, "ruleset-key", "", "The key of the ruleset to use for this transaction. You can configure a ruleset using the Plaid Dashboard, under...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().BoolVar(&bodyUserPresent, "user-present", false, "`true` if the end user is present while initiating the ACH transfer and the endpoint is being called; `false`...")

	return cmd
}

func newProcessorSignalPrepareCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "signal-prepare",
		Short: "Opt-in a processor token to Signal",
		Example: "  plaid-cli processor signal-prepare --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/signal/prepare"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorSignalReturnReportCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyClientTransactionId string
	var bodyProcessorToken string
	var bodyReturnCode string
	var bodyReturnedAt string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "signal-return-report",
		Short: "Report a return for an ACH transaction",
		Example: "  plaid-cli processor signal-return-report --client-transaction-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/signal/return/report"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientTransactionId != "" {
				body["client_transaction_id"] = bodyClientTransactionId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodyReturnCode != "" {
				body["return_code"] = bodyReturnCode
			}
			if bodyReturnedAt != "" {
				body["returned_at"] = bodyReturnedAt
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientTransactionId, "client-transaction-id", "", "Must be the same as the `client_transaction_id` supplied when calling `/processor/signal/evaluate`")
	_ = cmd.MarkFlagRequired("client-transaction-id")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodyReturnCode, "return-code", "", "Must be a valid ACH return code (e.g. 'R01') If formatted incorrectly, this will result in an...")
	_ = cmd.MarkFlagRequired("return-code")
	cmd.Flags().StringVar(&bodyReturnedAt, "returned-at", "", "Date and time when you receive the returns from your payment processors, in ISO 8601 format (`YYYY-MM-DDTHH:mm:ssZ`).")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorStripeBankAccountTokenCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyAccountId string
	var bodyClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "stripe-bank-account-token-create",
		Short: "Create Stripe bank account token",
		Example: "  plaid-cli processor stripe-bank-account-token-create --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/stripe/bank_account_token/create"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyAccountId != "" {
				body["account_id"] = bodyAccountId
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyAccountId, "account-id", "", "The `account_id` value obtained from the `onSuccess` callback in Link")
	_ = cmd.MarkFlagRequired("account-id")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorTokenCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyAccountId string
	var bodyClientId string
	var bodyProcessor string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "token-create",
		Short: "Create processor token",
		Example: "  plaid-cli processor token-create --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/token/create"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyAccountId != "" {
				body["account_id"] = bodyAccountId
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessor != "" {
				body["processor"] = bodyProcessor
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyAccountId, "account-id", "", "The `account_id` value obtained from the `onSuccess` callback in Link")
	_ = cmd.MarkFlagRequired("account-id")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessor, "processor", "", "The processor you are integrating with.")
	_ = cmd.MarkFlagRequired("processor")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorTokenPermissionsGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "token-permissions-get",
		Short: "Get a processor token's product permissions",
		Example: "  plaid-cli processor token-permissions-get --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/token/permissions/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorTokenPermissionsSetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "token-permissions-set",
		Short: "Control a processor's access to products",
		Example: "  plaid-cli processor token-permissions-set --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/token/permissions/set"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorTokenWebhookUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProcessorToken string
	var bodySecret string
	var bodyWebhook string

	cmd := &cobra.Command{
		Use:   "token-webhook-update",
		Short: "Update a processor token's webhook URL",
		Example: "  plaid-cli processor token-webhook-update --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/token/webhook/update"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWebhook != "" {
				body["webhook"] = bodyWebhook
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWebhook, "webhook", "", "The new webhook URL to associate with the processor token. To remove a webhook from a processor token, set to `null`.")
	_ = cmd.MarkFlagRequired("webhook")

	return cmd
}

func newProcessorTransactionsGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyEndDate string
	var bodyProcessorToken string
	var bodySecret string
	var bodyStartDate string

	cmd := &cobra.Command{
		Use:   "transactions-get",
		Short: "Get transaction data",
		Example: "  plaid-cli processor transactions-get --end-date value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/transactions/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEndDate != "" {
				body["end_date"] = bodyEndDate
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStartDate != "" {
				body["start_date"] = bodyStartDate
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEndDate, "end-date", "", "The latest date for which data should be returned. Dates should be formatted as YYYY-MM-DD.")
	_ = cmd.MarkFlagRequired("end-date")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStartDate, "start-date", "", "The earliest date for which data should be returned. Dates should be formatted as YYYY-MM-DD.")
	_ = cmd.MarkFlagRequired("start-date")

	return cmd
}

func newProcessorTransactionsRecurringGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "transactions-recurring-get",
		Short: "Fetch recurring transaction streams",
		Example: "  plaid-cli processor transactions-recurring-get --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/transactions/recurring/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorTransactionsRefreshCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "transactions-refresh",
		Short: "Refresh transaction data",
		Example: "  plaid-cli processor transactions-refresh --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/transactions/refresh"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProcessorTransactionsSyncCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCount int
	var bodyCursor string
	var bodyProcessorToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "transactions-sync",
		Short: "Get incremental transaction updates on a processor token",
		Example: "  plaid-cli processor transactions-sync --processor-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/processor/transactions/sync"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCount != 0 {
				body["count"] = bodyCount
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodyProcessorToken != "" {
				body["processor_token"] = bodyProcessorToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().IntVar(&bodyCount, "count", 100, "The number of transaction updates to fetch.")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "The cursor value represents the last update requested. Providing it will cause the response to only return changes...")
	cmd.Flags().StringVar(&bodyProcessorToken, "processor-token", "", "The processor token obtained from the Plaid integration partner. Processor tokens are in the format:...")
	_ = cmd.MarkFlagRequired("processor-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

