// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newProtectCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "protect",
		Short: "Manage protect",
	}

	cmd.AddCommand(newProtectComputeCmd(flags))
	cmd.AddCommand(newProtectEventGetCmd(flags))
	cmd.AddCommand(newProtectEventSendCmd(flags))
	cmd.AddCommand(newProtectReportCreateCmd(flags))
	cmd.AddCommand(newProtectUserInsightsGetCmd(flags))
	return cmd
}

func newProtectComputeCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyModel string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "compute",
		Aliases: []string{"create"},
		Short: "Compute Protect Trust Index Score",
		Example: "  plaid-cli protect compute --model value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/protect/compute"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyModel != "" {
				body["model"] = bodyModel
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyModel, "model", "", "The name of the Trust Index model to use for calculating the Trust Index Score, with a major.minor version suffix....")
	_ = cmd.MarkFlagRequired("model")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProtectEventGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyEventId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "event-get",
		Short: "Get information about a user event",
		Example: "  plaid-cli protect event-get --event-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/protect/event/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEventId != "" {
				body["event_id"] = bodyEventId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEventId, "event-id", "", "The event ID to retrieve information for.")
	_ = cmd.MarkFlagRequired("event-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newProtectEventSendCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyProtectSessionId string
	var bodyRequestTrustIndex bool
	var bodySecret string
	var bodyTimestamp string

	cmd := &cobra.Command{
		Use:   "event-send",
		Short: "Send a new event to enrich user data",
		Example: "  plaid-cli protect event-send",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/protect/event/send"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyProtectSessionId != "" {
				body["protect_session_id"] = bodyProtectSessionId
			}
			if bodyRequestTrustIndex != false {
				body["request_trust_index"] = bodyRequestTrustIndex
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyTimestamp != "" {
				body["timestamp"] = bodyTimestamp
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyProtectSessionId, "protect-session-id", "", "Protect Session ID should be provided for any event correlated with a frontend user session started via the Protect SDK.")
	cmd.Flags().BoolVar(&bodyRequestTrustIndex, "request-trust-index", false, "Whether this event should be scored with Trust Index. The default is false.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyTimestamp, "timestamp", "", "Timestamp of the event. Might be the current moment or a time in the past. In [ISO...")

	return cmd
}

func newProtectReportCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAchReturnCode string
	var bodyClientId string
	var bodyNotes string
	var bodyReportConfidence string
	var bodyReportSource string
	var bodyReportType string
	var bodySecret string
	var bodyUserId string

	cmd := &cobra.Command{
		Use:   "report-create",
		Short: "Create a Protect report",
		Example: "  plaid-cli protect report-create --report-confidence value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/protect/report/create"
			body := map[string]any{}
			if bodyAchReturnCode != "" {
				body["ach_return_code"] = bodyAchReturnCode
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyNotes != "" {
				body["notes"] = bodyNotes
			}
			if bodyReportConfidence != "" {
				body["report_confidence"] = bodyReportConfidence
			}
			if bodyReportSource != "" {
				body["report_source"] = bodyReportSource
			}
			if bodyReportType != "" {
				body["report_type"] = bodyReportType
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyUserId != "" {
				body["user_id"] = bodyUserId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAchReturnCode, "ach-return-code", "", "Must be a valid ACH return code (e.g. `R01`), required if `report_type` is `ACH_RETURN`.")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyNotes, "notes", "", "Additional context or details about the report, required if `report_type` is `OTHER`.")
	cmd.Flags().StringVar(&bodyReportConfidence, "report-confidence", "", "The confidence level of the incident report. `CONFIRMED` indicates the incident has been verified and definitively...")
	_ = cmd.MarkFlagRequired("report-confidence")
	cmd.Flags().StringVar(&bodyReportSource, "report-source", "", "The source that identified or reported the incident. `INTERNAL_REVIEW` - Incident was identified through internal...")
	_ = cmd.MarkFlagRequired("report-source")
	cmd.Flags().StringVar(&bodyReportType, "report-type", "", "The type of incident being reported. `USER_ACCOUNT_TAKEOVER` - Indicates that a legitimate user's account was...")
	_ = cmd.MarkFlagRequired("report-type")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyUserId, "user-id", "", "The Plaid User ID associated with the report.")

	return cmd
}

func newProtectUserInsightsGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyClientUserId string
	var bodySecret string
	var bodyUserId string

	cmd := &cobra.Command{
		Use:   "user-insights-get",
		Short: "Get Protect user insights",
		Example: "  plaid-cli protect user-insights-get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/protect/user/insights/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyUserId != "" {
				body["user_id"] = bodyUserId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID representing the end user. Either `user_id` or `client_user_id` must be provided.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyUserId, "user-id", "", "The Plaid User ID. Either `user_id` or `client_user_id` must be provided.")

	return cmd
}

