// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newSandboxCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "sandbox",
		Short: "Manage sandbox",
	}

	cmd.AddCommand(newSandboxBankIncomeFireWebhookCmd(flags))
	cmd.AddCommand(newSandboxBankTransferFireWebhookCmd(flags))
	cmd.AddCommand(newSandboxBankTransferSimulateCmd(flags))
	cmd.AddCommand(newSandboxCraCashflowUpdatesUpdateCmd(flags))
	cmd.AddCommand(newSandboxIncomeFireWebhookCmd(flags))
	cmd.AddCommand(newSandboxItemFireWebhookCmd(flags))
	cmd.AddCommand(newSandboxItemResetLoginCmd(flags))
	cmd.AddCommand(newSandboxItemSetVerificationStatusCmd(flags))
	cmd.AddCommand(newSandboxOauthSelectAccountsCmd(flags))
	cmd.AddCommand(newSandboxPaymentProfileResetLoginCmd(flags))
	cmd.AddCommand(newSandboxPaymentSimulateCmd(flags))
	cmd.AddCommand(newSandboxProcessorTokenCreateCmd(flags))
	cmd.AddCommand(newSandboxPublicTokenCreateCmd(flags))
	cmd.AddCommand(newSandboxTransactionsCreateCmd(flags))
	cmd.AddCommand(newSandboxTransferFireWebhookCmd(flags))
	cmd.AddCommand(newSandboxTransferLedgerDepositSimulateCmd(flags))
	cmd.AddCommand(newSandboxTransferLedgerSimulateAvailableCmd(flags))
	cmd.AddCommand(newSandboxTransferLedgerWithdrawSimulateCmd(flags))
	cmd.AddCommand(newSandboxTransferRefundSimulateCmd(flags))
	cmd.AddCommand(newSandboxTransferRepaymentSimulateCmd(flags))
	cmd.AddCommand(newSandboxTransferSimulateCmd(flags))
	cmd.AddCommand(newSandboxTransferSweepSimulateCmd(flags))
	cmd.AddCommand(newSandboxTransferTestClockAdvanceCmd(flags))
	cmd.AddCommand(newSandboxTransferTestClockCreateCmd(flags))
	cmd.AddCommand(newSandboxTransferTestClockGetCmd(flags))
	cmd.AddCommand(newSandboxTransferTestClockListCmd(flags))
	cmd.AddCommand(newSandboxUserResetLoginCmd(flags))
	return cmd
}

func newSandboxBankIncomeFireWebhookCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string
	var bodyWebhookCode string
	var bodyWebhookOverride string

	cmd := &cobra.Command{
		Use:   "bank-income-fire-webhook",
		Aliases: []string{"create"},
		Short: "Manually fire a bank income webhook in sandbox",
		Example: "  plaid-cli sandbox bank-income-fire-webhook --webhook-code value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/bank_income/fire_webhook"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWebhookCode != "" {
				body["webhook_code"] = bodyWebhookCode
			}
			if bodyWebhookOverride != "" {
				body["webhook_override"] = bodyWebhookOverride
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWebhookCode, "webhook-code", "", "The webhook codes this endpoint can be used to test")
	_ = cmd.MarkFlagRequired("webhook-code")
	cmd.Flags().StringVar(&bodyWebhookOverride, "webhook-override", "", "The URL to which the webhook should be sent. If provided, this will override the URL set in the dashboard.")

	return cmd
}

func newSandboxBankTransferFireWebhookCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string
	var bodyWebhook string

	cmd := &cobra.Command{
		Use:   "bank-transfer-fire-webhook",
		Short: "Manually fire a Bank Transfer webhook",
		Example: "  plaid-cli sandbox bank-transfer-fire-webhook --webhook value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/bank_transfer/fire_webhook"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWebhook != "" {
				body["webhook"] = bodyWebhook
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWebhook, "webhook", "", "The URL to which the webhook should be sent.")
	_ = cmd.MarkFlagRequired("webhook")

	return cmd
}

func newSandboxBankTransferSimulateCmd(flags *rootFlags) *cobra.Command {
	var bodyBankTransferId string
	var bodyClientId string
	var bodyEventType string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "bank-transfer-simulate",
		Short: "Simulate a bank transfer event in Sandbox",
		Example: "  plaid-cli sandbox bank-transfer-simulate --bank-transfer-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/bank_transfer/simulate"
			body := map[string]any{}
			if bodyBankTransferId != "" {
				body["bank_transfer_id"] = bodyBankTransferId
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEventType != "" {
				body["event_type"] = bodyEventType
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyBankTransferId, "bank-transfer-id", "", "Plaid’s unique identifier for a bank transfer.")
	_ = cmd.MarkFlagRequired("bank-transfer-id")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEventType, "event-type", "", "The asynchronous event to be simulated. May be: `posted`, `failed`, or `reversed`. An error will be returned if the...")
	_ = cmd.MarkFlagRequired("event-type")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newSandboxCraCashflowUpdatesUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string
	var bodyUserId string
	var bodyUserToken string

	cmd := &cobra.Command{
		Use:   "cra-cashflow-updates-update",
		Short: "Trigger an update for Cash Flow Updates",
		Example: "  plaid-cli sandbox cra-cashflow-updates-update",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/cra/cashflow_updates/update"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyUserId != "" {
				body["user_id"] = bodyUserId
			}
			if bodyUserToken != "" {
				body["user_token"] = bodyUserToken
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyUserId, "user-id", "", "A unique user identifier, created by `/user/create`. Integrations that began using `/user/create` after December 10,...")
	cmd.Flags().StringVar(&bodyUserToken, "user-token", "", "The user token associated with the User data is being requested for. This field is used only by customers with...")

	return cmd
}

func newSandboxIncomeFireWebhookCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyItemId string
	var bodySecret string
	var bodyUserId string
	var bodyVerificationStatus string
	var bodyWebhook string
	var bodyWebhookCode string

	cmd := &cobra.Command{
		Use:   "income-fire-webhook",
		Short: "Manually fire an Income webhook",
		Example: "  plaid-cli sandbox income-fire-webhook --item-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/income/fire_webhook"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyItemId != "" {
				body["item_id"] = bodyItemId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyUserId != "" {
				body["user_id"] = bodyUserId
			}
			if bodyVerificationStatus != "" {
				body["verification_status"] = bodyVerificationStatus
			}
			if bodyWebhook != "" {
				body["webhook"] = bodyWebhook
			}
			if bodyWebhookCode != "" {
				body["webhook_code"] = bodyWebhookCode
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyItemId, "item-id", "", "The Item ID associated with the verification.")
	_ = cmd.MarkFlagRequired("item-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyUserId, "user-id", "", "The Plaid `user_id` of the User associated with this webhook, warning, or error.")
	cmd.Flags().StringVar(&bodyVerificationStatus, "verification-status", "", "`VERIFICATION_STATUS_PROCESSING_COMPLETE`: The income verification status processing has completed. If the user...")
	cmd.Flags().StringVar(&bodyWebhook, "webhook", "", "The URL to which the webhook should be sent.")
	_ = cmd.MarkFlagRequired("webhook")
	cmd.Flags().StringVar(&bodyWebhookCode, "webhook-code", "", "The webhook codes that can be fired by this test endpoint.")
	_ = cmd.MarkFlagRequired("webhook-code")

	return cmd
}

func newSandboxItemFireWebhookCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyClientId string
	var bodySecret string
	var bodyWebhookCode string
	var bodyWebhookType string

	cmd := &cobra.Command{
		Use:   "item-fire-webhook",
		Short: "Fire a test webhook",
		Example: "  plaid-cli sandbox item-fire-webhook --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/item/fire_webhook"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWebhookCode != "" {
				body["webhook_code"] = bodyWebhookCode
			}
			if bodyWebhookType != "" {
				body["webhook_type"] = bodyWebhookType
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWebhookCode, "webhook-code", "", "The webhook codes that can be fired by this test endpoint.")
	_ = cmd.MarkFlagRequired("webhook-code")
	cmd.Flags().StringVar(&bodyWebhookType, "webhook-type", "", "The webhook types that can be fired by this test endpoint.")

	return cmd
}

func newSandboxItemResetLoginCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "item-reset-login",
		Short: "Force a Sandbox Item into an error state",
		Example: "  plaid-cli sandbox item-reset-login --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/item/reset_login"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newSandboxItemSetVerificationStatusCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyAccountId string
	var bodyClientId string
	var bodySecret string
	var bodyVerificationStatus string

	cmd := &cobra.Command{
		Use:   "item-set-verification-status",
		Short: "Set verification status for Sandbox account",
		Example: "  plaid-cli sandbox item-set-verification-status --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/item/set_verification_status"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyAccountId != "" {
				body["account_id"] = bodyAccountId
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyVerificationStatus != "" {
				body["verification_status"] = bodyVerificationStatus
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyAccountId, "account-id", "", "The `account_id` of the account whose verification status is to be modified")
	_ = cmd.MarkFlagRequired("account-id")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyVerificationStatus, "verification-status", "", "The verification status to set the account to.")
	_ = cmd.MarkFlagRequired("verification-status")

	return cmd
}

func newSandboxOauthSelectAccountsCmd(flags *rootFlags) *cobra.Command {
	var bodyOauthStateId string

	cmd := &cobra.Command{
		Use:   "oauth-select-accounts",
		Short: "Save the selected accounts when connecting to the Platypus Oauth institution",
		Example: "  plaid-cli sandbox oauth-select-accounts --oauth-state-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/oauth/select_accounts"
			body := map[string]any{}
			if bodyOauthStateId != "" {
				body["oauth_state_id"] = bodyOauthStateId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyOauthStateId, "oauth-state-id", "", "Oauth state id")
	_ = cmd.MarkFlagRequired("oauth-state-id")

	return cmd
}

func newSandboxPaymentProfileResetLoginCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyPaymentProfileToken string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "payment-profile-reset-login",
		Short: "Reset the login of a Payment Profile",
		Example: "  plaid-cli sandbox payment-profile-reset-login --payment-profile-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/payment_profile/reset_login"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyPaymentProfileToken != "" {
				body["payment_profile_token"] = bodyPaymentProfileToken
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyPaymentProfileToken, "payment-profile-token", "", "A payment profile token associated with the Payment Profile data that is being requested.")
	_ = cmd.MarkFlagRequired("payment-profile-token")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newSandboxPaymentSimulateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyPaymentId string
	var bodySecret string
	var bodyStatus string
	var bodyWebhook string

	cmd := &cobra.Command{
		Use:   "payment-simulate",
		Short: "Simulate a payment event in Sandbox",
		Example: "  plaid-cli sandbox payment-simulate --payment-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/payment/simulate"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyPaymentId != "" {
				body["payment_id"] = bodyPaymentId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStatus != "" {
				body["status"] = bodyStatus
			}
			if bodyWebhook != "" {
				body["webhook"] = bodyWebhook
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyPaymentId, "payment-id", "", "The ID of the payment to simulate")
	_ = cmd.MarkFlagRequired("payment-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "The status to set the payment to. Valid statuses include: - `PAYMENT_STATUS_INITIATED` -...")
	_ = cmd.MarkFlagRequired("status")
	cmd.Flags().StringVar(&bodyWebhook, "webhook", "", "The webhook url to use for any payment events triggered by the simulated status change.")
	_ = cmd.MarkFlagRequired("webhook")

	return cmd
}

func newSandboxProcessorTokenCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyInstitutionId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "processor-token-create",
		Short: "Create a test Item and processor token",
		Example: "  plaid-cli sandbox processor-token-create --institution-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/processor_token/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyInstitutionId != "" {
				body["institution_id"] = bodyInstitutionId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyInstitutionId, "institution-id", "", "The ID of the institution the Item will be associated with")
	_ = cmd.MarkFlagRequired("institution-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newSandboxPublicTokenCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyInstitutionId string
	var bodySecret string
	var bodyUserId string
	var bodyUserToken string

	cmd := &cobra.Command{
		Use:   "public-token-create",
		Short: "Create a test Item",
		Example: "  plaid-cli sandbox public-token-create --institution-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/public_token/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyInstitutionId != "" {
				body["institution_id"] = bodyInstitutionId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyUserId != "" {
				body["user_id"] = bodyUserId
			}
			if bodyUserToken != "" {
				body["user_token"] = bodyUserToken
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyInstitutionId, "institution-id", "", "The ID of the institution the Item will be associated with")
	_ = cmd.MarkFlagRequired("institution-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyUserId, "user-id", "", "A unique user identifier, created by `/user/create`. Integrations that began using `/user/create` after December 10,...")
	cmd.Flags().StringVar(&bodyUserToken, "user-token", "", "The user token associated with the User data is being requested for. This field is used only by customers with...")

	return cmd
}

func newSandboxTransactionsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "transactions-create",
		Short: "Create sandbox transactions",
		Example: "  plaid-cli sandbox transactions-create --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/transactions/create"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newSandboxTransferFireWebhookCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string
	var bodyWebhook string

	cmd := &cobra.Command{
		Use:   "transfer-fire-webhook",
		Short: "Manually fire a Transfer webhook",
		Example: "  plaid-cli sandbox transfer-fire-webhook --webhook value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/transfer/fire_webhook"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWebhook != "" {
				body["webhook"] = bodyWebhook
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWebhook, "webhook", "", "The URL to which the webhook should be sent.")
	_ = cmd.MarkFlagRequired("webhook")

	return cmd
}

func newSandboxTransferLedgerDepositSimulateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyEventType string
	var bodySecret string
	var bodySweepId string

	cmd := &cobra.Command{
		Use:   "transfer-ledger-deposit-simulate",
		Short: "Simulate a ledger deposit event in Sandbox",
		Example: "  plaid-cli sandbox transfer-ledger-deposit-simulate --event-type value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/transfer/ledger/deposit/simulate"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEventType != "" {
				body["event_type"] = bodyEventType
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodySweepId != "" {
				body["sweep_id"] = bodySweepId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEventType, "event-type", "", "The asynchronous event to be simulated. May be: `posted`, `settled`, `failed`, or `returned`. An error will be...")
	_ = cmd.MarkFlagRequired("event-type")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodySweepId, "sweep-id", "", "Plaid’s unique identifier for a sweep.")
	_ = cmd.MarkFlagRequired("sweep-id")

	return cmd
}

func newSandboxTransferLedgerSimulateAvailableCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyLedgerId string
	var bodyOriginatorClientId string
	var bodySecret string
	var bodyTestClockId string
	var bodyWebhook string

	cmd := &cobra.Command{
		Use:   "transfer-ledger-simulate-available",
		Short: "Simulate converting pending balance to available balance",
		Example: "  plaid-cli sandbox transfer-ledger-simulate-available",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/transfer/ledger/simulate_available"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyLedgerId != "" {
				body["ledger_id"] = bodyLedgerId
			}
			if bodyOriginatorClientId != "" {
				body["originator_client_id"] = bodyOriginatorClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyTestClockId != "" {
				body["test_clock_id"] = bodyTestClockId
			}
			if bodyWebhook != "" {
				body["webhook"] = bodyWebhook
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyLedgerId, "ledger-id", "", "Specify which ledger balance to simulate converting pending balance to available balance. If this field is left...")
	cmd.Flags().StringVar(&bodyOriginatorClientId, "originator-client-id", "", "Client ID of the end customer (i.e. the originator). Only applicable to Transfer for Platforms customers.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyTestClockId, "test-clock-id", "", "Plaid’s unique identifier for a test clock. If provided, only the pending balance that is due before the...")
	cmd.Flags().StringVar(&bodyWebhook, "webhook", "", "The webhook URL to which a `TRANSFER_EVENTS_UPDATE` webhook should be sent.")

	return cmd
}

func newSandboxTransferLedgerWithdrawSimulateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyEventType string
	var bodySecret string
	var bodySweepId string

	cmd := &cobra.Command{
		Use:   "transfer-ledger-withdraw-simulate",
		Short: "Simulate a ledger withdraw event in Sandbox",
		Example: "  plaid-cli sandbox transfer-ledger-withdraw-simulate --event-type value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/transfer/ledger/withdraw/simulate"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEventType != "" {
				body["event_type"] = bodyEventType
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodySweepId != "" {
				body["sweep_id"] = bodySweepId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEventType, "event-type", "", "The asynchronous event to be simulated. May be: `posted`, `settled`, `failed`, or `returned`. An error will be...")
	_ = cmd.MarkFlagRequired("event-type")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodySweepId, "sweep-id", "", "Plaid’s unique identifier for a sweep.")
	_ = cmd.MarkFlagRequired("sweep-id")

	return cmd
}

func newSandboxTransferRefundSimulateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyEventType string
	var bodyRefundId string
	var bodySecret string
	var bodyTestClockId string
	var bodyWebhook string

	cmd := &cobra.Command{
		Use:   "transfer-refund-simulate",
		Short: "Simulate a refund event in Sandbox",
		Example: "  plaid-cli sandbox transfer-refund-simulate --event-type value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/transfer/refund/simulate"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEventType != "" {
				body["event_type"] = bodyEventType
			}
			if bodyRefundId != "" {
				body["refund_id"] = bodyRefundId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyTestClockId != "" {
				body["test_clock_id"] = bodyTestClockId
			}
			if bodyWebhook != "" {
				body["webhook"] = bodyWebhook
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEventType, "event-type", "", "The asynchronous event to be simulated. May be: `refund.posted`, `refund.settled`, `refund.failed`, or...")
	_ = cmd.MarkFlagRequired("event-type")
	cmd.Flags().StringVar(&bodyRefundId, "refund-id", "", "Plaid’s unique identifier for a refund.")
	_ = cmd.MarkFlagRequired("refund-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyTestClockId, "test-clock-id", "", "Plaid’s unique identifier for a test clock. If provided, the event to be simulated is created at the...")
	cmd.Flags().StringVar(&bodyWebhook, "webhook", "", "The webhook URL to which a `TRANSFER_EVENTS_UPDATE` webhook should be sent.")

	return cmd
}

func newSandboxTransferRepaymentSimulateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "transfer-repayment-simulate",
		Short: "Trigger the creation of a repayment",
		Example: "  plaid-cli sandbox transfer-repayment-simulate",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/transfer/repayment/simulate"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newSandboxTransferSimulateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyEventType string
	var bodySecret string
	var bodyTestClockId string
	var bodyTransferId string
	var bodyWebhook string

	cmd := &cobra.Command{
		Use:   "transfer-simulate",
		Short: "Simulate a transfer event in Sandbox",
		Example: "  plaid-cli sandbox transfer-simulate --event-type value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/transfer/simulate"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEventType != "" {
				body["event_type"] = bodyEventType
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyTestClockId != "" {
				body["test_clock_id"] = bodyTestClockId
			}
			if bodyTransferId != "" {
				body["transfer_id"] = bodyTransferId
			}
			if bodyWebhook != "" {
				body["webhook"] = bodyWebhook
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEventType, "event-type", "", "The asynchronous event to be simulated. May be: `posted`, `settled`, `failed`, `funds_available`, or `returned`. An...")
	_ = cmd.MarkFlagRequired("event-type")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyTestClockId, "test-clock-id", "", "Plaid’s unique identifier for a test clock. If provided, the event to be simulated is created at the...")
	cmd.Flags().StringVar(&bodyTransferId, "transfer-id", "", "Plaid’s unique identifier for a transfer.")
	_ = cmd.MarkFlagRequired("transfer-id")
	cmd.Flags().StringVar(&bodyWebhook, "webhook", "", "The webhook URL to which a `TRANSFER_EVENTS_UPDATE` webhook should be sent.")

	return cmd
}

func newSandboxTransferSweepSimulateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string
	var bodyTestClockId string
	var bodyWebhook string

	cmd := &cobra.Command{
		Use:   "transfer-sweep-simulate",
		Short: "Simulate creating a sweep",
		Example: "  plaid-cli sandbox transfer-sweep-simulate",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/transfer/sweep/simulate"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyTestClockId != "" {
				body["test_clock_id"] = bodyTestClockId
			}
			if bodyWebhook != "" {
				body["webhook"] = bodyWebhook
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyTestClockId, "test-clock-id", "", "Plaid’s unique identifier for a test clock. If provided, the sweep to be simulated is created on the day of the...")
	cmd.Flags().StringVar(&bodyWebhook, "webhook", "", "The webhook URL to which a `TRANSFER_EVENTS_UPDATE` webhook should be sent.")

	return cmd
}

func newSandboxTransferTestClockAdvanceCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyNewVirtualTime string
	var bodySecret string
	var bodyTestClockId string

	cmd := &cobra.Command{
		Use:   "transfer-test-clock-advance",
		Short: "Advance a test clock",
		Example: "  plaid-cli sandbox transfer-test-clock-advance --new-virtual-time value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/transfer/test_clock/advance"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyNewVirtualTime != "" {
				body["new_virtual_time"] = bodyNewVirtualTime
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyTestClockId != "" {
				body["test_clock_id"] = bodyTestClockId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyNewVirtualTime, "new-virtual-time", "", "The virtual timestamp on the test clock. This will be of the form `2006-01-02T15:04:05Z`.")
	_ = cmd.MarkFlagRequired("new-virtual-time")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyTestClockId, "test-clock-id", "", "Plaid’s unique identifier for a test clock. This field is only populated in the Sandbox environment, and only if a...")
	_ = cmd.MarkFlagRequired("test-clock-id")

	return cmd
}

func newSandboxTransferTestClockCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string
	var bodyVirtualTime string

	cmd := &cobra.Command{
		Use:   "transfer-test-clock-create",
		Short: "Create a test clock",
		Example: "  plaid-cli sandbox transfer-test-clock-create",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/transfer/test_clock/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyVirtualTime != "" {
				body["virtual_time"] = bodyVirtualTime
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyVirtualTime, "virtual-time", "", "The virtual timestamp on the test clock. If not provided, the current timestamp will be used. This will be of the...")

	return cmd
}

func newSandboxTransferTestClockGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string
	var bodyTestClockId string

	cmd := &cobra.Command{
		Use:   "transfer-test-clock-get",
		Short: "Get a test clock",
		Example: "  plaid-cli sandbox transfer-test-clock-get --test-clock-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/transfer/test_clock/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyTestClockId != "" {
				body["test_clock_id"] = bodyTestClockId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyTestClockId, "test-clock-id", "", "Plaid’s unique identifier for a test clock. This field is only populated in the Sandbox environment, and only if a...")
	_ = cmd.MarkFlagRequired("test-clock-id")

	return cmd
}

func newSandboxTransferTestClockListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCount int
	var bodyEndVirtualTime string
	var bodyOffset int
	var bodySecret string
	var bodyStartVirtualTime string

	cmd := &cobra.Command{
		Use:   "transfer-test-clock-list",
		Short: "List test clocks",
		Example: "  plaid-cli sandbox transfer-test-clock-list",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/transfer/test_clock/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCount != 0 {
				body["count"] = bodyCount
			}
			if bodyEndVirtualTime != "" {
				body["end_virtual_time"] = bodyEndVirtualTime
			}
			if bodyOffset != 0 {
				body["offset"] = bodyOffset
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStartVirtualTime != "" {
				body["start_virtual_time"] = bodyStartVirtualTime
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().IntVar(&bodyCount, "count", 25, "The maximum number of test clocks to return.")
	cmd.Flags().StringVar(&bodyEndVirtualTime, "end-virtual-time", "", "The end virtual timestamp of test clocks to return. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)")
	cmd.Flags().IntVar(&bodyOffset, "offset", 0, "The number of test clocks to skip before returning results.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStartVirtualTime, "start-virtual-time", "", "The start virtual timestamp of test clocks to return. This should be in RFC 3339 format (i.e. `2019-12-06T22:35:49Z`)")

	return cmd
}

func newSandboxUserResetLoginCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string
	var bodyUserId string
	var bodyUserToken string

	cmd := &cobra.Command{
		Use:   "user-reset-login",
		Short: "Force item(s) for a Sandbox User into an error state",
		Example: "  plaid-cli sandbox user-reset-login",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/sandbox/user/reset_login"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyUserId != "" {
				body["user_id"] = bodyUserId
			}
			if bodyUserToken != "" {
				body["user_token"] = bodyUserToken
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyUserId, "user-id", "", "A unique user identifier, created by `/user/create`. Integrations that began using `/user/create` after December 10,...")
	cmd.Flags().StringVar(&bodyUserToken, "user-token", "", "The user token associated with the User data is being requested for. This field is used only by customers with...")

	return cmd
}

