// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newSignalCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "signal",
		Short: "Manage signal",
	}

	cmd.AddCommand(newSignalDecisionReportCmd(flags))
	cmd.AddCommand(newSignalEvaluateCmd(flags))
	cmd.AddCommand(newSignalPrepareCmd(flags))
	cmd.AddCommand(newSignalReturnReportCmd(flags))
	cmd.AddCommand(newSignalScheduleCmd(flags))
	return cmd
}

func newSignalDecisionReportCmd(flags *rootFlags) *cobra.Command {
	var bodyAmountInstantlyAvailable float64
	var bodyClientId string
	var bodyClientTransactionId string
	var bodyDaysFundsOnHold int
	var bodyDecisionOutcome string
	var bodyInitiated bool
	var bodyPaymentMethod string
	var bodySecret string
	var bodySubmittedAt string

	cmd := &cobra.Command{
		Use:   "decision-report",
		Aliases: []string{"create"},
		Short: "Report whether you initiated an ACH transaction",
		Example: "  plaid-cli signal decision-report --client-transaction-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/signal/decision/report"
			body := map[string]any{}
			if bodyAmountInstantlyAvailable != 0.0 {
				body["amount_instantly_available"] = bodyAmountInstantlyAvailable
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientTransactionId != "" {
				body["client_transaction_id"] = bodyClientTransactionId
			}
			if bodyDaysFundsOnHold != 0 {
				body["days_funds_on_hold"] = bodyDaysFundsOnHold
			}
			if bodyDecisionOutcome != "" {
				body["decision_outcome"] = bodyDecisionOutcome
			}
			if bodyInitiated != false {
				body["initiated"] = bodyInitiated
			}
			if bodyPaymentMethod != "" {
				body["payment_method"] = bodyPaymentMethod
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodySubmittedAt != "" {
				body["submitted_at"] = bodySubmittedAt
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().Float64Var(&bodyAmountInstantlyAvailable, "amount-instantly-available", 0.0, "The amount (in USD) made available to your customers instantly following the debit transaction. It could be a...")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientTransactionId, "client-transaction-id", "", "Must be the same as the `client_transaction_id` supplied when calling `/signal/evaluate`")
	_ = cmd.MarkFlagRequired("client-transaction-id")
	cmd.Flags().IntVar(&bodyDaysFundsOnHold, "days-funds-on-hold", 0, "The actual number of days (hold time) since the ACH debit transaction that you wait before making funds available to...")
	cmd.Flags().StringVar(&bodyDecisionOutcome, "decision-outcome", "", "The payment decision from the risk assessment. `APPROVE`: approve the transaction without requiring further actions...")
	cmd.Flags().BoolVar(&bodyInitiated, "initiated", false, "`true` if the ACH transaction was initiated, `false` otherwise. This field must be returned as a boolean. If...")
	_ = cmd.MarkFlagRequired("initiated")
	cmd.Flags().StringVar(&bodyPaymentMethod, "payment-method", "", "The payment method to complete the transaction after the risk assessment. It may be different from the default...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodySubmittedAt, "submitted-at", "", "The date the ACH debit was submitted to the bank for processing (in ISO 8601 format: `YYYY-MM-DDTHH:mm:ssZ`). This...")

	return cmd
}

func newSignalEvaluateCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyAccountId string
	var bodyAmount float64
	var bodyClientId string
	var bodyClientTransactionId string
	var bodyClientUserId string
	var bodyDefaultPaymentMethod string
	var bodyIsRecurring bool
	var bodyRiskProfileKey string
	var bodyRulesetKey string
	var bodySecret string
	var bodyUserPresent bool

	cmd := &cobra.Command{
		Use:   "evaluate",
		Short: "Evaluate a planned ACH transaction",
		Example: "  plaid-cli signal evaluate --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/signal/evaluate"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyAccountId != "" {
				body["account_id"] = bodyAccountId
			}
			if bodyAmount != 0.0 {
				body["amount"] = bodyAmount
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientTransactionId != "" {
				body["client_transaction_id"] = bodyClientTransactionId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodyDefaultPaymentMethod != "" {
				body["default_payment_method"] = bodyDefaultPaymentMethod
			}
			if bodyIsRecurring != false {
				body["is_recurring"] = bodyIsRecurring
			}
			if bodyRiskProfileKey != "" {
				body["risk_profile_key"] = bodyRiskProfileKey
			}
			if bodyRulesetKey != "" {
				body["ruleset_key"] = bodyRulesetKey
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyUserPresent != false {
				body["user_present"] = bodyUserPresent
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyAccountId, "account-id", "", "The Plaid `account_id` of the account that is the funding source for the proposed transaction. The `account_id` is...")
	_ = cmd.MarkFlagRequired("account-id")
	cmd.Flags().Float64Var(&bodyAmount, "amount", 0.0, "The transaction amount, in USD (e.g. `102.05`)")
	_ = cmd.MarkFlagRequired("amount")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientTransactionId, "client-transaction-id", "", "The unique ID that you would like to use to refer to this evaluation attempt - for example, a payment attempt ID....")
	_ = cmd.MarkFlagRequired("client-transaction-id")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID that identifies the end user in your system. This ID is used to correlate requests by a user with...")
	cmd.Flags().StringVar(&bodyDefaultPaymentMethod, "default-payment-method", "", "The default ACH payment method to complete the transaction. When using a Balance-only ruleset, this field is...")
	cmd.Flags().BoolVar(&bodyIsRecurring, "is-recurring", false, "Use `true` if the ACH transaction is a part of recurring schedule (for example, a monthly repayment); `false`...")
	cmd.Flags().StringVar(&bodyRiskProfileKey, "risk-profile-key", "", "Specifying `risk_profile_key` is deprecated. Please provide `ruleset` instead.")
	cmd.Flags().StringVar(&bodyRulesetKey, "ruleset-key", "", "The key of the ruleset to use for evaluating this transaction. You can create a ruleset using the Plaid Dashboard,...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().BoolVar(&bodyUserPresent, "user-present", false, "`true` if the end user is present while initiating the ACH transfer and the endpoint is being called; `false`...")

	return cmd
}

func newSignalPrepareCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "prepare",
		Short: "Opt-in an Item to Signal Transaction Scores",
		Example: "  plaid-cli signal prepare --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/signal/prepare"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newSignalReturnReportCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyClientTransactionId string
	var bodyReturnCode string
	var bodyReturnedAt string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "return-report",
		Short: "Report a return for an ACH transaction",
		Example: "  plaid-cli signal return-report --client-transaction-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/signal/return/report"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientTransactionId != "" {
				body["client_transaction_id"] = bodyClientTransactionId
			}
			if bodyReturnCode != "" {
				body["return_code"] = bodyReturnCode
			}
			if bodyReturnedAt != "" {
				body["returned_at"] = bodyReturnedAt
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientTransactionId, "client-transaction-id", "", "Must be the same as the `client_transaction_id` supplied when calling `/signal/evaluate` or `/accounts/balance/get`.")
	_ = cmd.MarkFlagRequired("client-transaction-id")
	cmd.Flags().StringVar(&bodyReturnCode, "return-code", "", "Must be a valid ACH return code (e.g. 'R01') If formatted incorrectly, this will result in an...")
	_ = cmd.MarkFlagRequired("return-code")
	cmd.Flags().StringVar(&bodyReturnedAt, "returned-at", "", "Date and time when you receive the returns from your payment processors, in ISO 8601 format (`YYYY-MM-DDTHH:mm:ssZ`).")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newSignalScheduleCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyAccountId string
	var bodyAmount float64
	var bodyClientId string
	var bodyClientTransactionId string
	var bodyDefaultPaymentMethod string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "schedule",
		Short: "Schedule a planned ACH transaction",
		Example: "  plaid-cli signal schedule --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/signal/schedule"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyAccountId != "" {
				body["account_id"] = bodyAccountId
			}
			if bodyAmount != 0.0 {
				body["amount"] = bodyAmount
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientTransactionId != "" {
				body["client_transaction_id"] = bodyClientTransactionId
			}
			if bodyDefaultPaymentMethod != "" {
				body["default_payment_method"] = bodyDefaultPaymentMethod
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyAccountId, "account-id", "", "The Plaid `account_id` of the account that is the funding source for the proposed transaction. The `account_id` is...")
	_ = cmd.MarkFlagRequired("account-id")
	cmd.Flags().Float64Var(&bodyAmount, "amount", 0.0, "The transaction amount, in USD (e.g. `102.05`)")
	_ = cmd.MarkFlagRequired("amount")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientTransactionId, "client-transaction-id", "", "The unique ID that you would like to use to refer to this transaction. For your convenience mapping your internal...")
	_ = cmd.MarkFlagRequired("client-transaction-id")
	cmd.Flags().StringVar(&bodyDefaultPaymentMethod, "default-payment-method", "", "The payment method specified in the `default_payment_method` field directly impacts the timing recommendations...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

