// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newStatementsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "statements",
		Short: "Manage statements",
	}

	cmd.AddCommand(newStatementsDownloadCmd(flags))
	cmd.AddCommand(newStatementsListCmd(flags))
	cmd.AddCommand(newStatementsRefreshCmd(flags))
	return cmd
}

func newStatementsDownloadCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyClientId string
	var bodySecret string
	var bodyStatementId string

	cmd := &cobra.Command{
		Use:   "download",
		Aliases: []string{"create"},
		Short: "Retrieve a single statement.",
		Example: "  plaid-cli statements download --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/statements/download"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStatementId != "" {
				body["statement_id"] = bodyStatementId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStatementId, "statement-id", "", "Plaid's unique identifier for the statement.")
	_ = cmd.MarkFlagRequired("statement-id")

	return cmd
}

func newStatementsListCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyClientId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "list",
		Short: "Retrieve a list of all statements associated with an item.",
		Example: "  plaid-cli statements list --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/statements/list"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newStatementsRefreshCmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyClientId string
	var bodyEndDate string
	var bodySecret string
	var bodyStartDate string

	cmd := &cobra.Command{
		Use:   "refresh",
		Short: "Refresh statements data.",
		Example: "  plaid-cli statements refresh --access-token value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/statements/refresh"
			body := map[string]any{}
			if bodyAccessToken != "" {
				body["access_token"] = bodyAccessToken
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEndDate != "" {
				body["end_date"] = bodyEndDate
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStartDate != "" {
				body["start_date"] = bodyStartDate
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token associated with the Item data is being requested for.")
	_ = cmd.MarkFlagRequired("access-token")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEndDate, "end-date", "", "The end date for statements, in 'YYYY-MM-DD' format, e.g. '2023-10-30'. You can request up to two years of data. To...")
	_ = cmd.MarkFlagRequired("end-date")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStartDate, "start-date", "", "The start date for statements, in 'YYYY-MM-DD' format, e.g. '2023-08-30'. To determine whether a statement falls...")
	_ = cmd.MarkFlagRequired("start-date")

	return cmd
}

