// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newWatchlistScreeningCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "watchlist-screening",
		Short: "Manage watchlist screening",
	}

	cmd.AddCommand(newWatchlistScreeningEntityCreateCmd(flags))
	cmd.AddCommand(newWatchlistScreeningEntityGetCmd(flags))
	cmd.AddCommand(newWatchlistScreeningEntityHistoryListCmd(flags))
	cmd.AddCommand(newWatchlistScreeningEntityHitListCmd(flags))
	cmd.AddCommand(newWatchlistScreeningEntityListCmd(flags))
	cmd.AddCommand(newWatchlistScreeningEntityProgramGetCmd(flags))
	cmd.AddCommand(newWatchlistScreeningEntityProgramListCmd(flags))
	cmd.AddCommand(newWatchlistScreeningEntityReviewCreateCmd(flags))
	cmd.AddCommand(newWatchlistScreeningEntityReviewListCmd(flags))
	cmd.AddCommand(newWatchlistScreeningEntityUpdateCmd(flags))
	cmd.AddCommand(newWatchlistScreeningIndividualCreateCmd(flags))
	cmd.AddCommand(newWatchlistScreeningIndividualGetCmd(flags))
	cmd.AddCommand(newWatchlistScreeningIndividualHistoryListCmd(flags))
	cmd.AddCommand(newWatchlistScreeningIndividualHitListCmd(flags))
	cmd.AddCommand(newWatchlistScreeningIndividualListCmd(flags))
	cmd.AddCommand(newWatchlistScreeningIndividualProgramGetCmd(flags))
	cmd.AddCommand(newWatchlistScreeningIndividualProgramListCmd(flags))
	cmd.AddCommand(newWatchlistScreeningIndividualReviewCreateCmd(flags))
	cmd.AddCommand(newWatchlistScreeningIndividualReviewListCmd(flags))
	cmd.AddCommand(newWatchlistScreeningIndividualUpdateCmd(flags))
	return cmd
}

func newWatchlistScreeningEntityCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyClientUserId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "entity-create",
		Aliases: []string{"create"},
		Short: "Create a watchlist screening for an entity",
		Example: "  plaid-cli watchlist-screening entity-create",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/entity/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID that identifies the end user in your system. Either a `user_id` or the `client_user_id` must be...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newWatchlistScreeningEntityGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyEntityWatchlistScreeningId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "entity-get",
		Short: "Get an entity screening",
		Example: "  plaid-cli watchlist-screening entity-get --entity-watchlist-screening-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/entity/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEntityWatchlistScreeningId != "" {
				body["entity_watchlist_screening_id"] = bodyEntityWatchlistScreeningId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEntityWatchlistScreeningId, "entity-watchlist-screening-id", "", "ID of the associated entity screening.")
	_ = cmd.MarkFlagRequired("entity-watchlist-screening-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newWatchlistScreeningEntityHistoryListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCursor string
	var bodyEntityWatchlistScreeningId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "entity-history-list",
		Short: "List history for entity watchlist screenings",
		Example: "  plaid-cli watchlist-screening entity-history-list --entity-watchlist-screening-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/entity/history/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodyEntityWatchlistScreeningId != "" {
				body["entity_watchlist_screening_id"] = bodyEntityWatchlistScreeningId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "An identifier that determines which page of results you receive.")
	cmd.Flags().StringVar(&bodyEntityWatchlistScreeningId, "entity-watchlist-screening-id", "", "ID of the associated entity screening.")
	_ = cmd.MarkFlagRequired("entity-watchlist-screening-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newWatchlistScreeningEntityHitListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCursor string
	var bodyEntityWatchlistScreeningId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "entity-hit-list",
		Short: "List hits for entity watchlist screenings",
		Example: "  plaid-cli watchlist-screening entity-hit-list --entity-watchlist-screening-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/entity/hit/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodyEntityWatchlistScreeningId != "" {
				body["entity_watchlist_screening_id"] = bodyEntityWatchlistScreeningId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "An identifier that determines which page of results you receive.")
	cmd.Flags().StringVar(&bodyEntityWatchlistScreeningId, "entity-watchlist-screening-id", "", "ID of the associated entity screening.")
	_ = cmd.MarkFlagRequired("entity-watchlist-screening-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newWatchlistScreeningEntityListCmd(flags *rootFlags) *cobra.Command {
	var bodyAssignee string
	var bodyClientId string
	var bodyClientUserId string
	var bodyCursor string
	var bodyEntityWatchlistProgramId string
	var bodySecret string
	var bodyStatus string

	cmd := &cobra.Command{
		Use:   "entity-list",
		Short: "List entity watchlist screenings",
		Example: "  plaid-cli watchlist-screening entity-list --entity-watchlist-program-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/entity/list"
			body := map[string]any{}
			if bodyAssignee != "" {
				body["assignee"] = bodyAssignee
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodyEntityWatchlistProgramId != "" {
				body["entity_watchlist_program_id"] = bodyEntityWatchlistProgramId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStatus != "" {
				body["status"] = bodyStatus
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAssignee, "assignee", "", "ID of the associated user. To retrieve the email address or other details of the person corresponding to this id,...")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID that identifies the end user in your system. Either a `user_id` or the `client_user_id` must be...")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "An identifier that determines which page of results you receive.")
	cmd.Flags().StringVar(&bodyEntityWatchlistProgramId, "entity-watchlist-program-id", "", "ID of the associated entity program.")
	_ = cmd.MarkFlagRequired("entity-watchlist-program-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "A status enum indicating whether a screening is still pending review, has been rejected, or has been cleared.")

	return cmd
}

func newWatchlistScreeningEntityProgramGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyEntityWatchlistProgramId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "entity-program-get",
		Short: "Get entity watchlist screening program",
		Example: "  plaid-cli watchlist-screening entity-program-get --entity-watchlist-program-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/entity/program/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyEntityWatchlistProgramId != "" {
				body["entity_watchlist_program_id"] = bodyEntityWatchlistProgramId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyEntityWatchlistProgramId, "entity-watchlist-program-id", "", "ID of the associated entity program.")
	_ = cmd.MarkFlagRequired("entity-watchlist-program-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newWatchlistScreeningEntityProgramListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCursor string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "entity-program-list",
		Short: "List entity watchlist screening programs",
		Example: "  plaid-cli watchlist-screening entity-program-list",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/entity/program/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "An identifier that determines which page of results you receive.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newWatchlistScreeningEntityReviewCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyComment string
	var bodyEntityWatchlistScreeningId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "entity-review-create",
		Short: "Create a review for an entity watchlist screening",
		Example: "  plaid-cli watchlist-screening entity-review-create --entity-watchlist-screening-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/entity/review/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyComment != "" {
				body["comment"] = bodyComment
			}
			if bodyEntityWatchlistScreeningId != "" {
				body["entity_watchlist_screening_id"] = bodyEntityWatchlistScreeningId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyComment, "comment", "", "A comment submitted by a team member as part of reviewing a watchlist screening.")
	cmd.Flags().StringVar(&bodyEntityWatchlistScreeningId, "entity-watchlist-screening-id", "", "ID of the associated entity screening.")
	_ = cmd.MarkFlagRequired("entity-watchlist-screening-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newWatchlistScreeningEntityReviewListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCursor string
	var bodyEntityWatchlistScreeningId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "entity-review-list",
		Short: "List reviews for entity watchlist screenings",
		Example: "  plaid-cli watchlist-screening entity-review-list --entity-watchlist-screening-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/entity/review/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodyEntityWatchlistScreeningId != "" {
				body["entity_watchlist_screening_id"] = bodyEntityWatchlistScreeningId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "An identifier that determines which page of results you receive.")
	cmd.Flags().StringVar(&bodyEntityWatchlistScreeningId, "entity-watchlist-screening-id", "", "ID of the associated entity screening.")
	_ = cmd.MarkFlagRequired("entity-watchlist-screening-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newWatchlistScreeningEntityUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyAssignee string
	var bodyClientId string
	var bodyClientUserId string
	var bodyEntityWatchlistScreeningId string
	var bodySecret string
	var bodyStatus string

	cmd := &cobra.Command{
		Use:   "entity-update",
		Short: "Update an entity screening",
		Example: "  plaid-cli watchlist-screening entity-update --entity-watchlist-screening-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/entity/update"
			body := map[string]any{}
			if bodyAssignee != "" {
				body["assignee"] = bodyAssignee
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodyEntityWatchlistScreeningId != "" {
				body["entity_watchlist_screening_id"] = bodyEntityWatchlistScreeningId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStatus != "" {
				body["status"] = bodyStatus
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAssignee, "assignee", "", "ID of the associated user. To retrieve the email address or other details of the person corresponding to this id,...")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID that identifies the end user in your system. Either a `user_id` or the `client_user_id` must be...")
	cmd.Flags().StringVar(&bodyEntityWatchlistScreeningId, "entity-watchlist-screening-id", "", "ID of the associated entity screening.")
	_ = cmd.MarkFlagRequired("entity-watchlist-screening-id")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "A status enum indicating whether a screening is still pending review, has been rejected, or has been cleared.")

	return cmd
}

func newWatchlistScreeningIndividualCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyClientUserId string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "individual-create",
		Short: "Create a watchlist screening for a person",
		Example: "  plaid-cli watchlist-screening individual-create",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/individual/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID that identifies the end user in your system. Either a `user_id` or the `client_user_id` must be...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newWatchlistScreeningIndividualGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string
	var bodyWatchlistScreeningId string

	cmd := &cobra.Command{
		Use:   "individual-get",
		Short: "Retrieve an individual watchlist screening",
		Example: "  plaid-cli watchlist-screening individual-get --watchlist-screening-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/individual/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWatchlistScreeningId != "" {
				body["watchlist_screening_id"] = bodyWatchlistScreeningId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWatchlistScreeningId, "watchlist-screening-id", "", "ID of the associated screening.")
	_ = cmd.MarkFlagRequired("watchlist-screening-id")

	return cmd
}

func newWatchlistScreeningIndividualHistoryListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCursor string
	var bodySecret string
	var bodyWatchlistScreeningId string

	cmd := &cobra.Command{
		Use:   "individual-history-list",
		Short: "List history for individual watchlist screenings",
		Example: "  plaid-cli watchlist-screening individual-history-list --watchlist-screening-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/individual/history/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWatchlistScreeningId != "" {
				body["watchlist_screening_id"] = bodyWatchlistScreeningId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "An identifier that determines which page of results you receive.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWatchlistScreeningId, "watchlist-screening-id", "", "ID of the associated screening.")
	_ = cmd.MarkFlagRequired("watchlist-screening-id")

	return cmd
}

func newWatchlistScreeningIndividualHitListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCursor string
	var bodySecret string
	var bodyWatchlistScreeningId string

	cmd := &cobra.Command{
		Use:   "individual-hit-list",
		Short: "List hits for individual watchlist screening",
		Example: "  plaid-cli watchlist-screening individual-hit-list --watchlist-screening-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/individual/hit/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWatchlistScreeningId != "" {
				body["watchlist_screening_id"] = bodyWatchlistScreeningId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "An identifier that determines which page of results you receive.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWatchlistScreeningId, "watchlist-screening-id", "", "ID of the associated screening.")
	_ = cmd.MarkFlagRequired("watchlist-screening-id")

	return cmd
}

func newWatchlistScreeningIndividualListCmd(flags *rootFlags) *cobra.Command {
	var bodyAssignee string
	var bodyClientId string
	var bodyClientUserId string
	var bodyCursor string
	var bodySecret string
	var bodyStatus string
	var bodyWatchlistProgramId string

	cmd := &cobra.Command{
		Use:   "individual-list",
		Short: "List Individual Watchlist Screenings",
		Example: "  plaid-cli watchlist-screening individual-list --watchlist-program-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/individual/list"
			body := map[string]any{}
			if bodyAssignee != "" {
				body["assignee"] = bodyAssignee
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStatus != "" {
				body["status"] = bodyStatus
			}
			if bodyWatchlistProgramId != "" {
				body["watchlist_program_id"] = bodyWatchlistProgramId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAssignee, "assignee", "", "ID of the associated user. To retrieve the email address or other details of the person corresponding to this id,...")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID that identifies the end user in your system. Either a `user_id` or the `client_user_id` must be...")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "An identifier that determines which page of results you receive.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "A status enum indicating whether a screening is still pending review, has been rejected, or has been cleared.")
	cmd.Flags().StringVar(&bodyWatchlistProgramId, "watchlist-program-id", "", "ID of the associated program.")
	_ = cmd.MarkFlagRequired("watchlist-program-id")

	return cmd
}

func newWatchlistScreeningIndividualProgramGetCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodySecret string
	var bodyWatchlistProgramId string

	cmd := &cobra.Command{
		Use:   "individual-program-get",
		Short: "Get individual watchlist screening program",
		Example: "  plaid-cli watchlist-screening individual-program-get --watchlist-program-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/individual/program/get"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWatchlistProgramId != "" {
				body["watchlist_program_id"] = bodyWatchlistProgramId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWatchlistProgramId, "watchlist-program-id", "", "ID of the associated program.")
	_ = cmd.MarkFlagRequired("watchlist-program-id")

	return cmd
}

func newWatchlistScreeningIndividualProgramListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCursor string
	var bodySecret string

	cmd := &cobra.Command{
		Use:   "individual-program-list",
		Short: "List individual watchlist screening programs",
		Example: "  plaid-cli watchlist-screening individual-program-list",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/individual/program/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "An identifier that determines which page of results you receive.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")

	return cmd
}

func newWatchlistScreeningIndividualReviewCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyComment string
	var bodySecret string
	var bodyWatchlistScreeningId string

	cmd := &cobra.Command{
		Use:   "individual-review-create",
		Short: "Create a review for an individual watchlist screening",
		Example: "  plaid-cli watchlist-screening individual-review-create --watchlist-screening-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/individual/review/create"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyComment != "" {
				body["comment"] = bodyComment
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWatchlistScreeningId != "" {
				body["watchlist_screening_id"] = bodyWatchlistScreeningId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyComment, "comment", "", "A comment submitted by a team member as part of reviewing a watchlist screening.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWatchlistScreeningId, "watchlist-screening-id", "", "ID of the associated screening.")
	_ = cmd.MarkFlagRequired("watchlist-screening-id")

	return cmd
}

func newWatchlistScreeningIndividualReviewListCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyCursor string
	var bodySecret string
	var bodyWatchlistScreeningId string

	cmd := &cobra.Command{
		Use:   "individual-review-list",
		Short: "List reviews for individual watchlist screenings",
		Example: "  plaid-cli watchlist-screening individual-review-list --watchlist-screening-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/individual/review/list"
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyCursor != "" {
				body["cursor"] = bodyCursor
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyWatchlistScreeningId != "" {
				body["watchlist_screening_id"] = bodyWatchlistScreeningId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyCursor, "cursor", "", "An identifier that determines which page of results you receive.")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyWatchlistScreeningId, "watchlist-screening-id", "", "ID of the associated screening.")
	_ = cmd.MarkFlagRequired("watchlist-screening-id")

	return cmd
}

func newWatchlistScreeningIndividualUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyAssignee string
	var bodyClientId string
	var bodyClientUserId string
	var bodySecret string
	var bodyStatus string
	var bodyWatchlistScreeningId string

	cmd := &cobra.Command{
		Use:   "individual-update",
		Short: "Update individual watchlist screening",
		Example: "  plaid-cli watchlist-screening individual-update --watchlist-screening-id value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/watchlist_screening/individual/update"
			body := map[string]any{}
			if bodyAssignee != "" {
				body["assignee"] = bodyAssignee
			}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientUserId != "" {
				body["client_user_id"] = bodyClientUserId
			}
			if bodySecret != "" {
				body["secret"] = bodySecret
			}
			if bodyStatus != "" {
				body["status"] = bodyStatus
			}
			if bodyWatchlistScreeningId != "" {
				body["watchlist_screening_id"] = bodyWatchlistScreeningId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAssignee, "assignee", "", "ID of the associated user. To retrieve the email address or other details of the person corresponding to this id,...")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "Your Plaid API `client_id`. The `client_id` is required and may be provided either in the `PLAID-CLIENT-ID` header...")
	cmd.Flags().StringVar(&bodyClientUserId, "client-user-id", "", "A unique ID that identifies the end user in your system. Either a `user_id` or the `client_user_id` must be...")
	cmd.Flags().StringVar(&bodySecret, "secret", "", "Your Plaid API `secret`. The `secret` is required and may be provided either in the `PLAID-SECRET` header or as part...")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "A status enum indicating whether a screening is still pending review, has been rejected, or has been cleared.")
	cmd.Flags().StringVar(&bodyWatchlistScreeningId, "watchlist-screening-id", "", "ID of the associated screening.")
	_ = cmd.MarkFlagRequired("watchlist-screening-id")

	return cmd
}

