// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newApplicationsActivityInstancesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "activity-instances",
		Short: "Manage activity instances",
	}

	cmd.AddCommand(newApplicationsActivityInstancesApplicationsGetCmd(flags))
	return cmd
}
