// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newApplicationsGuildsSetApplicationCommandPermissionsCmd(flags *rootFlags) *cobra.Command {
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "set-application-command-permissions <application_id> <guild_id> <command_id>",
		Short: "Set application command permissions",
		Example: "  discord-cli applications guilds set-application-command-permissions abc123 abc123 abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/applications/{application_id}/guilds/{guild_id}/commands/{command_id}/permissions"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("application_id is required"))
			}
			path = replacePathParam(path, "application_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("guild_id is required"))
			}
			path = replacePathParam(path, "guild_id", args[1])
			if len(args) < 3 {
				return usageErr(fmt.Errorf("command_id is required"))
			}
			path = replacePathParam(path, "command_id", args[2])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
			}
			data, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
