// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newApplicationsGetCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "get <application_id>",
		Short: "Get",
		Example: "  discord-cli applications get abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/applications/{application_id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("application_id is required"))
			}
			path = replacePathParam(path, "application_id", args[0])
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}
