// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newApplicationsUpdateMyCmd(flags *rootFlags) *cobra.Command {
	var bodyCoverImage string
	var bodyCustomInstallUrl string
	var bodyExplicitContentFilter string
	var bodyFlags int
	var bodyIcon string
	var bodyInstallParams string
	var bodyInteractionsEndpointUrl string
	var bodyMaxParticipants int
	var bodyRoleConnectionsVerificationUrl string
	var bodyTeamId string
	var bodyType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "update-my",
		Short: "Update my",
		Example: "  discord-cli applications update-my",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/applications/@me"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyCoverImage != "" {
					body["cover_image"] = bodyCoverImage
				}
				if bodyCustomInstallUrl != "" {
					body["custom_install_url"] = bodyCustomInstallUrl
				}
				if bodyExplicitContentFilter != "" {
					body["explicit_content_filter"] = bodyExplicitContentFilter
				}
				if bodyFlags != 0 {
					body["flags"] = bodyFlags
				}
				if bodyIcon != "" {
					body["icon"] = bodyIcon
				}
				if bodyInstallParams != "" {
					body["install_params"] = bodyInstallParams
				}
				if bodyInteractionsEndpointUrl != "" {
					body["interactions_endpoint_url"] = bodyInteractionsEndpointUrl
				}
				if bodyMaxParticipants != 0 {
					body["max_participants"] = bodyMaxParticipants
				}
				if bodyRoleConnectionsVerificationUrl != "" {
					body["role_connections_verification_url"] = bodyRoleConnectionsVerificationUrl
				}
				if bodyTeamId != "" {
					body["team_id"] = bodyTeamId
				}
				if bodyType != "" {
					body["type"] = bodyType
				}
			}
			data, err := c.Patch(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyCoverImage, "cover-image", "", "Cover image")
	cmd.Flags().StringVar(&bodyCustomInstallUrl, "custom-install-url", "", "Custom install url")
	cmd.Flags().StringVar(&bodyExplicitContentFilter, "explicit-content-filter", "", "Explicit content filter")
	cmd.Flags().IntVar(&bodyFlags, "flags", 0, "Flags")
	cmd.Flags().StringVar(&bodyIcon, "icon", "", "Icon")
	cmd.Flags().StringVar(&bodyInstallParams, "install-params", "", "Install params")
	cmd.Flags().StringVar(&bodyInteractionsEndpointUrl, "interactions-endpoint-url", "", "Interactions endpoint url")
	cmd.Flags().IntVar(&bodyMaxParticipants, "max-participants", 0, "Max participants")
	cmd.Flags().StringVar(&bodyRoleConnectionsVerificationUrl, "role-connections-verification-url", "", "Role connections verification url")
	cmd.Flags().StringVar(&bodyTeamId, "team-id", "", "Team id")
	cmd.Flags().StringVar(&bodyType, "type", "", "Type")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
