// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newApplicationsAttachmentCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "attachment",
		Short: "Manage attachment",
	}

	cmd.AddCommand(newApplicationsAttachmentUploadApplicationCmd(flags))
	return cmd
}
