// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newChannelsUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "users",
		Short: "Manage users",
	}

	cmd.AddCommand(newChannelsUsersListMyPrivateArchivedThreadsCmd(flags))
	return cmd
}
