// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newChannelsMessagesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "messages",
		Short: "Manage messages",
	}

	cmd.AddCommand(newChannelsMessagesAddMyReactionCmd(flags))
	cmd.AddCommand(newChannelsMessagesBulkDeleteCmd(flags))
	cmd.AddCommand(newChannelsMessagesCreateCmd(flags))
	cmd.AddCommand(newChannelsMessagesCreatePinCmd(flags))
	cmd.AddCommand(newChannelsMessagesCreateThreadFromCmd(flags))
	cmd.AddCommand(newChannelsMessagesCrosspostCmd(flags))
	cmd.AddCommand(newChannelsMessagesDeleteCmd(flags))
	cmd.AddCommand(newChannelsMessagesDeleteAllReactionsCmd(flags))
	cmd.AddCommand(newChannelsMessagesDeleteAllReactionsByEmojiCmd(flags))
	cmd.AddCommand(newChannelsMessagesDeleteMyReactionCmd(flags))
	cmd.AddCommand(newChannelsMessagesDeletePinCmd(flags))
	cmd.AddCommand(newChannelsMessagesDeleteUserReactionCmd(flags))
	cmd.AddCommand(newChannelsMessagesGetCmd(flags))
	cmd.AddCommand(newChannelsMessagesListCmd(flags))
	cmd.AddCommand(newChannelsMessagesListPinsCmd(flags))
	cmd.AddCommand(newChannelsMessagesListReactionsByEmojiCmd(flags))
	cmd.AddCommand(newChannelsMessagesUpdateCmd(flags))
	return cmd
}
