// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newChannelsRecipientsDeleteGroupDmUserCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "delete-group-dm-user <channel_id> <user_id>",
		Aliases: []string{"delete"},
		Short: "Delete group dm user",
		Example: "  discord-cli channels recipients delete-group-dm-user abc123 abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/channels/{channel_id}/recipients/{user_id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("channel_id is required"))
			}
			path = replacePathParam(path, "channel_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("user_id is required"))
			}
			path = replacePathParam(path, "user_id", args[1])
			data, err := c.Delete(path)
			if err != nil {
				return classifyDeleteError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}
