// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newChannelsPollsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "polls",
		Short: "Manage polls",
	}

	cmd.AddCommand(newChannelsPollsExpireCmd(flags))
	cmd.AddCommand(newChannelsPollsGetAnswerVotersCmd(flags))
	return cmd
}
