// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newChannelsThreadsListPrivateArchivedCmd(flags *rootFlags) *cobra.Command {
	var flagBefore string
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "list-private-archived <channel_id>",
		Aliases: []string{"get"},
		Short: "List private archived",
		Example: "  discord-cli channels threads list-private-archived abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/channels/{channel_id}/threads/archived/private"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("channel_id is required"))
			}
			path = replacePathParam(path, "channel_id", args[0])
			data, err := paginatedGet(c, path, map[string]string{
				"before": fmt.Sprintf("%v", flagBefore),
				"limit": fmt.Sprintf("%v", flagLimit),
			}, flagAll, "", "", "has_more")
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagBefore, "before", "", "Before")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Limit")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
