// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newChannelsFollowersFollowChannelCmd(flags *rootFlags) *cobra.Command {
	var bodyWebhookChannelId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "follow-channel <channel_id>",
		Aliases: []string{"create"},
		Short: "Follow channel",
		Example: "  discord-cli channels followers follow-channel abc123 --webhook-channel-id abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/channels/{channel_id}/followers"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("channel_id is required"))
			}
			path = replacePathParam(path, "channel_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyWebhookChannelId != "" {
					body["webhook_channel_id"] = bodyWebhookChannelId
				}
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyWebhookChannelId, "webhook-channel-id", "", "Webhook channel id")
	_ = cmd.MarkFlagRequired("webhook-channel-id")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
