// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGatewayCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "gateway",
		Short: "Manage gateway",
	}

	cmd.AddCommand(newGatewayGetCmd(flags))
	cmd.AddCommand(newGatewayGetBotCmd(flags))
	return cmd
}
