// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newGuildsOnboardingPutGuildsCmd(flags *rootFlags) *cobra.Command {
	var bodyEnabled bool
	var bodyMode string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "put-guilds <guild_id>",
		Aliases: []string{"update"},
		Short: "Put guilds",
		Example: "  discord-cli guilds onboarding put-guilds abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/guilds/{guild_id}/onboarding"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("guild_id is required"))
			}
			path = replacePathParam(path, "guild_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyEnabled != false {
					body["enabled"] = bodyEnabled
				}
				if bodyMode != "" {
					body["mode"] = bodyMode
				}
			}
			data, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().BoolVar(&bodyEnabled, "enabled", false, "Enabled")
	cmd.Flags().StringVar(&bodyMode, "mode", "", "Mode")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
