// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGuildsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "guilds",
		Short: "Manage Discord guilds (servers) - members, roles, bans, channels, audit logs, and more",
	}

	cmd.AddCommand(newGuildsGetCmd(flags))
	cmd.AddCommand(newGuildsGetTemplateCmd(flags))
	cmd.AddCommand(newGuildsUpdateCmd(flags))
	cmd.AddCommand(newGuildsAuditLogsCmd(flags))
	cmd.AddCommand(newGuildsAutoModerationCmd(flags))
	cmd.AddCommand(newGuildsBansCmd(flags))
	cmd.AddCommand(newGuildsBulkBanCmd(flags))
	cmd.AddCommand(newGuildsChannelsCmd(flags))
	cmd.AddCommand(newGuildsEmojisCmd(flags))
	cmd.AddCommand(newGuildsIntegrationsCmd(flags))
	cmd.AddCommand(newGuildsInvitesCmd(flags))
	cmd.AddCommand(newGuildsMembersCmd(flags))
	cmd.AddCommand(newGuildsMessagesCmd(flags))
	cmd.AddCommand(newGuildsNewMemberWelcomeCmd(flags))
	cmd.AddCommand(newGuildsOnboardingCmd(flags))
	cmd.AddCommand(newGuildsPreviewCmd(flags))
	cmd.AddCommand(newGuildsPruneCmd(flags))
	cmd.AddCommand(newGuildsRegionsCmd(flags))
	cmd.AddCommand(newGuildsRolesCmd(flags))
	cmd.AddCommand(newGuildsScheduledEventsCmd(flags))
	cmd.AddCommand(newGuildsSoundboardSoundsCmd(flags))
	cmd.AddCommand(newGuildsStickersCmd(flags))
	cmd.AddCommand(newGuildsTemplatesCmd(flags))
	cmd.AddCommand(newGuildsThreadsCmd(flags))
	cmd.AddCommand(newGuildsVanityUrlCmd(flags))
	cmd.AddCommand(newGuildsVoiceStatesCmd(flags))
	cmd.AddCommand(newGuildsWebhooksCmd(flags))
	cmd.AddCommand(newGuildsWelcomeScreenCmd(flags))
	cmd.AddCommand(newGuildsWidgetCmd(flags))
	cmd.AddCommand(newGuildsWidgetJsonCmd(flags))
	cmd.AddCommand(newGuildsWidgetPngCmd(flags))
	return cmd
}
