// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newGuildsMembersListGuildCmd(flags *rootFlags) *cobra.Command {
	var flagLimit int
	var flagAfter int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "list-guild <guild_id>",
		Short: "List guild",
		Example: "  discord-cli guilds members list-guild abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/guilds/{guild_id}/members"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("guild_id is required"))
			}
			path = replacePathParam(path, "guild_id", args[0])
			data, err := paginatedGet(c, path, map[string]string{
				"limit": fmt.Sprintf("%v", flagLimit),
				"after": fmt.Sprintf("%v", flagAfter),
			}, flagAll, "after", "", "")
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Limit")
	cmd.Flags().IntVar(&flagAfter, "after", 0, "After")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
