// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGuildsThreadsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "threads",
		Short: "Manage threads",
	}

	cmd.AddCommand(newGuildsThreadsGetActiveGuildCmd(flags))
	return cmd
}
