// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGuildsPruneCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "prune",
		Short: "Manage prune",
	}

	cmd.AddCommand(newGuildsPruneGuildCmd(flags))
	cmd.AddCommand(newGuildsPrunePreviewGuildCmd(flags))
	return cmd
}
