// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newGuildsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyAfkChannelId string
	var bodyAfkTimeout string
	var bodyBanner string
	var bodyDefaultMessageNotifications string
	var bodyDescription string
	var bodyDiscoverySplash string
	var bodyExplicitContentFilter string
	var bodyHomeHeader string
	var bodyIcon string
	var bodyName string
	var bodyPreferredLocale string
	var bodyPremiumProgressBarEnabled bool
	var bodyPublicUpdatesChannelId string
	var bodyRegion string
	var bodyRulesChannelId string
	var bodySafetyAlertsChannelId string
	var bodySplash string
	var bodySystemChannelFlags int
	var bodySystemChannelId string
	var bodyVerificationLevel string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "update <guild_id>",
		Short: "Update",
		Example: "  discord-cli guilds update abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/guilds/{guild_id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("guild_id is required"))
			}
			path = replacePathParam(path, "guild_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAfkChannelId != "" {
					body["afk_channel_id"] = bodyAfkChannelId
				}
				if bodyAfkTimeout != "" {
					body["afk_timeout"] = bodyAfkTimeout
				}
				if bodyBanner != "" {
					body["banner"] = bodyBanner
				}
				if bodyDefaultMessageNotifications != "" {
					body["default_message_notifications"] = bodyDefaultMessageNotifications
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyDiscoverySplash != "" {
					body["discovery_splash"] = bodyDiscoverySplash
				}
				if bodyExplicitContentFilter != "" {
					body["explicit_content_filter"] = bodyExplicitContentFilter
				}
				if bodyHomeHeader != "" {
					body["home_header"] = bodyHomeHeader
				}
				if bodyIcon != "" {
					body["icon"] = bodyIcon
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyPreferredLocale != "" {
					body["preferred_locale"] = bodyPreferredLocale
				}
				if bodyPremiumProgressBarEnabled != false {
					body["premium_progress_bar_enabled"] = bodyPremiumProgressBarEnabled
				}
				if bodyPublicUpdatesChannelId != "" {
					body["public_updates_channel_id"] = bodyPublicUpdatesChannelId
				}
				if bodyRegion != "" {
					body["region"] = bodyRegion
				}
				if bodyRulesChannelId != "" {
					body["rules_channel_id"] = bodyRulesChannelId
				}
				if bodySafetyAlertsChannelId != "" {
					body["safety_alerts_channel_id"] = bodySafetyAlertsChannelId
				}
				if bodySplash != "" {
					body["splash"] = bodySplash
				}
				if bodySystemChannelFlags != 0 {
					body["system_channel_flags"] = bodySystemChannelFlags
				}
				if bodySystemChannelId != "" {
					body["system_channel_id"] = bodySystemChannelId
				}
				if bodyVerificationLevel != "" {
					body["verification_level"] = bodyVerificationLevel
				}
			}
			data, err := c.Patch(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAfkChannelId, "afk-channel-id", "", "Afk channel id")
	cmd.Flags().StringVar(&bodyAfkTimeout, "afk-timeout", "", "Afk timeout")
	cmd.Flags().StringVar(&bodyBanner, "banner", "", "Banner")
	cmd.Flags().StringVar(&bodyDefaultMessageNotifications, "default-message-notifications", "", "Default message notifications")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Description")
	cmd.Flags().StringVar(&bodyDiscoverySplash, "discovery-splash", "", "Discovery splash")
	cmd.Flags().StringVar(&bodyExplicitContentFilter, "explicit-content-filter", "", "Explicit content filter")
	cmd.Flags().StringVar(&bodyHomeHeader, "home-header", "", "Home header")
	cmd.Flags().StringVar(&bodyIcon, "icon", "", "Icon")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name")
	cmd.Flags().StringVar(&bodyPreferredLocale, "preferred-locale", "", "Preferred locale")
	cmd.Flags().BoolVar(&bodyPremiumProgressBarEnabled, "premium-progress-bar-enabled", false, "Premium progress bar enabled")
	cmd.Flags().StringVar(&bodyPublicUpdatesChannelId, "public-updates-channel-id", "", "Public updates channel id")
	cmd.Flags().StringVar(&bodyRegion, "region", "", "Region")
	cmd.Flags().StringVar(&bodyRulesChannelId, "rules-channel-id", "", "Rules channel id")
	cmd.Flags().StringVar(&bodySafetyAlertsChannelId, "safety-alerts-channel-id", "", "Safety alerts channel id")
	cmd.Flags().StringVar(&bodySplash, "splash", "", "Splash")
	cmd.Flags().IntVar(&bodySystemChannelFlags, "system-channel-flags", 0, "System channel flags")
	cmd.Flags().StringVar(&bodySystemChannelId, "system-channel-id", "", "System channel id")
	cmd.Flags().StringVar(&bodyVerificationLevel, "verification-level", "", "Verification level")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
