// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newGuildsWidgetPngGetGuildCmd(flags *rootFlags) *cobra.Command {
	var flagStyle string

	cmd := &cobra.Command{
		Use:   "get-guild <guild_id>",
		Aliases: []string{"get"},
		Short: "Get guild",
		Example: "  discord-cli guilds widget-png get-guild abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/guilds/{guild_id}/widget.png"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("guild_id is required"))
			}
			path = replacePathParam(path, "guild_id", args[0])
			params := map[string]string{}
			if flagStyle != "" {
				params["style"] = fmt.Sprintf("%v", flagStyle)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagStyle, "style", "", "Style")

	return cmd
}
