// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newGuildsScheduledEventsListGuildUsersCmd(flags *rootFlags) *cobra.Command {
	var flagWithMember bool
	var flagLimit int
	var flagBefore string
	var flagAfter string
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "list-guild-users <guild_id> <guild_scheduled_event_id>",
		Short: "List guild users",
		Example: "  discord-cli guilds scheduled-events list-guild-users abc123 abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/guilds/{guild_id}/scheduled-events/{guild_scheduled_event_id}/users"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("guild_id is required"))
			}
			path = replacePathParam(path, "guild_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("guild_scheduled_event_id is required"))
			}
			path = replacePathParam(path, "guild_scheduled_event_id", args[1])
			data, err := paginatedGet(c, path, map[string]string{
				"with_member": fmt.Sprintf("%v", flagWithMember),
				"limit": fmt.Sprintf("%v", flagLimit),
				"before": fmt.Sprintf("%v", flagBefore),
				"after": fmt.Sprintf("%v", flagAfter),
			}, flagAll, "after", "", "")
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().BoolVar(&flagWithMember, "with-member", false, "With member")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Limit")
	cmd.Flags().StringVar(&flagBefore, "before", "", "Before")
	cmd.Flags().StringVar(&flagAfter, "after", "", "After")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
