// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGuildsVoiceStatesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "voice-states",
		Short: "Manage voice states",
	}

	cmd.AddCommand(newGuildsVoiceStatesGetCmd(flags))
	cmd.AddCommand(newGuildsVoiceStatesGetSelfCmd(flags))
	cmd.AddCommand(newGuildsVoiceStatesUpdateCmd(flags))
	cmd.AddCommand(newGuildsVoiceStatesUpdateSelfCmd(flags))
	return cmd
}
