// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGuildsBulkBanCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "bulk-ban",
		Short: "Manage bulk ban",
	}

	cmd.AddCommand(newGuildsBulkBanUsersFromGuildCmd(flags))
	return cmd
}
