// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGuildsEmojisCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "emojis",
		Short: "Manage emojis",
	}

	cmd.AddCommand(newGuildsEmojisCreateGuildCmd(flags))
	cmd.AddCommand(newGuildsEmojisDeleteGuildCmd(flags))
	cmd.AddCommand(newGuildsEmojisGetGuildCmd(flags))
	cmd.AddCommand(newGuildsEmojisListGuildCmd(flags))
	cmd.AddCommand(newGuildsEmojisUpdateGuildCmd(flags))
	return cmd
}
