// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGuildsAuditLogsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "audit-logs",
		Short: "Manage audit logs",
	}

	cmd.AddCommand(newGuildsAuditLogsListGuildEntriesCmd(flags))
	return cmd
}
