// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newInteractionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "interactions",
		Short: "Manage interactions",
	}

	cmd.AddCommand(newInteractionsCallbackCmd(flags))
	return cmd
}
