// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newInteractionsCallbackCreateInteractionResponseCmd(flags *rootFlags) *cobra.Command {
	var flagWithResponse bool
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "create-interaction-response <interaction_id> <interaction_token>",
		Aliases: []string{"create"},
		Short: "Create interaction response",
		Example: "  discord-cli interactions callback create-interaction-response abc123 value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/interactions/{interaction_id}/{interaction_token}/callback"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("interaction_id is required"))
			}
			path = replacePathParam(path, "interaction_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("interaction_token is required"))
			}
			path = replacePathParam(path, "interaction_token", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().BoolVar(&flagWithResponse, "with-response", false, "With response")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
