// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newInteractionsCallbackCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "callback",
		Short: "Manage callback",
	}

	cmd.AddCommand(newInteractionsCallbackCreateInteractionResponseCmd(flags))
	return cmd
}
