// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newLobbiesMembersAddLobbyCmd(flags *rootFlags) *cobra.Command {
	var bodyFlags string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "add-lobby <lobby_id> <user_id>",
		Aliases: []string{"update"},
		Short: "Add lobby",
		Example: "  discord-cli lobbies members add-lobby abc123 abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/lobbies/{lobby_id}/members/{user_id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("lobby_id is required"))
			}
			path = replacePathParam(path, "lobby_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("user_id is required"))
			}
			path = replacePathParam(path, "user_id", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyFlags != "" {
					body["flags"] = bodyFlags
				}
			}
			data, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyFlags, "flags", "", "Flags")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
