// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOauth2Cmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "oauth2",
		Short: "Manage oauth2",
	}

	cmd.AddCommand(newOauth2GetMyApplicationCmd(flags))
	cmd.AddCommand(newOauth2GetMyAuthorizationCmd(flags))
	cmd.AddCommand(newOauth2GetOpenidConnectUserinfoCmd(flags))
	cmd.AddCommand(newOauth2GetPublicKeysCmd(flags))
	return cmd
}
