// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPartnerSdkCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "partner-sdk",
		Short: "Manage partner sdk",
	}

	cmd.AddCommand(newPartnerSdkBotTokenCmd(flags))
	cmd.AddCommand(newPartnerSdkBotUnmergeProvisionalAccountCmd(flags))
	cmd.AddCommand(newPartnerSdkTokenCmd(flags))
	cmd.AddCommand(newPartnerSdkUnmergeProvisionalAccountCmd(flags))
	cmd.AddCommand(newPartnerSdkUpdateUserMessageExternalModerationMetadataCmd(flags))
	return cmd
}
