// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSoundboardDefaultSoundsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "soundboard-default-sounds",
		Short: "Manage soundboard default sounds",
	}

	cmd.AddCommand(newSoundboardDefaultSoundsGetCmd(flags))
	return cmd
}
