// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newUsersGetCurrentApplicationEntitlementsCmd(flags *rootFlags) *cobra.Command {
	var flagSkuIds string
	var flagExcludeConsumed bool

	cmd := &cobra.Command{
		Use:   "get-current-application-entitlements <application_id>",
		Short: "Get current application entitlements",
		Example: "  discord-cli users get-current-application-entitlements abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/users/@me/applications/{application_id}/entitlements"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("application_id is required"))
			}
			path = replacePathParam(path, "application_id", args[0])
			params := map[string]string{}
			if flagSkuIds != "" {
				params["sku_ids"] = fmt.Sprintf("%v", flagSkuIds)
			}
			if flagExcludeConsumed != false {
				params["exclude_consumed"] = fmt.Sprintf("%v", flagExcludeConsumed)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagSkuIds, "sku-ids", "", "Sku ids")
	cmd.Flags().BoolVar(&flagExcludeConsumed, "exclude-consumed", false, "Exclude consumed")

	return cmd
}
