// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newUsersUpdateApplicationRoleConnectionCmd(flags *rootFlags) *cobra.Command {
	var bodyPlatformName string
	var bodyPlatformUsername string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "update-application-role-connection <application_id>",
		Aliases: []string{"update"},
		Short: "Update application role connection",
		Example: "  discord-cli users update-application-role-connection abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/users/@me/applications/{application_id}/role-connection"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("application_id is required"))
			}
			path = replacePathParam(path, "application_id", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyPlatformName != "" {
					body["platform_name"] = bodyPlatformName
				}
				if bodyPlatformUsername != "" {
					body["platform_username"] = bodyPlatformUsername
				}
			}
			data, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyPlatformName, "platform-name", "", "Platform name")
	cmd.Flags().StringVar(&bodyPlatformUsername, "platform-username", "", "Platform username")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
