// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newVoiceCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "voice",
		Short: "Manage voice",
	}

	cmd.AddCommand(newVoiceListRegionsCmd(flags))
	return cmd
}
