// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newWebhooksUpdateByTokenCmd(flags *rootFlags) *cobra.Command {
	var bodyAvatar string
	var bodyName string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "update-by-token <webhook_id> <webhook_token>",
		Short: "Update by token",
		Example: "  discord-cli webhooks update-by-token abc123 value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/webhooks/{webhook_id}/{webhook_token}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("webhook_id is required"))
			}
			path = replacePathParam(path, "webhook_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("webhook_token is required"))
			}
			path = replacePathParam(path, "webhook_token", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAvatar != "" {
					body["avatar"] = bodyAvatar
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
			}
			data, err := c.Patch(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyAvatar, "avatar", "", "Avatar")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
