// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newWebhooksGithubExecuteCompatibleWebhookCmd(flags *rootFlags) *cobra.Command {
	var flagWait bool
	var flagThreadId string
	var bodyAction string
	var bodyAnswer string
	var bodyCheckRun string
	var bodyCheckSuite string
	var bodyComment string
	var bodyCompare string
	var bodyDiscussion string
	var bodyForced bool
	var bodyForkee string
	var bodyHeadCommit string
	var bodyIssue string
	var bodyMember string
	var bodyPullRequest string
	var bodyRef string
	var bodyRefType string
	var bodyRelease string
	var bodyRepository string
	var bodyReview string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "execute-compatible-webhook <webhook_id> <webhook_token>",
		Aliases: []string{"create"},
		Short: "Execute compatible webhook",
		Example: "  discord-cli webhooks github execute-compatible-webhook abc123 value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/webhooks/{webhook_id}/{webhook_token}/github"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("webhook_id is required"))
			}
			path = replacePathParam(path, "webhook_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("webhook_token is required"))
			}
			path = replacePathParam(path, "webhook_token", args[1])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAction != "" {
					body["action"] = bodyAction
				}
				if bodyAnswer != "" {
					body["answer"] = bodyAnswer
				}
				if bodyCheckRun != "" {
					body["check_run"] = bodyCheckRun
				}
				if bodyCheckSuite != "" {
					body["check_suite"] = bodyCheckSuite
				}
				if bodyComment != "" {
					body["comment"] = bodyComment
				}
				if bodyCompare != "" {
					body["compare"] = bodyCompare
				}
				if bodyDiscussion != "" {
					body["discussion"] = bodyDiscussion
				}
				if bodyForced != false {
					body["forced"] = bodyForced
				}
				if bodyForkee != "" {
					body["forkee"] = bodyForkee
				}
				if bodyHeadCommit != "" {
					body["head_commit"] = bodyHeadCommit
				}
				if bodyIssue != "" {
					body["issue"] = bodyIssue
				}
				if bodyMember != "" {
					body["member"] = bodyMember
				}
				if bodyPullRequest != "" {
					body["pull_request"] = bodyPullRequest
				}
				if bodyRef != "" {
					body["ref"] = bodyRef
				}
				if bodyRefType != "" {
					body["ref_type"] = bodyRefType
				}
				if bodyRelease != "" {
					body["release"] = bodyRelease
				}
				if bodyRepository != "" {
					body["repository"] = bodyRepository
				}
				if bodyReview != "" {
					body["review"] = bodyReview
				}
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().BoolVar(&flagWait, "wait", false, "Wait")
	cmd.Flags().StringVar(&flagThreadId, "thread-id", "", "Thread id")
	cmd.Flags().StringVar(&bodyAction, "action", "", "Action")
	cmd.Flags().StringVar(&bodyAnswer, "answer", "", "Answer")
	cmd.Flags().StringVar(&bodyCheckRun, "check-run", "", "Check run")
	cmd.Flags().StringVar(&bodyCheckSuite, "check-suite", "", "Check suite")
	cmd.Flags().StringVar(&bodyComment, "comment", "", "Comment")
	cmd.Flags().StringVar(&bodyCompare, "compare", "", "Compare")
	cmd.Flags().StringVar(&bodyDiscussion, "discussion", "", "Discussion")
	cmd.Flags().BoolVar(&bodyForced, "forced", false, "Forced")
	cmd.Flags().StringVar(&bodyForkee, "forkee", "", "Forkee")
	cmd.Flags().StringVar(&bodyHeadCommit, "head-commit", "", "Head commit")
	cmd.Flags().StringVar(&bodyIssue, "issue", "", "Issue")
	cmd.Flags().StringVar(&bodyMember, "member", "", "Member")
	cmd.Flags().StringVar(&bodyPullRequest, "pull-request", "", "Pull request")
	cmd.Flags().StringVar(&bodyRef, "ref", "", "Ref")
	cmd.Flags().StringVar(&bodyRefType, "ref-type", "", "Ref type")
	cmd.Flags().StringVar(&bodyRelease, "release", "", "Release")
	cmd.Flags().StringVar(&bodyRepository, "repository", "", "Repository")
	cmd.Flags().StringVar(&bodyReview, "review", "", "Review")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
