// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWebhooksMessagesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "messages",
		Short: "Manage messages",
	}

	cmd.AddCommand(newWebhooksMessagesDeleteOriginalWebhookCmd(flags))
	cmd.AddCommand(newWebhooksMessagesDeleteWebhookCmd(flags))
	cmd.AddCommand(newWebhooksMessagesGetOriginalWebhookCmd(flags))
	cmd.AddCommand(newWebhooksMessagesGetWebhookCmd(flags))
	cmd.AddCommand(newWebhooksMessagesUpdateOriginalWebhookCmd(flags))
	cmd.AddCommand(newWebhooksMessagesUpdateWebhookCmd(flags))
	return cmd
}
