// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import
var _ = io.ReadAll         // ensure import
var _ = os.Stdin           // ensure import
var _ json.RawMessage      // ensure import

func newWebhooksDeleteCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "delete <webhook_id>",
		Short: "Delete",
		Example: "  discord-cli webhooks delete abc123",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/webhooks/{webhook_id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("webhook_id is required"))
			}
			path = replacePathParam(path, "webhook_id", args[0])
			data, err := c.Delete(path)
			if err != nil {
				return classifyDeleteError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}
