// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newDealsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "deals",
		Short: "Deals represent ongoing, lost or won sales to an organization or to a person. Each deal has a monetary value and...",
	}

	cmd.AddCommand(newDealsGetArchivedCmd(flags))
	cmd.AddCommand(newDealsGetArchivedSummaryCmd(flags))
	cmd.AddCommand(newDealsGetArchivedTimelineCmd(flags))
	cmd.AddCommand(newDealsGetSummaryCmd(flags))
	cmd.AddCommand(newDealsGetTimelineCmd(flags))
	cmd.AddCommand(newDealsChangelogCmd(flags))
	cmd.AddCommand(newDealsDuplicateCmd(flags))
	cmd.AddCommand(newDealsFilesCmd(flags))
	cmd.AddCommand(newDealsFlowCmd(flags))
	cmd.AddCommand(newDealsFollowersCmd(flags))
	cmd.AddCommand(newDealsMailMessagesCmd(flags))
	cmd.AddCommand(newDealsMergeCmd(flags))
	cmd.AddCommand(newDealsParticipantsCmd(flags))
	cmd.AddCommand(newDealsParticipantsChangelogCmd(flags))
	cmd.AddCommand(newDealsPermittedUsersCmd(flags))
	return cmd
}

func newDealsGetArchivedCmd(flags *rootFlags) *cobra.Command {
	var flagUserId int
	var flagFilterId int
	var flagPersonId int
	var flagOrgId int
	var flagProductId int
	var flagPipelineId int
	var flagStageId int
	var flagStatus string
	var flagStart int
	var flagLimit int
	var flagSort string
	var flagOwnedByYou float64
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "get-archived",
		Aliases: []string{"list"},
		Short: "Get all archived deals",
		Example: "  pipedrive-cli deals get-archived",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/deals/archived"
			data, err := paginatedGet(c, path, map[string]string{
				"user_id": fmt.Sprintf("%v", flagUserId),
				"filter_id": fmt.Sprintf("%v", flagFilterId),
				"person_id": fmt.Sprintf("%v", flagPersonId),
				"org_id": fmt.Sprintf("%v", flagOrgId),
				"product_id": fmt.Sprintf("%v", flagProductId),
				"pipeline_id": fmt.Sprintf("%v", flagPipelineId),
				"stage_id": fmt.Sprintf("%v", flagStageId),
				"status": fmt.Sprintf("%v", flagStatus),
				"start": fmt.Sprintf("%v", flagStart),
				"limit": fmt.Sprintf("%v", flagLimit),
				"sort": fmt.Sprintf("%v", flagSort),
				"owned_by_you": fmt.Sprintf("%v", flagOwnedByYou),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&flagUserId, "user-id", 0, "If supplied, only deals matching the given user will be returned. However, `filter_id` and `owned_by_you` takes...")
	cmd.Flags().IntVar(&flagFilterId, "filter-id", 0, "The ID of the filter to use")
	cmd.Flags().IntVar(&flagPersonId, "person-id", 0, "If supplied, only deals linked to the specified person are returned. If filter_id is provided, this is ignored.")
	cmd.Flags().IntVar(&flagOrgId, "org-id", 0, "If supplied, only deals linked to the specified organization are returned. If filter_id is provided, this is ignored.")
	cmd.Flags().IntVar(&flagProductId, "product-id", 0, "If supplied, only deals linked to the specified product are returned. If filter_id is provided, this is ignored.")
	cmd.Flags().IntVar(&flagPipelineId, "pipeline-id", 0, "If supplied, only deals in the specified pipeline are returned. If filter_id is provided, this is ignored.")
	cmd.Flags().IntVar(&flagStageId, "stage-id", 0, "If supplied, only deals in the specified stage are returned. If filter_id is provided, this is ignored.")
	cmd.Flags().StringVar(&flagStatus, "status", "all_not_deleted", "Only fetch deals with a specific status. If omitted, all not deleted deals are returned. If set to deleted, deals...")
	cmd.Flags().IntVar(&flagStart, "start", 0, "Pagination start")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Items shown per page")
	cmd.Flags().StringVar(&flagSort, "sort", "", "The field names and sorting mode separated by a comma (`field_name_1 ASC`, `field_name_2 DESC`). Only first-level...")
	cmd.Flags().Float64Var(&flagOwnedByYou, "owned-by-you", 0.0, "When supplied, only deals owned by you are returned. However, `filter_id` takes precedence over `owned_by_you` when...")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}

func newDealsGetArchivedSummaryCmd(flags *rootFlags) *cobra.Command {
	var flagStatus string
	var flagFilterId int
	var flagUserId int
	var flagPipelineId int
	var flagStageId int

	cmd := &cobra.Command{
		Use:   "get-archived-summary",
		Short: "Get archived deals summary",
		Example: "  pipedrive-cli deals get-archived-summary",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/deals/summary/archived"
			params := map[string]string{}
			if flagStatus != "" {
				params["status"] = fmt.Sprintf("%v", flagStatus)
			}
			if flagFilterId != 0 {
				params["filter_id"] = fmt.Sprintf("%v", flagFilterId)
			}
			if flagUserId != 0 {
				params["user_id"] = fmt.Sprintf("%v", flagUserId)
			}
			if flagPipelineId != 0 {
				params["pipeline_id"] = fmt.Sprintf("%v", flagPipelineId)
			}
			if flagStageId != 0 {
				params["stage_id"] = fmt.Sprintf("%v", flagStageId)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagStatus, "status", "", "Only fetch deals with a specific status. open = Open, won = Won, lost = Lost.")
	cmd.Flags().IntVar(&flagFilterId, "filter-id", 0, "<code>user_id</code> will not be considered. Only deals matching the given filter will be returned.")
	cmd.Flags().IntVar(&flagUserId, "user-id", 0, "Only deals matching the given user will be returned. `user_id` will not be considered if you use `filter_id`.")
	cmd.Flags().IntVar(&flagPipelineId, "pipeline-id", 0, "Only deals within the given pipeline will be returned")
	cmd.Flags().IntVar(&flagStageId, "stage-id", 0, "Only deals within the given stage will be returned")

	return cmd
}

func newDealsGetArchivedTimelineCmd(flags *rootFlags) *cobra.Command {
	var flagStartDate string
	var flagInterval string
	var flagAmount int
	var flagFieldKey string
	var flagUserId int
	var flagPipelineId int
	var flagFilterId int
	var flagExcludeDeals float64
	var flagTotalsConvertCurrency string

	cmd := &cobra.Command{
		Use:   "get-archived-timeline",
		Short: "Get archived deals timeline",
		Example: "  pipedrive-cli deals get-archived-timeline",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/deals/timeline/archived"
			params := map[string]string{}
			if flagStartDate != "" {
				params["start_date"] = fmt.Sprintf("%v", flagStartDate)
			}
			if flagInterval != "" {
				params["interval"] = fmt.Sprintf("%v", flagInterval)
			}
			if flagAmount != 0 {
				params["amount"] = fmt.Sprintf("%v", flagAmount)
			}
			if flagFieldKey != "" {
				params["field_key"] = fmt.Sprintf("%v", flagFieldKey)
			}
			if flagUserId != 0 {
				params["user_id"] = fmt.Sprintf("%v", flagUserId)
			}
			if flagPipelineId != 0 {
				params["pipeline_id"] = fmt.Sprintf("%v", flagPipelineId)
			}
			if flagFilterId != 0 {
				params["filter_id"] = fmt.Sprintf("%v", flagFilterId)
			}
			if flagExcludeDeals != 0.0 {
				params["exclude_deals"] = fmt.Sprintf("%v", flagExcludeDeals)
			}
			if flagTotalsConvertCurrency != "" {
				params["totals_convert_currency"] = fmt.Sprintf("%v", flagTotalsConvertCurrency)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "The date when the first interval starts. Format: YYYY-MM-DD.")
	_ = cmd.MarkFlagRequired("start-date")
	cmd.Flags().StringVar(&flagInterval, "interval", "", "The type of the interval<table><tr><th>Value</th><th>Description</th></tr><tr><td>`day`</td><td>Day</td></tr><tr><td>...")
	_ = cmd.MarkFlagRequired("interval")
	cmd.Flags().IntVar(&flagAmount, "amount", 0, "The number of given intervals, starting from `start_date`, to fetch. E.g. 3 (months).")
	_ = cmd.MarkFlagRequired("amount")
	cmd.Flags().StringVar(&flagFieldKey, "field-key", "", "The date field key which deals will be retrieved from")
	_ = cmd.MarkFlagRequired("field-key")
	cmd.Flags().IntVar(&flagUserId, "user-id", 0, "If supplied, only deals matching the given user will be returned")
	cmd.Flags().IntVar(&flagPipelineId, "pipeline-id", 0, "If supplied, only deals matching the given pipeline will be returned")
	cmd.Flags().IntVar(&flagFilterId, "filter-id", 0, "If supplied, only deals matching the given filter will be returned")
	cmd.Flags().Float64Var(&flagExcludeDeals, "exclude-deals", 0.0, "Whether to exclude deals list (1) or not (0). Note that when deals are excluded, the timeline summary (counts and...")
	cmd.Flags().StringVar(&flagTotalsConvertCurrency, "totals-convert-currency", "", "The 3-letter currency code of any of the supported currencies. When supplied, `totals_converted` is returned per...")

	return cmd
}

func newDealsGetSummaryCmd(flags *rootFlags) *cobra.Command {
	var flagStatus string
	var flagFilterId int
	var flagUserId int
	var flagPipelineId int
	var flagStageId int

	cmd := &cobra.Command{
		Use:   "get-summary",
		Short: "Get deals summary",
		Example: "  pipedrive-cli deals get-summary",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/deals/summary"
			params := map[string]string{}
			if flagStatus != "" {
				params["status"] = fmt.Sprintf("%v", flagStatus)
			}
			if flagFilterId != 0 {
				params["filter_id"] = fmt.Sprintf("%v", flagFilterId)
			}
			if flagUserId != 0 {
				params["user_id"] = fmt.Sprintf("%v", flagUserId)
			}
			if flagPipelineId != 0 {
				params["pipeline_id"] = fmt.Sprintf("%v", flagPipelineId)
			}
			if flagStageId != 0 {
				params["stage_id"] = fmt.Sprintf("%v", flagStageId)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagStatus, "status", "", "Only fetch deals with a specific status. open = Open, won = Won, lost = Lost.")
	cmd.Flags().IntVar(&flagFilterId, "filter-id", 0, "<code>user_id</code> will not be considered. Only deals matching the given filter will be returned.")
	cmd.Flags().IntVar(&flagUserId, "user-id", 0, "Only deals matching the given user will be returned. `user_id` will not be considered if you use `filter_id`.")
	cmd.Flags().IntVar(&flagPipelineId, "pipeline-id", 0, "Only deals within the given pipeline will be returned")
	cmd.Flags().IntVar(&flagStageId, "stage-id", 0, "Only deals within the given stage will be returned")

	return cmd
}

func newDealsGetTimelineCmd(flags *rootFlags) *cobra.Command {
	var flagStartDate string
	var flagInterval string
	var flagAmount int
	var flagFieldKey string
	var flagUserId int
	var flagPipelineId int
	var flagFilterId int
	var flagExcludeDeals float64
	var flagTotalsConvertCurrency string

	cmd := &cobra.Command{
		Use:   "get-timeline",
		Short: "Get deals timeline",
		Example: "  pipedrive-cli deals get-timeline",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/deals/timeline"
			params := map[string]string{}
			if flagStartDate != "" {
				params["start_date"] = fmt.Sprintf("%v", flagStartDate)
			}
			if flagInterval != "" {
				params["interval"] = fmt.Sprintf("%v", flagInterval)
			}
			if flagAmount != 0 {
				params["amount"] = fmt.Sprintf("%v", flagAmount)
			}
			if flagFieldKey != "" {
				params["field_key"] = fmt.Sprintf("%v", flagFieldKey)
			}
			if flagUserId != 0 {
				params["user_id"] = fmt.Sprintf("%v", flagUserId)
			}
			if flagPipelineId != 0 {
				params["pipeline_id"] = fmt.Sprintf("%v", flagPipelineId)
			}
			if flagFilterId != 0 {
				params["filter_id"] = fmt.Sprintf("%v", flagFilterId)
			}
			if flagExcludeDeals != 0.0 {
				params["exclude_deals"] = fmt.Sprintf("%v", flagExcludeDeals)
			}
			if flagTotalsConvertCurrency != "" {
				params["totals_convert_currency"] = fmt.Sprintf("%v", flagTotalsConvertCurrency)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "The date when the first interval starts. Format: YYYY-MM-DD.")
	_ = cmd.MarkFlagRequired("start-date")
	cmd.Flags().StringVar(&flagInterval, "interval", "", "The type of the interval<table><tr><th>Value</th><th>Description</th></tr><tr><td>`day`</td><td>Day</td></tr><tr><td>...")
	_ = cmd.MarkFlagRequired("interval")
	cmd.Flags().IntVar(&flagAmount, "amount", 0, "The number of given intervals, starting from `start_date`, to fetch. E.g. 3 (months).")
	_ = cmd.MarkFlagRequired("amount")
	cmd.Flags().StringVar(&flagFieldKey, "field-key", "", "The date field key which deals will be retrieved from")
	_ = cmd.MarkFlagRequired("field-key")
	cmd.Flags().IntVar(&flagUserId, "user-id", 0, "If supplied, only deals matching the given user will be returned")
	cmd.Flags().IntVar(&flagPipelineId, "pipeline-id", 0, "If supplied, only deals matching the given pipeline will be returned")
	cmd.Flags().IntVar(&flagFilterId, "filter-id", 0, "If supplied, only deals matching the given filter will be returned")
	cmd.Flags().Float64Var(&flagExcludeDeals, "exclude-deals", 0.0, "Whether to exclude deals list (1) or not (0). Note that when deals are excluded, the timeline summary (counts and...")
	cmd.Flags().StringVar(&flagTotalsConvertCurrency, "totals-convert-currency", "", "The 3-letter currency code of any of the supported currencies. When supplied, `totals_converted` is returned per...")

	return cmd
}

