// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newFiltersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "filters",
		Short: "Each filter is essentially a set of data validation conditions. A filter of the same kind can be applied when...",
	}

	cmd.AddCommand(newFiltersAddCmd(flags))
	cmd.AddCommand(newFiltersDeleteCmd(flags))
	cmd.AddCommand(newFiltersDeleteIdCmd(flags))
	cmd.AddCommand(newFiltersGetCmd(flags))
	cmd.AddCommand(newFiltersGetHelpersCmd(flags))
	cmd.AddCommand(newFiltersGetIdCmd(flags))
	cmd.AddCommand(newFiltersUpdateCmd(flags))
	return cmd
}

func newFiltersAddCmd(flags *rootFlags) *cobra.Command {
	var bodyName string

	cmd := &cobra.Command{
		Use:   "add",
		Aliases: []string{"create"},
		Short: "Add a new filter",
		Example: "  pipedrive-cli filters add --name value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/filters"
			body := map[string]any{}
			if bodyName != "" {
				body["name"] = bodyName
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the filter")
	_ = cmd.MarkFlagRequired("name")

	return cmd
}

func newFiltersDeleteCmd(flags *rootFlags) *cobra.Command {
	var flagIds string

	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete multiple filters in bulk",
		Example: "  pipedrive-cli filters delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/filters"
			data, err := c.Delete(path)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagIds, "ids", "", "The comma-separated filter IDs to delete")
	_ = cmd.MarkFlagRequired("ids")

	return cmd
}

func newFiltersDeleteIdCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "delete-id <id>",
		Short: "Delete a filter",
		Example: "  pipedrive-cli filters delete-id <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/filters/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			data, err := c.Delete(path)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newFiltersGetCmd(flags *rootFlags) *cobra.Command {
	var flagType string

	cmd := &cobra.Command{
		Use:   "get",
		Aliases: []string{"list"},
		Short: "Get all filters",
		Example: "  pipedrive-cli filters get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/filters"
			params := map[string]string{}
			if flagType != "" {
				params["type"] = fmt.Sprintf("%v", flagType)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagType, "type", "", "The types of filters to fetch")

	return cmd
}

func newFiltersGetHelpersCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "get-helpers",
		Short: "Get all filter helpers",
		Example: "  pipedrive-cli filters get-helpers",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/filters/helpers"
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newFiltersGetIdCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "get-id <id>",
		Short: "Get one filter",
		Example: "  pipedrive-cli filters get-id <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/filters/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newFiltersUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyName string

	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Update filter",
		Example: "  pipedrive-cli filters update <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/filters/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			body := map[string]any{}
			if bodyName != "" {
				body["name"] = bodyName
			}
			data, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the filter")

	return cmd
}

