// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newOauthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "oauth",
		Short: "Using OAuth 2.0 is necessary for developing apps that are available in the Pipedrive Marketplace. Authorization via...",
	}

	cmd.AddCommand(newOauthAuthorizeCmd(flags))
	cmd.AddCommand(newOauthGetTokensCmd(flags))
	cmd.AddCommand(newOauthRefreshTokensCmd(flags))
	return cmd
}

func newOauthAuthorizeCmd(flags *rootFlags) *cobra.Command {
	var flagClientId string
	var flagRedirectUri string
	var flagState string

	cmd := &cobra.Command{
		Use:   "authorize",
		Aliases: []string{"list"},
		Short: "Requesting authorization",
		Example: "  pipedrive-cli oauth authorize",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/oauth/authorize"
			params := map[string]string{}
			if flagClientId != "" {
				params["client_id"] = fmt.Sprintf("%v", flagClientId)
			}
			if flagRedirectUri != "" {
				params["redirect_uri"] = fmt.Sprintf("%v", flagRedirectUri)
			}
			if flagState != "" {
				params["state"] = fmt.Sprintf("%v", flagState)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagClientId, "client-id", "", "The client ID provided to you by the Pipedrive Marketplace when you register your app")
	_ = cmd.MarkFlagRequired("client-id")
	cmd.Flags().StringVar(&flagRedirectUri, "redirect-uri", "", "The callback URL you provided when you registered your app. Authorization code will be sent to that URL (if it...")
	_ = cmd.MarkFlagRequired("redirect-uri")
	cmd.Flags().StringVar(&flagState, "state", "", "You may pass any random string as the state parameter and the same string will be returned to your app after a user...")

	return cmd
}

func newOauthGetTokensCmd(flags *rootFlags) *cobra.Command {
	var bodyCode string
	var bodyGrantType string
	var bodyRedirectUri string

	cmd := &cobra.Command{
		Use:   "get-tokens",
		Aliases: []string{"create"},
		Short: "Getting the tokens",
		Example: "  pipedrive-cli oauth get-tokens",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/oauth/token"
			body := map[string]any{}
			if bodyCode != "" {
				body["code"] = bodyCode
			}
			if bodyGrantType != "" {
				body["grant_type"] = bodyGrantType
			}
			if bodyRedirectUri != "" {
				body["redirect_uri"] = bodyRedirectUri
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyCode, "code", "", "The authorization code that you received after the user confirmed app installation")
	cmd.Flags().StringVar(&bodyGrantType, "grant-type", "authorization_code", "Since you are trying to exchange an authorization code for a pair of tokens, you must use the value 'authorization_code'")
	cmd.Flags().StringVar(&bodyRedirectUri, "redirect-uri", "", "The callback URL you provided when you registered your app")

	return cmd
}

func newOauthRefreshTokensCmd(flags *rootFlags) *cobra.Command {
	var bodyGrantType string
	var bodyRefreshToken string

	cmd := &cobra.Command{
		Use:   "refresh-tokens",
		Short: "Refreshing the tokens",
		Example: "  pipedrive-cli oauth refresh-tokens",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/oauth/token/"
			body := map[string]any{}
			if bodyGrantType != "" {
				body["grant_type"] = bodyGrantType
			}
			if bodyRefreshToken != "" {
				body["refresh_token"] = bodyRefreshToken
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyGrantType, "grant-type", "refresh_token", "Since you are to refresh your access_token, you must use the value 'refresh_token'")
	cmd.Flags().StringVar(&bodyRefreshToken, "refresh-token", "", "The refresh token that you received after you exchanged the authorization code")

	return cmd
}

