// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newOrganizationsChangelogCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "changelog",
		Short: "Manage changelog",
	}

	cmd.AddCommand(newOrganizationsChangelogGetOrganizationCmd(flags))
	return cmd
}

func newOrganizationsChangelogGetOrganizationCmd(flags *rootFlags) *cobra.Command {
	var flagCursor string
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "get-organization <id>",
		Aliases: []string{"get"},
		Short: "List updates about organization field values",
		Example: "  pipedrive-cli organizations changelog get-organization <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organizations/{id}/changelog"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			data, err := paginatedGet(c, path, map[string]string{
				"cursor": fmt.Sprintf("%v", flagCursor),
				"limit": fmt.Sprintf("%v", flagLimit),
			}, flagAll, "cursor", "", "")
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "For pagination, the marker (an opaque string value) representing the first item on the next page")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Items shown per page")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}

