// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newOrganizationFieldsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "organization-fields",
		Short: "Organization fields represent the near-complete schema for an organization in the context of the company of the...",
	}

	cmd.AddCommand(newOrganizationFieldsAddCmd(flags))
	cmd.AddCommand(newOrganizationFieldsDeleteCmd(flags))
	cmd.AddCommand(newOrganizationFieldsDeleteOrganizationfieldsCmd(flags))
	cmd.AddCommand(newOrganizationFieldsGetCmd(flags))
	cmd.AddCommand(newOrganizationFieldsGetOrganizationfieldsCmd(flags))
	cmd.AddCommand(newOrganizationFieldsUpdateCmd(flags))
	return cmd
}

func newOrganizationFieldsAddCmd(flags *rootFlags) *cobra.Command {
	var bodyAddVisibleFlag bool
	var bodyFieldType string
	var bodyName string

	cmd := &cobra.Command{
		Use:   "add",
		Aliases: []string{"create"},
		Short: "Add a new organization field",
		Example: "  pipedrive-cli organization-fields add --field-type value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organizationFields"
			body := map[string]any{}
			if bodyAddVisibleFlag != false {
				body["add_visible_flag"] = bodyAddVisibleFlag
			}
			if bodyFieldType != "" {
				body["field_type"] = bodyFieldType
			}
			if bodyName != "" {
				body["name"] = bodyName
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().BoolVar(&bodyAddVisibleFlag, "add-visible-flag", true, "Whether the field is available in the 'add new' modal or not (both in the web and mobile app)")
	cmd.Flags().StringVar(&bodyFieldType, "field-type", "", "The type of the field<table><tr><th>Value</th><th>Description</th></tr><tr><td>`address`</td><td>Address...")
	_ = cmd.MarkFlagRequired("field-type")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the field")
	_ = cmd.MarkFlagRequired("name")

	return cmd
}

func newOrganizationFieldsDeleteCmd(flags *rootFlags) *cobra.Command {
	var flagIds string

	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete multiple organization fields in bulk",
		Example: "  pipedrive-cli organization-fields delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organizationFields"
			data, err := c.Delete(path)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagIds, "ids", "", "The comma-separated field IDs to delete")
	_ = cmd.MarkFlagRequired("ids")

	return cmd
}

func newOrganizationFieldsDeleteOrganizationfieldsCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "delete-organizationfields <id>",
		Short: "Delete an organization field",
		Example: "  pipedrive-cli organization-fields delete-organizationfields <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organizationFields/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			data, err := c.Delete(path)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newOrganizationFieldsGetCmd(flags *rootFlags) *cobra.Command {
	var flagStart int
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "get",
		Aliases: []string{"list"},
		Short: "Get all organization fields",
		Example: "  pipedrive-cli organization-fields get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organizationFields"
			data, err := paginatedGet(c, path, map[string]string{
				"start": fmt.Sprintf("%v", flagStart),
				"limit": fmt.Sprintf("%v", flagLimit),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&flagStart, "start", 0, "Pagination start")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Items shown per page")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}

func newOrganizationFieldsGetOrganizationfieldsCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "get-organizationfields <id>",
		Short: "Get one organization field",
		Example: "  pipedrive-cli organization-fields get-organizationfields <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organizationFields/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newOrganizationFieldsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyAddVisibleFlag bool
	var bodyName string

	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Update an organization field",
		Example: "  pipedrive-cli organization-fields update <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organizationFields/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			body := map[string]any{}
			if bodyAddVisibleFlag != false {
				body["add_visible_flag"] = bodyAddVisibleFlag
			}
			if bodyName != "" {
				body["name"] = bodyName
			}
			data, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().BoolVar(&bodyAddVisibleFlag, "add-visible-flag", true, "Whether the field is available in 'add new' modal or not (both in web and mobile app)")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the field")

	return cmd
}

