// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newOrganizationsMergeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "merge",
		Short: "Manage merge",
	}

	cmd.AddCommand(newOrganizationsMergeOrganizationsCmd(flags))
	return cmd
}

func newOrganizationsMergeOrganizationsCmd(flags *rootFlags) *cobra.Command {
	var bodyMergeWithId int

	cmd := &cobra.Command{
		Use:   "organizations <id>",
		Aliases: []string{"update"},
		Short: "Merge two organizations",
		Example: "  pipedrive-cli organizations merge organizations <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organizations/{id}/merge"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			body := map[string]any{}
			if bodyMergeWithId != 0 {
				body["merge_with_id"] = bodyMergeWithId
			}
			data, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&bodyMergeWithId, "merge-with-id", 0, "The ID of the organization that the organization will be merged with")
	_ = cmd.MarkFlagRequired("merge-with-id")

	return cmd
}

