// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newOrganizationRelationshipsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "organization-relationships",
		Short: "Organization relationships represent how different organizations are related to each other. The relationship can be...",
	}

	cmd.AddCommand(newOrganizationRelationshipsAddCmd(flags))
	cmd.AddCommand(newOrganizationRelationshipsDeleteCmd(flags))
	cmd.AddCommand(newOrganizationRelationshipsGetCmd(flags))
	cmd.AddCommand(newOrganizationRelationshipsGetOrganizationrelationshipsCmd(flags))
	cmd.AddCommand(newOrganizationRelationshipsUpdateCmd(flags))
	return cmd
}

func newOrganizationRelationshipsAddCmd(flags *rootFlags) *cobra.Command {
	var bodyOrgId int
	var bodyRelLinkedOrgId int
	var bodyRelOwnerOrgId int
	var bodyType string

	cmd := &cobra.Command{
		Use:   "add",
		Aliases: []string{"create"},
		Short: "Create an organization relationship",
		Example: "  pipedrive-cli organization-relationships add --type value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organizationRelationships"
			body := map[string]any{}
			if bodyOrgId != 0 {
				body["org_id"] = bodyOrgId
			}
			if bodyRelLinkedOrgId != 0 {
				body["rel_linked_org_id"] = bodyRelLinkedOrgId
			}
			if bodyRelOwnerOrgId != 0 {
				body["rel_owner_org_id"] = bodyRelOwnerOrgId
			}
			if bodyType != "" {
				body["type"] = bodyType
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&bodyOrgId, "org-id", 0, "The ID of the base organization for the returned calculated values")
	cmd.Flags().IntVar(&bodyRelLinkedOrgId, "rel-linked-org-id", 0, "The linked organization in the relationship. If type is `parent`, then the linked organization is the daughter.")
	_ = cmd.MarkFlagRequired("rel-linked-org-id")
	cmd.Flags().IntVar(&bodyRelOwnerOrgId, "rel-owner-org-id", 0, "The owner of the relationship. If type is `parent`, then the owner is the parent and the linked organization is the...")
	_ = cmd.MarkFlagRequired("rel-owner-org-id")
	cmd.Flags().StringVar(&bodyType, "type", "", "The type of organization relationship")
	_ = cmd.MarkFlagRequired("type")

	return cmd
}

func newOrganizationRelationshipsDeleteCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Delete an organization relationship",
		Example: "  pipedrive-cli organization-relationships delete <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organizationRelationships/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			data, err := c.Delete(path)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newOrganizationRelationshipsGetCmd(flags *rootFlags) *cobra.Command {
	var flagOrgId int

	cmd := &cobra.Command{
		Use:   "get",
		Aliases: []string{"list"},
		Short: "Get all relationships for organization",
		Example: "  pipedrive-cli organization-relationships get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organizationRelationships"
			params := map[string]string{}
			if flagOrgId != 0 {
				params["org_id"] = fmt.Sprintf("%v", flagOrgId)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&flagOrgId, "org-id", 0, "The ID of the organization to get relationships for")
	_ = cmd.MarkFlagRequired("org-id")

	return cmd
}

func newOrganizationRelationshipsGetOrganizationrelationshipsCmd(flags *rootFlags) *cobra.Command {
	var flagOrgId int

	cmd := &cobra.Command{
		Use:   "get-organizationrelationships <id>",
		Short: "Get one organization relationship",
		Example: "  pipedrive-cli organization-relationships get-organizationrelationships <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organizationRelationships/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			if flagOrgId != 0 {
				params["org_id"] = fmt.Sprintf("%v", flagOrgId)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&flagOrgId, "org-id", 0, "The ID of the base organization for the returned calculated values")

	return cmd
}

func newOrganizationRelationshipsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyOrgId int
	var bodyRelLinkedOrgId int
	var bodyRelOwnerOrgId int
	var bodyType string

	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Update an organization relationship",
		Example: "  pipedrive-cli organization-relationships update <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/organizationRelationships/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			body := map[string]any{}
			if bodyOrgId != 0 {
				body["org_id"] = bodyOrgId
			}
			if bodyRelLinkedOrgId != 0 {
				body["rel_linked_org_id"] = bodyRelLinkedOrgId
			}
			if bodyRelOwnerOrgId != 0 {
				body["rel_owner_org_id"] = bodyRelOwnerOrgId
			}
			if bodyType != "" {
				body["type"] = bodyType
			}
			data, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&bodyOrgId, "org-id", 0, "The ID of the base organization for the returned calculated values")
	cmd.Flags().IntVar(&bodyRelLinkedOrgId, "rel-linked-org-id", 0, "The linked organization in this relationship. If type is `parent`, then the linked organization is the daughter.")
	cmd.Flags().IntVar(&bodyRelOwnerOrgId, "rel-owner-org-id", 0, "The owner of this relationship. If type is `parent`, then the owner is the parent and the linked organization is the...")
	cmd.Flags().StringVar(&bodyType, "type", "", "The type of organization relationship")

	return cmd
}

