// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newPersonsPermittedUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "permitted-users",
		Short: "Manage permitted users",
	}

	cmd.AddCommand(newPersonsPermittedUsersGetPersonUsersCmd(flags))
	return cmd
}

func newPersonsPermittedUsersGetPersonUsersCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "get-person-users <id>",
		Aliases: []string{"get"},
		Short: "List permitted users",
		Example: "  pipedrive-cli persons permitted-users get-person-users <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/persons/{id}/permittedUsers"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

