// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newPersonFieldsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "person-fields",
		Short: "Person fields represent the near-complete schema for a person in the context of the company of the authorized user....",
	}

	cmd.AddCommand(newPersonFieldsAddCmd(flags))
	cmd.AddCommand(newPersonFieldsDeleteCmd(flags))
	cmd.AddCommand(newPersonFieldsDeletePersonfieldsCmd(flags))
	cmd.AddCommand(newPersonFieldsGetCmd(flags))
	cmd.AddCommand(newPersonFieldsGetPersonfieldsCmd(flags))
	cmd.AddCommand(newPersonFieldsUpdateCmd(flags))
	return cmd
}

func newPersonFieldsAddCmd(flags *rootFlags) *cobra.Command {
	var bodyAddVisibleFlag bool
	var bodyFieldType string
	var bodyName string

	cmd := &cobra.Command{
		Use:   "add",
		Aliases: []string{"create"},
		Short: "Add a new person field",
		Example: "  pipedrive-cli person-fields add --field-type value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/personFields"
			body := map[string]any{}
			if bodyAddVisibleFlag != false {
				body["add_visible_flag"] = bodyAddVisibleFlag
			}
			if bodyFieldType != "" {
				body["field_type"] = bodyFieldType
			}
			if bodyName != "" {
				body["name"] = bodyName
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().BoolVar(&bodyAddVisibleFlag, "add-visible-flag", true, "Whether the field is available in the 'add new' modal or not (both in the web and mobile app)")
	cmd.Flags().StringVar(&bodyFieldType, "field-type", "", "The type of the field<table><tr><th>Value</th><th>Description</th></tr><tr><td>`address`</td><td>Address...")
	_ = cmd.MarkFlagRequired("field-type")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the field")
	_ = cmd.MarkFlagRequired("name")

	return cmd
}

func newPersonFieldsDeleteCmd(flags *rootFlags) *cobra.Command {
	var flagIds string

	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete multiple person fields in bulk",
		Example: "  pipedrive-cli person-fields delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/personFields"
			data, err := c.Delete(path)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagIds, "ids", "", "The comma-separated field IDs to delete")
	_ = cmd.MarkFlagRequired("ids")

	return cmd
}

func newPersonFieldsDeletePersonfieldsCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "delete-personfields <id>",
		Short: "Delete a person field",
		Example: "  pipedrive-cli person-fields delete-personfields <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/personFields/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			data, err := c.Delete(path)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newPersonFieldsGetCmd(flags *rootFlags) *cobra.Command {
	var flagStart int
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "get",
		Aliases: []string{"list"},
		Short: "Get all person fields",
		Example: "  pipedrive-cli person-fields get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/personFields"
			data, err := paginatedGet(c, path, map[string]string{
				"start": fmt.Sprintf("%v", flagStart),
				"limit": fmt.Sprintf("%v", flagLimit),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&flagStart, "start", 0, "Pagination start")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Items shown per page")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}

func newPersonFieldsGetPersonfieldsCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "get-personfields <id>",
		Short: "Get one person field",
		Example: "  pipedrive-cli person-fields get-personfields <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/personFields/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newPersonFieldsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyAddVisibleFlag bool
	var bodyName string

	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Update a person field",
		Example: "  pipedrive-cli person-fields update <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/personFields/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			body := map[string]any{}
			if bodyAddVisibleFlag != false {
				body["add_visible_flag"] = bodyAddVisibleFlag
			}
			if bodyName != "" {
				body["name"] = bodyName
			}
			data, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().BoolVar(&bodyAddVisibleFlag, "add-visible-flag", true, "Whether the field is available in 'add new' modal or not (both in web and mobile app)")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the field")

	return cmd
}

