// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newPersonsFilesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "files",
		Short: "Files are documents of any kind (images, spreadsheets, text files, etc.) that are uploaded to Pipedrive, and usually...",
	}

	cmd.AddCommand(newPersonsFilesGetPersonCmd(flags))
	return cmd
}

func newPersonsFilesGetPersonCmd(flags *rootFlags) *cobra.Command {
	var flagStart int
	var flagLimit int
	var flagSort string
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "get-person <id>",
		Aliases: []string{"get"},
		Short: "List files attached to a person",
		Example: "  pipedrive-cli persons files get-person <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/persons/{id}/files"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			data, err := paginatedGet(c, path, map[string]string{
				"start": fmt.Sprintf("%v", flagStart),
				"limit": fmt.Sprintf("%v", flagLimit),
				"sort": fmt.Sprintf("%v", flagSort),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&flagStart, "start", 0, "Pagination start")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Items shown per page. Please note that a maximum value of 100 is allowed.")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Supported fields: `id`, `update_time`")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}

