// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newProjectsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "projects",
		Short: "Projects represent ongoing, completed or canceled projects attached to an organization, person or to deals. Each...",
	}

	cmd.AddCommand(newProjectsAddCmd(flags))
	cmd.AddCommand(newProjectsDeleteCmd(flags))
	cmd.AddCommand(newProjectsGetCmd(flags))
	cmd.AddCommand(newProjectsGetBoardCmd(flags))
	cmd.AddCommand(newProjectsGetBoardsCmd(flags))
	cmd.AddCommand(newProjectsGetIdCmd(flags))
	cmd.AddCommand(newProjectsGetPhaseCmd(flags))
	cmd.AddCommand(newProjectsGetPhasesCmd(flags))
	cmd.AddCommand(newProjectsUpdateCmd(flags))
	cmd.AddCommand(newProjectsActivitiesCmd(flags))
	cmd.AddCommand(newProjectsArchiveCmd(flags))
	cmd.AddCommand(newProjectsGroupsCmd(flags))
	cmd.AddCommand(newProjectsPlanCmd(flags))
	cmd.AddCommand(newProjectsTasksCmd(flags))
	return cmd
}

func newProjectsAddCmd(flags *rootFlags) *cobra.Command {
	var bodyBoardId float64
	var bodyDescription string
	var bodyEndDate string
	var bodyOrgId float64
	var bodyOwnerId float64
	var bodyPersonId float64
	var bodyPhaseId float64
	var bodyStartDate string
	var bodyStatus string
	var bodyTemplateId float64
	var bodyTitle string

	cmd := &cobra.Command{
		Use:   "add",
		Aliases: []string{"create"},
		Short: "Add a project",
		Example: "  pipedrive-cli projects add --title value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/projects"
			body := map[string]any{}
			if bodyBoardId != 0.0 {
				body["board_id"] = bodyBoardId
			}
			if bodyDescription != "" {
				body["description"] = bodyDescription
			}
			if bodyEndDate != "" {
				body["end_date"] = bodyEndDate
			}
			if bodyOrgId != 0.0 {
				body["org_id"] = bodyOrgId
			}
			if bodyOwnerId != 0.0 {
				body["owner_id"] = bodyOwnerId
			}
			if bodyPersonId != 0.0 {
				body["person_id"] = bodyPersonId
			}
			if bodyPhaseId != 0.0 {
				body["phase_id"] = bodyPhaseId
			}
			if bodyStartDate != "" {
				body["start_date"] = bodyStartDate
			}
			if bodyStatus != "" {
				body["status"] = bodyStatus
			}
			if bodyTemplateId != 0.0 {
				body["template_id"] = bodyTemplateId
			}
			if bodyTitle != "" {
				body["title"] = bodyTitle
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().Float64Var(&bodyBoardId, "board-id", 0.0, "The ID of the board this project is associated with")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "The description of the project")
	cmd.Flags().StringVar(&bodyEndDate, "end-date", "", "The end date of the project. Format: YYYY-MM-DD.")
	cmd.Flags().Float64Var(&bodyOrgId, "org-id", 0.0, "The ID of the organization this project is associated with")
	cmd.Flags().Float64Var(&bodyOwnerId, "owner-id", 0.0, "The ID of a project owner")
	cmd.Flags().Float64Var(&bodyPersonId, "person-id", 0.0, "The ID of the person this project is associated with")
	cmd.Flags().Float64Var(&bodyPhaseId, "phase-id", 0.0, "The ID of the phase this project is associated with")
	cmd.Flags().StringVar(&bodyStartDate, "start-date", "", "The start date of the project. Format: YYYY-MM-DD.")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "The status of the project")
	cmd.Flags().Float64Var(&bodyTemplateId, "template-id", 0.0, "The ID of the template the project will be based on")
	cmd.Flags().StringVar(&bodyTitle, "title", "", "The title of the project")
	_ = cmd.MarkFlagRequired("title")

	return cmd
}

func newProjectsDeleteCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Delete a project",
		Example: "  pipedrive-cli projects delete <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/projects/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			data, err := c.Delete(path)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newProjectsGetCmd(flags *rootFlags) *cobra.Command {
	var flagCursor string
	var flagLimit int
	var flagFilterId int
	var flagStatus string
	var flagPhaseId int
	var flagIncludeArchived bool
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "get",
		Aliases: []string{"list"},
		Short: "Get all projects",
		Example: "  pipedrive-cli projects get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/projects"
			data, err := paginatedGet(c, path, map[string]string{
				"cursor": fmt.Sprintf("%v", flagCursor),
				"limit": fmt.Sprintf("%v", flagLimit),
				"filter_id": fmt.Sprintf("%v", flagFilterId),
				"status": fmt.Sprintf("%v", flagStatus),
				"phase_id": fmt.Sprintf("%v", flagPhaseId),
				"include_archived": fmt.Sprintf("%v", flagIncludeArchived),
			}, flagAll, "cursor", "", "")
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "For pagination, the marker (an opaque string value) representing the first item on the next page")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "For pagination, the limit of entries to be returned. If not provided, 100 items will be returned.")
	cmd.Flags().IntVar(&flagFilterId, "filter-id", 0, "The ID of the filter to use")
	cmd.Flags().StringVar(&flagStatus, "status", "", "If supplied, includes only projects with the specified statuses. Possible values are `open`, `completed`, `canceled`...")
	cmd.Flags().IntVar(&flagPhaseId, "phase-id", 0, "If supplied, only projects in specified phase are returned")
	cmd.Flags().BoolVar(&flagIncludeArchived, "include-archived", false, "If supplied with `true` then archived projects are also included in the response. By default only not archived...")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}

func newProjectsGetBoardCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "get-board <id>",
		Short: "Get details of a board",
		Example: "  pipedrive-cli projects get-board <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/projects/boards/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newProjectsGetBoardsCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "get-boards",
		Short: "Get all project boards",
		Example: "  pipedrive-cli projects get-boards",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/projects/boards"
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newProjectsGetIdCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "get-id <id>",
		Short: "Get details of a project",
		Example: "  pipedrive-cli projects get-id <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/projects/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newProjectsGetPhaseCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "get-phase <id>",
		Short: "Get details of a phase",
		Example: "  pipedrive-cli projects get-phase <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/projects/phases/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newProjectsGetPhasesCmd(flags *rootFlags) *cobra.Command {
	var flagBoardId int

	cmd := &cobra.Command{
		Use:   "get-phases",
		Short: "Get project phases",
		Example: "  pipedrive-cli projects get-phases",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/projects/phases"
			params := map[string]string{}
			if flagBoardId != 0 {
				params["board_id"] = fmt.Sprintf("%v", flagBoardId)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&flagBoardId, "board-id", 0, "ID of the board for which phases are requested")
	_ = cmd.MarkFlagRequired("board-id")

	return cmd
}

func newProjectsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyBoardId float64
	var bodyDescription string
	var bodyEndDate string
	var bodyOrgId float64
	var bodyOwnerId float64
	var bodyPersonId float64
	var bodyPhaseId float64
	var bodyStartDate string
	var bodyStatus string
	var bodyTitle string

	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Update a project",
		Example: "  pipedrive-cli projects update <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/projects/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			body := map[string]any{}
			if bodyBoardId != 0.0 {
				body["board_id"] = bodyBoardId
			}
			if bodyDescription != "" {
				body["description"] = bodyDescription
			}
			if bodyEndDate != "" {
				body["end_date"] = bodyEndDate
			}
			if bodyOrgId != 0.0 {
				body["org_id"] = bodyOrgId
			}
			if bodyOwnerId != 0.0 {
				body["owner_id"] = bodyOwnerId
			}
			if bodyPersonId != 0.0 {
				body["person_id"] = bodyPersonId
			}
			if bodyPhaseId != 0.0 {
				body["phase_id"] = bodyPhaseId
			}
			if bodyStartDate != "" {
				body["start_date"] = bodyStartDate
			}
			if bodyStatus != "" {
				body["status"] = bodyStatus
			}
			if bodyTitle != "" {
				body["title"] = bodyTitle
			}
			data, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().Float64Var(&bodyBoardId, "board-id", 0.0, "The ID of the board this project is associated with")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "The description of the project")
	cmd.Flags().StringVar(&bodyEndDate, "end-date", "", "The end date of the project. Format: YYYY-MM-DD.")
	cmd.Flags().Float64Var(&bodyOrgId, "org-id", 0.0, "The ID of the organization this project is associated with")
	cmd.Flags().Float64Var(&bodyOwnerId, "owner-id", 0.0, "The ID of a project owner")
	cmd.Flags().Float64Var(&bodyPersonId, "person-id", 0.0, "The ID of the person this project is associated with")
	cmd.Flags().Float64Var(&bodyPhaseId, "phase-id", 0.0, "The ID of the phase this project is associated with")
	cmd.Flags().StringVar(&bodyStartDate, "start-date", "", "The start date of the project. Format: YYYY-MM-DD.")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "The status of the project")
	cmd.Flags().StringVar(&bodyTitle, "title", "", "The title of the project")

	return cmd
}

