// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newRecentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "recents",
		Short: "Recent changes across all item types in Pipedrive (deals, persons, etc).",
	}

	cmd.AddCommand(newRecentsGetCmd(flags))
	return cmd
}

func newRecentsGetCmd(flags *rootFlags) *cobra.Command {
	var flagSinceTimestamp string
	var flagItems string
	var flagStart int
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "get",
		Aliases: []string{"list"},
		Short: "Get recents",
		Example: "  pipedrive-cli recents get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/recents"
			data, err := paginatedGet(c, path, map[string]string{
				"since_timestamp": fmt.Sprintf("%v", flagSinceTimestamp),
				"items": fmt.Sprintf("%v", flagItems),
				"start": fmt.Sprintf("%v", flagStart),
				"limit": fmt.Sprintf("%v", flagLimit),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&flagSinceTimestamp, "since-timestamp", "", "The timestamp in UTC. Format: YYYY-MM-DD HH:MM:SS.")
	_ = cmd.MarkFlagRequired("since-timestamp")
	cmd.Flags().StringVar(&flagItems, "items", "", "Multiple selection of item types to include in the query (optional)")
	cmd.Flags().IntVar(&flagStart, "start", 0, "Pagination start")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Items shown per page")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}

