// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newRolesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "roles",
		Short: "Roles are a part of the Visibility groups’ feature that allow the admin user to categorize other users and dictate...",
	}

	cmd.AddCommand(newRolesAddCmd(flags))
	cmd.AddCommand(newRolesDeleteCmd(flags))
	cmd.AddCommand(newRolesGetCmd(flags))
	cmd.AddCommand(newRolesGetIdCmd(flags))
	cmd.AddCommand(newRolesUpdateCmd(flags))
	cmd.AddCommand(newRolesAssignmentsCmd(flags))
	cmd.AddCommand(newRolesPipelinesCmd(flags))
	cmd.AddCommand(newRolesSettingsCmd(flags))
	return cmd
}

func newRolesAddCmd(flags *rootFlags) *cobra.Command {
	var bodyName string
	var bodyParentRoleId int

	cmd := &cobra.Command{
		Use:   "add",
		Aliases: []string{"create"},
		Short: "Add a role",
		Example: "  pipedrive-cli roles add --name value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/roles"
			body := map[string]any{}
			if bodyName != "" {
				body["name"] = bodyName
			}
			if bodyParentRoleId != 0 {
				body["parent_role_id"] = bodyParentRoleId
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the role")
	_ = cmd.MarkFlagRequired("name")
	cmd.Flags().IntVar(&bodyParentRoleId, "parent-role-id", 0, "The ID of the parent role")

	return cmd
}

func newRolesDeleteCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "delete <id>",
		Short: "Delete a role",
		Example: "  pipedrive-cli roles delete <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/roles/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			data, err := c.Delete(path)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newRolesGetCmd(flags *rootFlags) *cobra.Command {
	var flagStart int
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "get",
		Aliases: []string{"list"},
		Short: "Get all roles",
		Example: "  pipedrive-cli roles get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/roles"
			data, err := paginatedGet(c, path, map[string]string{
				"start": fmt.Sprintf("%v", flagStart),
				"limit": fmt.Sprintf("%v", flagLimit),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&flagStart, "start", 0, "Pagination start")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Items shown per page")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}

func newRolesGetIdCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "get-id <id>",
		Short: "Get one role",
		Example: "  pipedrive-cli roles get-id <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/roles/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

func newRolesUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyName string
	var bodyParentRoleId int

	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Update role details",
		Example: "  pipedrive-cli roles update <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/roles/{id}"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			body := map[string]any{}
			if bodyName != "" {
				body["name"] = bodyName
			}
			if bodyParentRoleId != 0 {
				body["parent_role_id"] = bodyParentRoleId
			}
			data, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the role")
	cmd.Flags().IntVar(&bodyParentRoleId, "parent-role-id", 0, "The ID of the parent role")

	return cmd
}

