// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newRolesPipelinesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "pipelines",
		Short: "Pipelines are essentially ordered collections of stages.",
	}

	cmd.AddCommand(newRolesPipelinesGetRoleCmd(flags))
	cmd.AddCommand(newRolesPipelinesUpdateRoleCmd(flags))
	return cmd
}

func newRolesPipelinesGetRoleCmd(flags *rootFlags) *cobra.Command {
	var flagVisible bool

	cmd := &cobra.Command{
		Use:   "get-role <id>",
		Aliases: []string{"get"},
		Short: "List pipeline visibility for a role",
		Example: "  pipedrive-cli roles pipelines get-role <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/roles/{id}/pipelines"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			if flagVisible != false {
				params["visible"] = fmt.Sprintf("%v", flagVisible)
			}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().BoolVar(&flagVisible, "visible", true, "Whether to return the visible or hidden pipelines for the role")

	return cmd
}

func newRolesPipelinesUpdateRoleCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "update-role <id>",
		Aliases: []string{"update"},
		Short: "Update pipeline visibility for a role",
		Example: "  pipedrive-cli roles pipelines update-role <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/roles/{id}/pipelines"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			body := map[string]any{}
			data, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

