// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newRolesSettingsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "settings",
		Short: "Manage settings",
	}

	cmd.AddCommand(newRolesSettingsAddOrUpdateRoleCmd(flags))
	cmd.AddCommand(newRolesSettingsGetRoleCmd(flags))
	return cmd
}

func newRolesSettingsAddOrUpdateRoleCmd(flags *rootFlags) *cobra.Command {
	var bodySettingKey string
	var bodyValue int

	cmd := &cobra.Command{
		Use:   "add-or-update-role <id>",
		Aliases: []string{"create"},
		Short: "Add or update role setting",
		Example: "  pipedrive-cli roles settings add-or-update-role <id> --setting-key value",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/roles/{id}/settings"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			body := map[string]any{}
			if bodySettingKey != "" {
				body["setting_key"] = bodySettingKey
			}
			if bodyValue != 0 {
				body["value"] = bodyValue
			}
			data, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().StringVar(&bodySettingKey, "setting-key", "", "Setting key")
	_ = cmd.MarkFlagRequired("setting-key")
	cmd.Flags().IntVar(&bodyValue, "value", 0, "Possible values for the `default_visibility` setting depending on the subscription plan:<br> <table...")
	_ = cmd.MarkFlagRequired("value")

	return cmd
}

func newRolesSettingsGetRoleCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "get-role <id>",
		Aliases: []string{"get"},
		Short: "List role settings",
		Example: "  pipedrive-cli roles settings get-role <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/roles/{id}/settings"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			data, err := c.Get(path, params)
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}

	return cmd
}

