// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newStagesDealsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "deals",
		Short: "Deals represent ongoing, lost or won sales to an organization or to a person. Each deal has a monetary value and...",
	}

	cmd.AddCommand(newStagesDealsGetStageCmd(flags))
	return cmd
}

func newStagesDealsGetStageCmd(flags *rootFlags) *cobra.Command {
	var flagFilterId int
	var flagUserId int
	var flagEveryone float64
	var flagStart int
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "get-stage <id>",
		Aliases: []string{"get"},
		Short: "Get deals in a stage",
		Example: "  pipedrive-cli stages deals get-stage <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/stages/{id}/deals"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			data, err := paginatedGet(c, path, map[string]string{
				"filter_id": fmt.Sprintf("%v", flagFilterId),
				"user_id": fmt.Sprintf("%v", flagUserId),
				"everyone": fmt.Sprintf("%v", flagEveryone),
				"start": fmt.Sprintf("%v", flagStart),
				"limit": fmt.Sprintf("%v", flagLimit),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&flagFilterId, "filter-id", 0, "If supplied, only deals matching the given filter will be returned")
	cmd.Flags().IntVar(&flagUserId, "user-id", 0, "If supplied, `filter_id` will not be considered and only deals owned by the given user will be returned. If omitted,...")
	cmd.Flags().Float64Var(&flagEveryone, "everyone", 0.0, "If supplied, `filter_id` and `user_id` will not be considered – instead, deals owned by everyone will be returned")
	cmd.Flags().IntVar(&flagStart, "start", 0, "Pagination start")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Items shown per page")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}

