// Code generated by CLI Printing Press. DO NOT EDIT.

package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

var _ = strings.ReplaceAll // ensure import
var _ = fmt.Sprintf        // ensure import

func newUsersRoleAssignmentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "role-assignments",
		Short: "Manage role assignments",
	}

	cmd.AddCommand(newUsersRoleAssignmentsGetUserCmd(flags))
	return cmd
}

func newUsersRoleAssignmentsGetUserCmd(flags *rootFlags) *cobra.Command {
	var flagStart int
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "get-user <id>",
		Aliases: []string{"get"},
		Short: "List role assignments",
		Example: "  pipedrive-cli users role-assignments get-user <id>",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/users/{id}/roleAssignments"
			if len(args) < 1 {
				return usageErr(fmt.Errorf("id is required"))
			}
			path = replacePathParam(path, "id", args[0])
			data, err := paginatedGet(c, path, map[string]string{
				"start": fmt.Sprintf("%v", flagStart),
				"limit": fmt.Sprintf("%v", flagLimit),
			}, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err)
			}

			return printOutput(cmd.OutOrStdout(), data, flags.asJSON)
		},
	}
	cmd.Flags().IntVar(&flagStart, "start", 0, "Pagination start")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Items shown per page")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}

